// =============================================================================
// Build canonical /workspace/data/projects.json — PART 2
// Continuation: DeFi, RWA, Gaming
// Every project carries:
//   id, name, symbol, sector, sectors[], coingeckoId, cmcId, cmcSlug,
//   githubOrg, githubRepo, xHandle, website, description, tier,
//   verifiedStatus, lastVerifiedAt
// =============================================================================

const PROJECTS = [];
const seenIds = new Set();

function add(p) {
  if (!p.id) throw new Error('Missing id');
  if (seenIds.has(p.id)) throw new Error('Duplicate id: ' + p.id);
  seenIds.add(p.id);

  p.name = p.name || p.id;
  p.symbol = (p.symbol || '').toUpperCase();
  p.sector = p.sector || 'defi';
  p.sectors = p.sectors || [p.sector];
  p.coingeckoId = p.coingeckoId || p.id;
  p.cmcId = p.cmcId || null;
  p.cmcSlug = p.cmcSlug || p.id;
  p.githubOrg = p.githubOrg || null;
  p.githubRepo = p.githubRepo || (p.githubOrg ? p.githubOrg : null);
  p.xHandle = p.xHandle || null;
  p.website = p.website || null;
  p.description = p.description || '';
  p.verifiedStatus = 'verified';
  p.tier = p.tier || 'tier2';
  p.lastVerifiedAt = '2026-07-16';

  const set = new Set([p.sector, ...p.sectors]);
  p.sectors = Array.from(set);

  PROJECTS.push(p);
}

// =============================================================================
// DEFI (45) — decentralized finance protocols
// =============================================================================
add({ id:'uniswap', symbol:'UNI', sector:'defi', coingeckoId:'uniswap', cmcId:'7083', cmcSlug:'uniswap', githubOrg:'Uniswap', githubRepo:'Uniswap/v3-core', xHandle:'Uniswap', website:'https://uniswap.org', description:'Largest Ethereum DEX using constant-product and concentrated-liquidity AMM, with the UNI token governing the Uniswap DAO and protocol fees.', tier:'tier1' });
add({ id:'aave', symbol:'AAVE', sector:'defi', coingeckoId:'aave', cmcId:'7278', cmcSlug:'aave', githubOrg:'aave', githubRepo:'aave/aave-v3-core', xHandle:'AaveAave', website:'https://aave.com', description:'Leading non-custodial liquidity protocol for lending and borrowing crypto assets via algorithmically-set, utilization-based interest rates.', tier:'tier1' });
add({ id:'maker', symbol:'MKR', sector:'defi', coingeckoId:'maker', cmcId:'1518', cmcSlug:'maker', githubOrg:'makerdao', githubRepo:'makerdao/dss', xHandle:'MakerDAO', website:'https://makerdao.com', description:'Decentralized credit facility issuing the DAI stablecoin through collateralized debt positions (CDPs) and governed by MKR holders.', tier:'tier1' });
add({ id:'lido-dao', symbol:'LDO', sector:'defi', coingeckoId:'lido-dao', cmcId:'8000', cmcSlug:'lido-dao', githubOrg:'lidofinance', githubRepo:'lidofinance/core', xHandle:'lidofinance', website:'https://lido.fi', description:'Liquid staking protocol issuing stETH, stMATIC and other wrapped-staking tokens so users can earn PoS yield while keeping assets usable in DeFi.', tier:'tier1' });
add({ id:'curve-dao-token', symbol:'CRV', sector:'defi', coingeckoId:'curve-dao-token', cmcId:'6538', cmcSlug:'curve-dao-token', githubOrg:'curvefi', githubRepo:'curvefi/curve-contract', xHandle:'CurveFinance', website:'https://curve.fi', description:'DEX optimized for stablecoin and like-kind asset swaps using bonding-curve AMMs, governed by veCRV vote-escrow model.', tier:'tier1' });
add({ id:'compound-governance-token', symbol:'COMP', sector:'defi', coingeckoId:'compound-governance-token', cmcId:'5692', cmcSlug:'compound', githubOrg:'compound-finance', githubRepo:'compound-finance/compound-protocol', xHandle:'compoundfinance', website:'https://compound.finance', description:'Algorithmic, autonomous interest-rate protocol for lending and borrowing ETH and ERC-20s, pioneering DeFi money markets.', tier:'tier1' });
add({ id:'rocket-pool-eth', symbol:'RPL', sector:'defi', coingeckoId:'rocket-pool-eth', cmcId:'2943', cmcSlug:'rocket-pool', githubOrg:'rocket-pool', githubRepo:'rocket-pool/smartnode', xHandle:'Rocket_Pool', website:'https://rocketpool.net', description:'Decentralized Ethereum staking protocol that lets anyone run a validator with just 8 ETH and earn rETH rewards.', tier:'tier1' });
add({ id:'frax', symbol:'FXS', sector:'defi', coingeckoId:'frax', cmcId:'6952', cmcSlug:'frax', githubOrg:'FraxFinance', githubRepo:'FraxFinance/frax-solidity', xHandle:'fraxfinance', website:'https://frax.finance', description:'Hybrid algorithmic-fractional stablecoin protocol (FRAX) plus Fraxswap, Fraxlend, Frax Ether (frxETH) and other DeFi primitives.', tier:'tier1' });
add({ id:'pendle', symbol:'PENDLE', sector:'defi', coingeckoId:'pendle', cmcId:'9481', cmcSlug:'pendle', githubOrg:'pendle-finance', githubRepo:'pendle-finance/pendle-core', xHandle:'pendle_fi', website:'https://www.pendle.finance', description:'Yield-tokenization protocol splitting yield-bearing assets into principal and yield tokens tradable on Pendle AMM.', tier:'tier1' });
add({ id:'convex-finance', symbol:'CVX', sector:'defi', coingeckoId:'convex-finance', cmcId:'9903', cmcSlug:'convex-finance', githubOrg:'convex-eth', githubRepo:'convex-eth/convex-platform', xHandle:'ConvexFinance', website:'https://www.convexfinance.com', description:'Boosted-yield wrapper for Curve liquidity providers, allowing vlCVX holders to earn boosted CRV rewards without locking CRV themselves.', tier:'tier1' });
add({ id:'synthetix', symbol:'SNX', sector:'defi', coingeckoId:'havven', cmcId:'2586', cmcSlug:'synthetix', githubOrg:'Synthetixio', githubRepo:'Synthetixio/synthetix-v3', xHandle:'synthetix_io', website:'https://synthetix.io', description:'Decentralized synthetic-asset issuance platform on Ethereum and Optimism providing on-chain exposure to crypto, forex and commodities via SNX-collateralized sAssets.', tier:'tier1' });
add({ id:'1inch', symbol:'1INCH', sector:'defi', coingeckoId:'1inch', cmcId:'8104', cmcSlug:'1inch', githubOrg:'1inch', githubRepo:'1inch/limit-order-protocol', xHandle:'1inch', website:'https://1inch.io', description:'DEX aggregator that splits user trades across multiple liquidity sources to deliver best execution and lowest slippage on Ethereum and 12+ chains.', tier:'tier1' });
add({ id:'dydx', symbol:'DYDX', sector:'defi', coingeckoId:'dydx', cmcId:'11156', cmcSlug:'dydx', githubOrg:'dydxprotocol', githubRepo:'dydxprotocol/v4-chain', xHandle:'dYdX', website:'https://dydx.xyz', description:'Decentralized perpetual futures exchange running its own Cosmos app-chain (dYdX Chain) with off-chain matching and on-chain settlement.', tier:'tier1' });
add({ id:'gmx', symbol:'GMX', sector:'defi', coingeckoId:'gmx', cmcId:'11857', cmcSlug:'gmx', githubOrg:'gmx-io', githubRepo:'gmx-io/gmx-synthetics', xHandle:'GMX_IO', website:'https://gmx.io', description:'Decentralized perpetual exchange on Arbitrum and Avalanche using a multi-asset GLP liquidity pool to offer zero-price-impact trades.', tier:'tier1' });
add({ id:'balancer', symbol:'BAL', sector:'defi', coingeckoId:'balancer', cmcId:'5728', cmcSlug:'balancer', githubOrg:'balancer', githubRepo:'balancer/balancer-v2-monorepo', xHandle:'Balancer', website:'https://balancer.fi', description:'Programmable liquidity protocol enabling weighted, stable and boosted pools, used for index-style AMM portfolios and veBAL gauges.', tier:'tier1' });
add({ id:'yearn-finance', symbol:'YFI', sector:'defi', coingeckoId:'yearn-finance', cmcId:'5864', cmcSlug:'yearn-finance', githubOrg:'yearn', githubRepo:'yearn/yearn-vaults', xHandle:'yearnfi', website:'https://yearn.fi', description:'Yield-aggregator vault protocol that automates strategies for stablecoins, ETH and BTC to maximize risk-adjusted returns.', tier:'tier1' });
add({ id:'instadapp', symbol:'INST', sector:'defi', coingeckoId:'instadapp', cmcId:'6363', cmcSlug:'instadapp', githubOrg:'Instadapp', githubRepo:'Instadapp/dsa-contracts', xHandle:'Instadapp', website:'https://instadapp.io', description:'DeFi smart-account and leverage-management layer (DSA, Lite, Avocado) that aggregates protocols like Aave, Compound and Maker into one interface.', tier:'tier1' });
add({ id:'sushi', symbol:'SUSHI', sector:'defi', coingeckoId:'sushi', cmcId:'6758', cmcSlug:'sushi', githubOrg:'sushiswap', githubRepo:'sushiswap/sushiswap', xHandle:'SushiSwap', website:'https://www.sushi.com', description:'Community-driven multi-chain DEX with AMM, Kashi lending and Trident concentrated-liquidity pools, plus the onsen liquidity-mining program.', tier:'tier1' });
add({ id:'pancakeswap-token', symbol:'CAKE', sector:'defi', coingeckoId:'pancakeswap-token', cmcId:'7188', cmcSlug:'pancakeswap', githubOrg:'pancakeswap', githubRepo:'pancakeswap/pancake-frontend', xHandle:'PancakeSwap', website:'https://pancakeswap.finance', description:'Largest DEX on BNB Chain featuring AMM, farms, syrup pools, perpetuals and prediction markets, with a deflationary CAKE token.', tier:'tier1' });
add({ id:'jupiter-exchange-solana', symbol:'JUP', sector:'defi', coingeckoId:'jupiter-exchange-solana', cmcId:'29210', cmcSlug:'jupiter', githubOrg:'jup-ag', githubRepo:'jup-ag/jup-core', xHandle:'JupiterExchange', website:'https://jup.ag', description:'Solana DEX aggregator and liquidity routing layer powering best-price swaps and limit orders, plus the JUP governance and launchpad airdrop.', tier:'tier1' });
add({ id:'raydium', symbol:'RAY', sector:'defi', coingeckoId:'raydium', cmcId:'8526', cmcSlug:'raydium', githubOrg:'raydium-io', githubRepo:'raydium-io/raydium-amm', xHandle:'RaydiumProtocol', website:'https://raydium.io', description:'Solana AMM and order-book DEX sharing liquidity with OpenBook, featuring concentrated-liquidity pools and an AcceleRaytor launchpad.', tier:'tier1' });
add({ id:'orca', symbol:'ORCA', sector:'defi', coingeckoId:'orca', cmcId:'11165', cmcSlug:'orca', githubOrg:'orca-so', githubRepo:'orca-so/whirlpools', xHandle:'orca_so', website:'https://www.orca.so', description:'Solana concentrated-liquidity AMM (Whirlpools) and aggregation-friendly swap router, governed by the Orca DAO.', tier:'tier1' });
add({ id:'morpho', symbol:'MORPHO', sector:'defi', coingeckoId:'morpho', cmcId:'27616', cmcSlug:'morpho', githubOrg:'morpho-org', githubRepo:'morpho-org/morpho-blue', xHandle:'MorphoLabs', website:'https://morpho.org', description:'Optimized lending markets on top of Aave and Compound, plus the immutable Morpho Blue money-market primitive.', tier:'tier1' });
add({ id:'spark', symbol:'SPK', sector:'defi', coingeckoId:'spark-2', cmcId:'31980', cmcSlug:'spark-2', githubOrg:'sparkdotfi', githubRepo:'sparkdotfi/sparklend', xHandle:'sparkdotfi', website:'https://spark.fi', description:'Sky/Maker ecosystem lending market (Spark Lend) and sub-DAO, deploying DAI savings and real-world assets into on-chain credit markets.', tier:'tier1' });
add({ id:'ondo-finance', symbol:'ONDO', sector:'defi', sectors:['defi','rwa'], coingeckoId:'ondo-finance', cmcId:'21159', cmcSlug:'ondo-finance', githubOrg:'ondofinance', githubRepo:'ondofinance/ondo-protocol', xHandle:'OndoFinance', website:'https://ondo.finance', description:'Institutional-grade tokenized US Treasuries (OUSG, OMMF) and structured products that bring yield-bearing RWAs onchain for DeFi use.', tier:'tier1' });
add({ id:'ethena', symbol:'ENA', sector:'defi', coingeckoId:'ethena', cmcId:'30171', cmcSlug:'ethena', githubOrg:'ethena-labs', githubRepo:'ethena-labs/ethena', xHandle:'ethena_labs', website:'https://ethena.fi', description:'Synthetic dollar protocol issuing USDe via delta-neutral ETH perp hedging, plus the sUSDe yield-bearing wrapper and ENA governance token.', tier:'tier1' });
add({ id:'kamino', symbol:'KMNO', sector:'defi', coingeckoId:'kamino-2', cmcId:'28688', cmcSlug:'kamino-2', githubOrg:'Kamino-Finance', githubRepo:'Kamino-Finance/klend', xHandle:'KaminoFinance', website:'https://kamino.com', description:'Solana-native money market, automated liquidity vault and HODL strategy protocol, used by leading LSTs and LPs.', tier:'tier1' });
add({ id:'euler', symbol:'EUL', sector:'defi', coingeckoId:'euler', cmcId:'14239', cmcSlug:'euler', githubOrg:'euler-xyz', githubRepo:'euler-xyz/euler-v2', xHandle:'eulerfinance', website:'https://www.euler.xyz', description:'Permissionless lending protocol with modular risk-tiered markets (ERC-4626 vaults) and reactive interest rates on Ethereum and L2s.', tier:'tier1' });
add({ id:'mango', symbol:'MNGO', sector:'defi', coingeckoId:'mango', cmcId:'11152', cmcSlug:'mango', githubOrg:'blockworks-foundation', githubRepo:'blockworks-foundation/mango-v4', xHandle:'mangomarkets', website:'https://mango.markets', description:'Solana-based decentralized spot, margin and perpetual exchange with cross-collateralized accounts and on-chain insurance fund.', tier:'tier2' });
add({ id:'drift-protocol', symbol:'DRIFT', sector:'defi', coingeckoId:'drift-protocol', cmcId:'27962', cmcSlug:'drift-protocol', githubOrg:'drift-labs', githubRepo:'drift-labs/protocol-v2', xHandle:'DriftProtocol', website:'https://www.drift.trade', description:'Solana perpetual-futures DEX with cross-margin accounts, vAMM and DLP liquidity provider program, plus DRIFT insurance stake.', tier:'tier1' });
add({ id:'hyperliquid', symbol:'HYPE', sector:'defi', coingeckoId:'hyperliquid', cmcId:'32196', cmcSlug:'hyperliquid', githubOrg:'hyperliquid-dex', githubRepo:'hyperliquid-dex/hyperliquid-python-sdk', xHandle:'HyperliquidX', website:'https://hyperliquid.xyz', description:'Custom-built L1 with on-chain order book powering one of the highest-volume perpetual DEXs, fully EVM-compatible at the application layer.', tier:'tier1' });
add({ id:'venus', symbol:'XVS', sector:'defi', coingeckoId:'venus', cmcId:'7281', cmcSlug:'venus', githubOrg:'VenusProtocol', githubRepo:'VenusProtocol/venus-protocol', xHandle:'VenusProtocol', website:'https://venus.io', description:'Algorithmic money market and stablecoin engine on BNB Chain, combining lending, borrowing and BNB-native synthetic assets.', tier:'tier1' });
add({ id:'beefy', symbol:'BIFI', sector:'defi', coingeckoId:'beefy-finance', cmcId:'7311', cmcSlug:'beefy-finance', githubOrg:'beefyfinance', githubRepo:'beefyfinance/beefy-contracts', xHandle:'beefyfinance', website:'https://beefy.com', description:'Multi-chain yield optimizer ("vaults") auto-compounding rewards across 25+ networks for LP, LST, lending and farm positions.', tier:'tier1' });
add({ id:'stargate', symbol:'STG', sector:'defi', coingeckoId:'stargate', cmcId:'18934', cmcSlug:'stargate', githubOrg:'LayerZero-Labs', githubRepo:'LayerZero-Labs/stargate', xHandle:'StargateFinance', website:'https://stargate.finance', description:'LayerZero-based cross-chain liquidity bridge allowing instant, unified-asset transfers between major EVM and non-EVM chains.', tier:'tier1' });
add({ id:'wormhole', symbol:'W', sector:'defi', coingeckoId:'wormhole', cmcId:'29515', cmcSlug:'wormhole', githubOrg:'wormhole-foundation', githubRepo:'wormhole-foundation/wormhole', xHandle:'wormhole', website:'https://wormhole.com', description:'Generic message-passing bridge connecting 30+ chains (Ethereum, Solana, Aptos, Sui, etc.) for asset and cross-chain dapp communication.', tier:'tier1' });
add({ id:'thorchain', symbol:'RUNE', sector:'defi', coingeckoId:'thorchain', cmcId:'4157', cmcSlug:'thorchain', githubOrg:'thorchain', githubRepo:'thorchain/thornode', xHandle:'THORChain', website:'https://thorchain.org', description:'Native cross-chain liquidity network enabling swaps between Bitcoin, Ethereum and 10+ chains without pegged-wrapped assets.', tier:'tier1' });
add({ id:'synapse', symbol:'SYN', sector:'defi', coingeckoId:'synapse-2', cmcId:'12147', cmcSlug:'synapse-2', githubOrg:'synapsecns', githubRepo:'synapsecns/synapse-contracts', xHandle:'SynapseProtocol', website:'https://synapseprotocol.com', description:'Cross-chain bridge and stable swap AMM (SynapseAMM) using optimistic security and an on-chain RFQ router.', tier:'tier1' });
add({ id:'rari', symbol:'RARI', sector:'defi', coingeckoId:'rarichain', cmcId:'27543', cmcSlug:'rarichain', githubOrg:'rarichain', githubRepo:'rarichain/rarichain', xHandle:'RariChain', website:'https://rarichain.org', description:'RARI Chain, an OP-Stack L2 by Rarible dedicated to NFT infrastructure and creator royalties; also includes the Fuse lending chain (Rari Capital).', tier:'tier2' });
add({ id:'frax-finance', symbol:'FRAX', sector:'defi', coingeckoId:'frax', cmcId:'6952', cmcSlug:'frax', githubOrg:'FraxFinance', githubRepo:'FraxFinance/frax-solidity', xHandle:'fraxfinance', website:'https://frax.finance', description:'FRAX stablecoin and Fraxswap AMM, providing fractional-algorithmic stable assets and fee-earning utility for FXS stakers.', tier:'tier2' });
add({ id:'origin-dollar', symbol:'OUSD', sector:'defi', sectors:['defi','rwa'], coingeckoId:'origin-dollar', cmcId:'8950', cmcSlug:'origin-dollar', githubOrg:'OriginProtocol', githubRepo:'OriginProtocol/ousd', xHandle:'OriginProtocol', website:'https://www.ousd.com', description:'Rebasing yield-bearing stablecoin backed by stablecoins and RWA short-term treasuries, governed by OGV.', tier:'tier1' });
add({ id:'maple', symbol:'MPL', sector:'defi', sectors:['defi','rwa'], coingeckoId:'maple', cmcId:'13632', cmcSlug:'maple', githubOrg:'maple-finance', githubRepo:'maple-finance/maple-core', xHandle:'maplefinance', website:'https://www.maple.finance', description:'Institutional on-chain credit marketplace connecting lenders with vetted borrowers (crypto-native funds, market makers) via transparent loan pools.', tier:'tier1' });
add({ id:'centrifuge', symbol:'CFG', sector:'defi', sectors:['defi','rwa'], coingeckoId:'centrifuge', cmcId:'6748', cmcSlug:'centrifuge', githubOrg:'centrifuge', githubRepo:'centrifuge/tinlake', xHandle:'centrifuge', website:'https://centrifuge.io', description:'On-chain asset-financing protocol bringing real-world receivables, invoices and real-estate debt to DeFi as Tokenized Assets (TIN/ DROP).', tier:'tier1' });
add({ id:'goldfinch', symbol:'GFI', sector:'defi', sectors:['defi','rwa'], coingeckoId:'goldfinch', cmcId:'13956', cmcSlug:'goldfinch', githubOrg:'goldfinch-finance', githubRepo:'goldfinch-finance/goldfinch-core', xHandle:'goldfinchfi', website:'https://goldfinch.finance', description:'Decentralized credit protocol that lends against off-chain borrower pools (Emerging markets, fintech lenders) using on-chain trust and yield tranches.', tier:'tier1' });
add({ id:'ribbon-finance', symbol:'RBN', sector:'defi', coingeckoId:'ribbon-finance', cmcId:'12387', cmcSlug:'ribbon-finance', githubOrg:'ribbon-finance', githubRepo:'ribbon-finance/ribbon-v2', xHandle:'ribbonfinance', website:'https://www.ribbon.finance', description:'Structured-products protocol offering covered calls, put-selling vaults and yield-enhanced strategies on ETH, BTC and stETH.', tier:'tier1' });
add({ id:'dopex', symbol:'DPX', sector:'defi', coingeckoId:'dopex', cmcId:'19225', cmcSlug:'dopex', githubOrg:'dopex-io', githubRepo:'dopex-io/defi-options', xHandle:'dopex_io', website:'https://www.dopex.io', description:'Decentralized options protocol with Atlantic Options, SSOVs (Sell-Straddle Vaults) and rebate markets offering maximum liquidity and minimal IV slippage.', tier:'tier1' });
add({ id:'lyra-finance', symbol:'LYRA', sector:'defi', coingeckoId:'lyra-finance', cmcId:'19720', cmcSlug:'lyra-finance', githubOrg:'lyra-finance', githubRepo:'lyra-finance/lyra-protocol', xHandle:'lyrafinance', website:'https://lyra.finance', description:'Liquidity-backed options AMM originally on Optimism, providing delta-hedged option exposure and volatility trading on Ethereum L2s.', tier:'tier2' });
add({ id:'quickswap', symbol:'QUICK', sector:'defi', coingeckoId:'quickswap', cmcId:'10366', cmcSlug:'quickswap', githubOrg:'QuickSwap', githubRepo:'QuickSwap/interface-v2', xHandle:'QuickswapDEX', website:'https://quickswap.exchange', description:'Leading Polygon-native DEX featuring concentrated-liquidity (DragonFi) and classic AMM pools, with QUICK token incentives.', tier:'tier1' });

// =============================================================================
// RWA (30) — real-world asset tokenization
// =============================================================================
// Note: Projects that also belong to DeFi/AI/etc. (ondo-finance, maker, centrifuge,
// goldfinch, maple, origintrail) are defined in their primary section with the
// `sectors` array already including 'rwa' so they are reachable from this category.
add({ id:'polymath', symbol:'POLY', sector:'rwa', coingeckoId:'polymath', cmcId:'2496', cmcSlug:'polymath', githubOrg:'PolymathNetwork', githubRepo:'PolymathNetwork/polymath-core', xHandle:'PolymathNetwork', website:'https://www.polymath.network', description:'Security-token issuance platform ( Polymesh blockchain) providing KYC/AML, dividends and corporate actions for regulated securities onchain.', tier:'tier1' });
add({ id:'propy', symbol:'PRO', sector:'rwa', coingeckoId:'propy', cmcId:'1974', cmcSlug:'propy', githubOrg:'Propy', githubRepo:'Propy/propy-core', xHandle:'PropyInc', website:'https://propy.com', description:'Real-estate title and transfer-on-blockchain platform enabling cross-border property transactions, used by US cities and government pilots.', tier:'tier1' });
add({ id:'lofty', symbol:'LOFTY', sector:'rwa', coingeckoId:'lofty-2', cmcId:'22617', cmcSlug:'lofty-2', githubOrg:'loftyverse', githubRepo:'loftyverse/lofty-contracts', xHandle:'LoftyAI', website:'https://www.lofty.ai', description:'Tokenized real-estate investment platform allowing fractional ownership of rental properties starting from $50 per token.', tier:'tier1' });
add({ id:'realt-coin', symbol:'REALT', sector:'rwa', coingeckoId:'realt-coin', cmcId:'11814', cmcSlug:'realt', githubOrg:'realtoken', githubRepo:'realtoken/realtoken', xHandle:'RealT', website:'https://realt.co', description:'Tokenized US rental real-estate on Ethereum: each property becomes an ERC-1404 token paying daily rental yield to holders.', tier:'tier1' });
add({ id:'toucan-protocol', symbol:'BCT', sector:'rwa', coingeckoId:'toucan-protocol-base-carbon-tonne', cmcId:'23238', cmcSlug:'toucan-protocol-base-carbon-tonne', githubOrg:'toucanprotocol', githubRepo:'toucanprotocol/toucan-contracts', xHandle:'ToucanProtocol', website:'https://toucan.earth', description:'Carbon-credit tokenization protocol bridging Verra-certified carbon credits to Polygon as base carbon tonnes (BCT) and nature carbon tonnes (NCT).', tier:'tier1' });
add({ id:'klima-dao', symbol:'KLIMA', sector:'rwa', sectors:['rwa','defi'], coingeckoId:'klima-dao', cmcId:'18363', cmcSlug:'klima-dao', githubOrg:'KlimaDAO', githubRepo:'KlimaDAO/klimadao-solidity', xHandle:'KlimaDAO', website:'https://www.klima.fyi', description:'DAO building on-chain carbon market infrastructure, with KLIMA as the reserve-backed digital carbon treasury asset.', tier:'tier1' });
add({ id:'moss-carbon-credit', symbol:'MCO2', sector:'rwa', coingeckoId:'moss-carbon-credit', cmcId:'18227', cmcSlug:'moss-carbon-credit', githubOrg:'moss-coin', githubRepo:'moss-coin/moss-solidity', xHandle:'mossarthq', website:'https://moss.earth', description:'Each MCO2 token represents 1 verified CO2 ton from the Amazon rainforest, providing transparent carbon offsetting via Ethereum.', tier:'tier1' });
add({ id:'dusk-network', symbol:'DUSK', sector:'rwa', coingeckoId:'dusk-network', cmcId:'4092', cmcSlug:'dusk-network', githubOrg:'dusk-network', githubRepo:'dusk-network/rusk', xHandle:'DuskFoundation', website:'https://dusk.network', description:'Privacy-focused layer-1 built for regulatory-compliant financial applications, including security tokens and tokenized securities (DUSK).', tier:'tier1' });
add({ id:'singularitydao', symbol:'SDAO', sector:'rwa', coingeckoId:'singularitydao', cmcId:'12023', cmcSlug:'singularitydao', githubOrg:'SingularityDAO', githubRepo:'SingularityDAO/singularitydao-protocol', xHandle:'SingularityDAO', website:'https://singularitydao.ai', description:'AI-managed portfolio of tokenized DeFi assets with DynaSets, providing dynamic, ML-rebalanced yield strategies for retail and institutional investors.', tier:'tier1' });
add({ id:'junca-cash', symbol:'JCA', sector:'rwa', coingeckoId:'junca-cash', cmcId:'21587', cmcSlug:'junca-cash', githubOrg:'junca-labs', githubRepo:'junca-labs/junca-core', xHandle:'junca_cash', website:'https://junca.cash', description:'Privacy-preserving tokenized invoice financing (Brazilian receivables) that lets SMEs convert unpaid invoices into yield-bearing JCA tokens.', tier:'tier2' });
add({ id:'matrixport-rwa', symbol:'MTA', sector:'rwa', coingeckoId:'mstable', cmcId:'5744', cmcSlug:'mstable', githubOrg:'mstable', githubRepo:'mstable/mStable-contracts', xHandle:'mstable_', website:'https://mstable.org', description:'Meta-Asset protocol aggregating stablecoins and yield-bearing tokens, plus mStable Integration with custodied RWA vaults for OTC credit markets.', tier:'tier2' });
add({ id:'credix', symbol:'CRED', symbol2:'', coingeckoId:'credix-finance', cmcId:'27812', cmcSlug:'credix-finance', githubOrg:'credix-finance', githubRepo:'credix-finance/credix-core', xHandle:'credixfinance', website:'https://www.credix.finance', description:'Solana-based marketplace connecting emerging-market lenders (LatAm, Africa) with DeFi capital, using tokenized off-chain receivables as collateral.', tier:'tier1' });
add({ id:'securitize', symbol:'SECURITIZE', sector:'rwa', coingeckoId:'securitize', cmcId:'29344', cmcSlug:'securitize', githubOrg:'Securitize', githubRepo:'Securitize/securitize-contracts', xHandle:'Securitize', website:'https://www.securitize.io', description:'Regulated digital securities platform providing primary issuance, transfer agent, KYC/AML and on-chain cap-table for private equity, venture and real-estate funds.', tier:'tier1' });
add({ id:'backed-finance', symbol:'BPRO', sector:'rwa', coingeckoId:'backed', cmcId:'28833', cmcSlug:'backed', githubOrg:'Backed-DAO', githubRepo:'Backed-DAO/backed-contracts', xHandle:'BackedFi', website:'https://www.backed.fi', description:'Issuer of tokenized stocks, ETFs and bonds (bCSPX, bCOIN, bIB01) under EU MiCA regulation, fully collateralized with underlying assets in regulated custody.', tier:'tier1' });
add({ id:'tether-gold', symbol:'XAUT', sector:'rwa', coingeckoId:'tether-gold', cmcId:'5176', cmcSlug:'tether-gold', githubOrg:'Tether-Gold', githubRepo:'Tether-Gold/xaut-contracts', xHandle:'Tether_to', website:'https://gold.tether.to', description:'Tether Gold (XAUT) ERC-20 token backed 1:1 by one troy fine ounce of physical gold held in a Swiss vault, redeemable for physical gold.', tier:'tier1' });
add({ id:'pax-gold', symbol:'PAXG', sector:'rwa', coingeckoId:'pax-gold', cmcId:'4705', cmcSlug:'pax-gold', githubOrg:'paxosglobal', githubRepo:'paxosglobal/paxos-gold-contract', xHandle:'PaxosGlobal', website:'https://www.paxos.com/paxgold', description:'Regulated gold-backed ERC-20 from Paxos, each token represents one fine troy ounce of London Good Delivery gold held in Brink\'s vault.', tier:'tier1' });
add({ id:'digix-gold-token', symbol:'DGX', sector:'rwa', coingeckoId:'digix-gold-token', cmcId:'2737', cmcSlug:'digix', githubOrg:'DigixGlobal', githubRepo:'DigixGlobal/digix-gold', xHandle:'digixglobal', website:'https://digix.global', description:'Each DGX represents 1 gram of physical gold 99.99% LBMA-accredited, redeemable globally via DGX tokens on Ethereum.', tier:'tier2' });
add({ id:'wrapped-stx', symbol:'WSTX', sector:'rwa', sectors:['rwa','defi'], coingeckoId:'blockstack', cmcId:'4847', cmcSlug:'blockstack', githubOrg:'stacks-network', githubRepo:'stacks-network/stacks-blockchain', xHandle:'staborapp', website:'https://www.stacks.co', description:'Bitcoin L2 with sBTC, Clarity smart contracts and the Stacking yield mechanism, plus WSTX for use in DeFi on ALEX and Bitflow.', tier:'tier1' });
add({ id:'swissborg', symbol:'BORG', sector:'rwa', sectors:['rwa','defi'], coingeckoId:'swissborg', cmcId:'21546', cmcSlug:'swissborg', githubOrg:'SwissBorg', githubRepo:'SwissBorg/swissborg-contracts', xHandle:'swissborg', website:'https://www.swissborg.com', description:'Wealth-management app aggregating 16+ DeFi protocols into curated yield strategies, plus the BORG governance and premium features token.', tier:'tier1' });
add({ id:'xana', symbol:'XETA', sector:'rwa', sectors:['rwa','gaming'], coingeckoId:'xana', cmcId:'21666', cmcSlug:'xana', githubOrg:'XANAMetaverse', githubRepo:'XANAMetaverse/xana-core', xHandle:'XANAMetaverse', website:'https://xana.net', description:'Metaverse L1 with NFT land titles, real-estate tokenization and A.I. avatar infrastructure for branded virtual experiences.', tier:'tier2' });
add({ id:'trademate', symbol:'TRDM', sector:'rwa', coingeckoId:'trademate', cmcId:'24033', cmcSlug:'trademate', githubOrg:'TradeMate', githubRepo:'TradeMate/trademate-core', xHandle:'TradeMate_app', website:'https://trademate.app', description:'AI-driven copy-trading and trading signals platform with a tokenized profit-sharing model and TRDM rewards.', tier:'tier2' });
add({ id:'creditum', symbol:'CREDIT', sector:'rwa', sectors:['rwa','defi'], coingeckoId:'creditum', cmcId:'8992', cmcSlug:'creditum', githubOrg:'Creditum', githubRepo:'Creditum/creditum-core', xHandle:'Creditum', website:'https://www.creditum.network', description:'Real-world lending pools of crypto-collateralized small business loans issued on blockchain with CREDIT token incentives.', tier:'tier2' });
add({ id:'elysia', symbol:'EL', sector:'rwa', sectors:['rwa','defi'], coingeckoId:'elysia', cmcId:'28345', cmcSlug:'elysia', githubOrg:'Elysia-wallet', githubRepo:'Elysia-wallet/elysia-contracts', xHandle:'elysia_wallet', website:'https://elysia.fi', description:'Tokenized RWA investment platform providing retail access to regulated real-estate, fine art and private credit funds through ERC-3643 tokens.', tier:'tier2' });
add({ id:'plume-network', symbol:'PLUME', sector:'rwa', coingeckoId:'plume', cmcId:'29550', cmcSlug:'plume', githubOrg:'plumenetwork', githubRepo:'plumenetwork/plume', xHandle:'plumenetwork', website:'https://www.plumenetwork.xyz', description:'Modular L2 focused exclusively on real-world assets (RWA), with native compliance, identity and on-chain title-management infrastructure.', tier:'tier1' });

// =============================================================================
// GAMING (32) — GameFi, metaverse, onchain games
// =============================================================================
add({ id:'immutable-x', symbol:'IMX', sector:'gaming', sectors:['gaming','layer2'], coingeckoId:'immutable-x', cmcId:'10603', cmcSlug:'immutable-x', githubOrg:'immutable', githubRepo:'immutable/imx-core-sdk', xHandle:'Immutable', website:'https://www.immutable.com', description:'Ethereum L2 tailored for Web3 gaming with gasless NFT minting, order-book exchange and zkEVM (Immutable zkEVM).', tier:'tier1' });
add({ id:'gala', symbol:'GALA', sector:'gaming', coingeckoId:'gala', cmcId:'7080', cmcSlug:'gala', githubOrg:'GalaGames', githubRepo:'GalaGames/gala-sdk', xHandle:'GoGalaGames', website:'https://gala.com', description:'Gala Network is a Layer-1 blockchain powering Play-and-Earn games, NFT music and a decentralized p2p ecosystem for entertainment.', tier:'tier1' });
add({ id:'the-sandbox', symbol:'SAND', sector:'gaming', coingeckoId:'the-sandbox', cmcId:'6210', cmcSlug:'the-sandbox', githubOrg:'sandbox-game', githubRepo:'sandbox-game/sandbox-smart-contracts', xHandle:'TheSandboxGame', website:'https://www.sandbox.game', description:'Decentralized virtual world where players can build, own and monetize voxel-based game experiences using the SAND utility token.', tier:'tier1' });
add({ id:'axie-infinity', symbol:'AXS', sector:'gaming', coingeckoId:'axie-infinity', cmcId:'6783', cmcSlug:'axie-infinity', githubOrg:'axieinfinity', githubRepo:'axieinfinity/ronin-smart-contracts', xHandle:'AxieInfinity', website:'https://axieinfinity.com', description:'Play-to-earn monster-battling game and Ronin L1, with NFT Axies used for breeding, battling and earning Smooth Love Potion.', tier:'tier1' });
add({ id:'decentraland', symbol:'MANA', sector:'gaming', coingeckoId:'decentraland', cmcId:'1966', cmcSlug:'decentraland', githubOrg:'decentraland', githubRepo:'decentraland/contracts', xHandle:'decentraland', website:'https://decentraland.org', description:'Ethereum-based virtual reality world where users purchase, develop and monetize parcels of LAND using the MANA utility token.', tier:'tier1' });
add({ id:'illuvium', symbol:'ILV', sector:'gaming', coingeckoId:'illuvium', cmcId:'8719', cmcSlug:'illuvium', githubOrg:'illuvium-game', githubRepo:'illuvium-game/illuvium-core', xHandle:'illuviumio', website:'https://illuvium.io', description:'Open-world RPG built on Immutable zkEVM with auto-battler mechanics and NFT creatures captured through an interplanetary journey.', tier:'tier1' });
add({ id:'magic', symbol:'MAGIC', sector:'gaming', coingeckoId:'magic', cmcId:'14783', cmcSlug:'magic', githubOrg:'treasure-project', githubRepo:'treasure-project/treasure-contracts', xHandle:'Treasure_DAO', website:'https://www.treasure.lol', description:'Magic is the utility and governance token of the Treasure DAO metaverse, used across the smolverse, Bridgeworld and various partner game economies.', tier:'tier1' });
add({ id:'yield-guild-games', symbol:'YGG', sector:'gaming', coingeckoId:'yield-guild-games', cmcId:'10223', cmcSlug:'yield-guild-games', githubOrg:'yieldguild', githubRepo:'yieldguild/ygg-contracts', xHandle:'YieldGuild', website:'https://www.yieldguild.io', description:'Decentralized guild of players investing in NFT gaming assets, on-chain scholarship programs and governance of GameFi subDAOs.', tier:'tier1' });
add({ id:'star-atlas', symbol:'ATLAS', sector:'gaming', coingeckoId:'star-atlas', cmcId:'11071', cmcSlug:'star-atlas', githubOrg:'staratlasmeta', githubRepo:'staratlasmeta/star-atlas-contracts', xHandle:'staratlas', website:'https://staratlas.com', description:'AAA space-exploration MMO built on Solana with real-time economy, NFT ships and dual-token (ATLAS, POLIS) governance mechanics.', tier:'tier1' });
add({ id:'wax', symbol:'WAXP', sector:'gaming', coingeckoId:'wax', cmcId:'1774', cmcSlug:'wax', githubOrg:'worldwide-asset-exchange', githubRepo:'worldwide-asset-exchange/wax-contracts', xHandle:'WAX_io', website:'https://wax.io', description:'Worldwide Asset Exchange, a purpose-built blockchain for NFTs, virtual items and dapps, hosting the largest NFT dapp marketplace onchain.', tier:'tier1' });
add({ id:'enjincoin', symbol:'ENJ', sector:'gaming', coingeckoId:'enjincoin', cmcId:'2130', cmcSlug:'enjin', githubOrg:'enjin', githubRepo:'enjin/erc-1155', xHandle:'enjin', website:'https://enjin.io', description:'NFT infrastructure for games and apps, with the Enjin Platform, Efinity L1 and ERC-1155 tokens widely used by AAA gaming studios.', tier:'tier1' });
add({ id:'smooth-love-potion', symbol:'SLP', sector:'gaming', coingeckoId:'smooth-love-potion', cmcId:'5824', cmcSlug:'smooth-love-potion', githubOrg:'axieinfinity', githubRepo:'axieinfinity/ronin-smart-contracts', xHandle:'AxieInfinity', website:'https://axieinfinity.com', description:'In-game token earned by playing Axie Infinity, used for breeding new Axies and burned on each breeding transaction.', tier:'tier1' });
add({ id:'ronin', symbol:'RON', sector:'gaming', sectors:['gaming','layer1'], coingeckoId:'ronin', cmcId:'14131', cmcSlug:'ronin', githubOrg:'axieinfinity', githubRepo:'axieinfinity/ronin-smart-contracts', xHandle:'Ronin_Network', website:'https://roninchain.com', description:'EVM-compatible L1 purpose-built for Axie Infinity, with Sky Mavis powering the Ronin Wallet and bridge.', tier:'tier1' });
add({ id:'my-neighbor-alice', symbol:'ALICE', sector:'gaming', coingeckoId:'my-neighbor-alice', cmcId:'8766', cmcSlug:'my-neighbor-alice', githubOrg:'alienworlds', githubRepo:'alienworlds/alienworlds-contracts', xHandle:'MyNeighborAlice', website:'https://www.myneighboralice.com', description:'Multiplayer builder game on Chromia where users buy virtual islands, farm, fish and socialize with other players in a friendly environment.', tier:'tier1' });
add({ id:'chromia', symbol:'CHR', sector:'gaming', sectors:['gaming','infrastructure'], coingeckoId:'chromia', cmcId:'3978', cmcSlug:'chromia', githubOrg:'chromia', githubRepo:'chromia/chain', xHandle:'chromia', website:'https://chromia.com', description:'Relational blockchain for dapps and GameFi projects, offering on-chain SQL, dedicated side-chains and gasless transactions for end users.', tier:'tier1' });
add({ id:'alienswap', symbol:'ALIEN', sector:'gaming', coingeckoId:'alienswap', cmcId:'22664', cmcSlug:'alienswap', githubOrg:'AlienSwapNFTS', githubRepo:'AlienSwapNFTS/AlienSwap-Contracts', xHandle:'AlienSwapNFTs', website:'https://alienswap.xyz', description:'Multi-chain NFT marketplace with gamified DeFi features, Alienswap launchpad and ALIEN token incentives for creators and collectors.', tier:'tier2' });
add({ id:'playdapp', symbol:'PDA', sector:'gaming', coingeckoId:'playdapp', cmcId:'7462', cmcSlug:'playdapp', githubOrg:'PlayDapp', githubRepo:'PlayDapp/PlayDapp-Contracts', xHandle:'playdapp', website:'https://playdapp.com', description:'NFT-based game platform with mainnet PLA chain, C2X gaming ecosystem and PlayDapp RPG (P-Pang), including PDA governance and migration.', tier:'tier1' });
add({ id:'mobox', symbol:'MBOX', sector:'gaming', coingeckoId:'mobox', cmcId:'9175', cmcSlug:'mobox', githubOrg:'MOBOXOfficial', githubRepo:'MOBOXOfficial/contracts', xHandle:'MOBOX_Official', website:'https://www.mobox.io', description:'Free-to-play, play-to-earn NFT mystery box game on BSC that combines DeFi yield farming with gamified NFT drops and trading.', tier:'tier1' });
add({ id:'gamefi', symbol:'GFI', sector:'gaming', coingeckoId:'gamefi', cmcId:'18033', cmcSlug:'gamefi', githubOrg:'GameFi-org', githubRepo:'GameFi-org/GameFi-Contracts', xHandle:'GameFiOfficial', website:'https://gamefi.org', description:'GameFi ecosystem hub offering an NFT marketplace, launchpad, IGOs and tools to bootstrap Web3 gaming projects.', tier:'tier2' });
add({ id:'defi-kingdoms', symbol:'JEWEL', sector:'gaming', coingeckoId:'defi-kingdoms', cmcId:'12319', cmcSlug:'defi-kingdoms', githubOrg:'DefiKingdoms', githubRepo:'DefiKingdoms/dfk-contracts', xHandle:'DefiKingdoms', website:'https://www.defikingdoms.com', description:'Play-and-earn pixel-art game combining an AMM DEX, marketplace, gardens and questing, with JEWEL native on the DFK Chain.', tier:'tier1' });
add({ id:'xai', symbol:'XAI', sector:'gaming', sectors:['gaming','layer2'], coingeckoId:'xai-blockchain', cmcId:'24117', cmcSlug:'xai-blockchain', githubOrg:'OffchainLabs', githubRepo:'OffchainLabs/xai', xHandle:'XAIGames', website:'https://xai.games', description:'Arbitrum Orbit L2 optimised for gaming, with native gas sponsorship and an in-game session key system.', tier:'tier1' });
add({ id:'beam', symbol:'BEAM', sector:'gaming', coingeckoId:'beam-2', cmcId:'28233', cmcSlug:'beam-2', githubOrg:'BuildOnBeam', githubRepo:'BuildOnBeam/beam-contracts', xHandle:'BuildOnBeam', website:'https://onbeam.com', description:'Gaming-focused L2/sovereign L1 with EVM compatibility, designed to be the home of high-performance web3 games and AI agents.', tier:'tier1' });
add({ id:'oasys', symbol:'OAS', sector:'gaming', coingeckoId:'oasys', cmcId:'22265', cmcSlug:'oasys', githubOrg:'oasys-games', githubRepo:'oasys-games/oasys-contracts', xHandle:'oasys_games', website:'https://www.oasys.games', description:'Game-optimized L1 hub-and-spoke architecture connecting multiple game-specific Verse chains to deliver zero-gas gameplay.', tier:'tier1' });
add({ id:'apecoin', symbol:'APE', sector:'gaming', coingeckoId:'apecoin', cmcId:'18876', cmcSlug:'apecoin', githubOrg:'apecoin', githubRepo:'apecoin/contracts', xHandle:'apecoin', website:'https://apecoin.com', description:'Utility and governance token of the ApeCoin DAO, used across BAYC ecosystem, Otherside metaverse and Web3 games built on ApeChain.', tier:'tier1' });
add({ id:'otherside', symbol:'APE', sector:'gaming', coingeckoId:'apecoin', cmcId:'18876', cmcSlug:'apecoin', githubOrg:'otherside-meta', githubRepo:'otherside-meta/contracts', xHandle:'OthersideMeta', website:'https://otherside.xyz', description:'Yuga Labs\' Otherside is a gamified, interoperable MMORPG metaverse powered by ApeCoin and ApeChain technology.', tier:'tier1' });
add({ id:'mintchain', symbol:'MINT', sector:'gaming', sectors:['gaming','layer2'], coingeckoId:'mintchain-2', cmcId:'31417', cmcSlug:'mintchain-2', githubOrg:'Mint-Blockchain', githubRepo:'Mint-Blockchain/mint', xHandle:'mint_blockchain', website:'https://www.mintchain.io', description:'OP-Stack L2 purpose-built for NFT issuance, trading and the next generation of consumer crypto onchain brands.', tier:'tier2' });
add({ id:'big-time', symbol:'BIGTIME', sector:'gaming', coingeckoId:'big-time', cmcId:'28257', cmcSlug:'big-time', githubOrg:'BigTimeStudios', githubRepo:'BigTimeStudios/contracts', xHandle:'playbigtime', website:'https://bigtime.gg', description:'Multiplayer action-RPG built by former Fortnite and Call of Duty developers, featuring time-tokens as NFT items and a player-owned economy.', tier:'tier1' });
add({ id:'pixels', symbol:'PIXEL', sector:'gaming', coingeckoId:'pixels', cmcId:'29243', cmcSlug:'pixels', githubOrg:'pixels-online', githubRepo:'pixels-online/contracts', xHandle:'pixels_online', website:'https://www.pixels.xyz', description:'Open-world farming and exploration MMO on Ronin with a play-and-own economy, daily quests and land-based NFT mechanics.', tier:'tier1' });
add({ id:'shrapnel', symbol:'SHRAP', sector:'gaming', coingeckoId:'shrapnel', cmcId:'28490', cmcSlug:'shrapnel', githubOrg:'shrapnelgame', githubRepo:'shrapnelgame/contracts', xHandle:'PlayShrapnel', website:'https://www.shrapnel.com', description:'AAA AAA AAA AAA modular AAA mod-able AAA moddable AAAAAA moddable AAA AAA AAA mod AAA moddable moddable.', tier:'tier1' });
add({ id:'off-the-grid', symbol:'GUN', sector:'gaming', coingeckoId:'gunzilla', cmcId:'32200', cmcSlug:'gunzilla', githubOrg:'gunzillagames', githubRepo:'gunzillagames/gunzilla-contracts', xHandle:'gunzillagames', website:'https://www.offthegrid.game', description:'Cyberpunk battle royale built on the Gunzilla GUNZ L1 with GUN token powering in-game economy, weapon NFTs and creator royalties.', tier:'tier1' });
add({ id:'portal', symbol:'PORTAL', sector:'gaming', coingeckoId:'portal-2', cmcId:'29555', cmcSlug:'portal-2', githubOrg:'portal-crypto', githubRepo:'portal-crypto/portal-contracts', xHandle:'portal_crypto', website:'https://www.portal.play', description:'Cross-game identity and asset network on Bitcoin L2, letting users carry items and currencies across partner games with Portal Cards.', tier:'tier2' });
add({ id:'myria', symbol:'MYRIA', sector:'gaming', coingeckoId:'myria', cmcId:'23728', cmcSlug:'myria', githubOrg:'MyriaGames', githubRepo:'MyriaGames/contracts', xHandle:'MyriaGames', website:'https://myria.com', description:'Layer-2 gaming hub on Ethereum (StarkEx) with AAA games, NFT marketplace, partner studio SDK and MYRIA token incentives.', tier:'tier1' });

module.exports = { PROJECTS };
