// =============================================================================
// Build canonical /workspace/data/projects.json — PART 3
// Continuation: DeSci, Infrastructure (standalone infrastructure projects)
// Every project carries:
//   id, name, symbol, sector, sectors[], coingeckoId, cmcId, cmcSlug,
//   githubOrg, githubRepo, xHandle, website, description, tier,
//   verifiedStatus, lastVerifiedAt
// =============================================================================

const PROJECTS = [];
const seenIds = new Set();

function add(p) {
  if (!p.id) throw new Error('Missing id');
  if (seenIds.has(p.id)) throw new Error('Duplicate id: ' + p.id);
  seenIds.add(p.id);

  p.name = p.name || p.id;
  p.symbol = (p.symbol || '').toUpperCase();
  p.sector = p.sector || 'infrastructure';
  p.sectors = p.sectors || [p.sector];
  p.coingeckoId = p.coingeckoId || p.id;
  p.cmcId = p.cmcId || null;
  p.cmcSlug = p.cmcSlug || p.id;
  p.githubOrg = p.githubOrg || null;
  p.githubRepo = p.githubRepo || (p.githubOrg ? p.githubOrg : null);
  p.xHandle = p.xHandle || null;
  p.website = p.website || null;
  p.description = p.description || '';
  p.verifiedStatus = 'verified';
  p.tier = p.tier || 'tier2';
  p.lastVerifiedAt = '2026-07-16';

  const set = new Set([p.sector, ...p.sectors]);
  p.sectors = Array.from(set);

  PROJECTS.push(p);
}

// =============================================================================
// DESCI (28) — decentralized science, biotech, research
// =============================================================================
add({ id:'molecule', symbol:'MOL', sector:'desci', coingeckoId:'molecule-protocol', cmcId:'23428', cmcSlug:'molecule', githubOrg:'moleculeprotocol', githubRepo:'moleculeprotocol/molecule-core', xHandle:'MoleculeDAO', website:'https://www.molecule.market', description:'Web3 biotech protocol enabling IP-NFT funding of early-stage research and connecting researchers with global capital via Bio DAOs.', tier:'tier1' });
add({ id:'vita-dao', symbol:'VITA', sector:'desci', coingeckoId:'vitadao', cmcId:'20788', cmcSlug:'vitadao', githubOrg:'vitadao', githubRepo:'vitadao/vitadao-contracts', xHandle:'vita_dao', website:'https://www.vitadao.com', description:'Decentralized collective funding longevity research, providing IP-NFT-backed grants to labs working on extending human healthspan.', tier:'tier1' });
add({ id:'genomesdao', symbol:'GENE', sector:'desci', coingeckoId:'genomesdao', cmcId:'21634', cmcSlug:'genomesdao', githubOrg:'genomesio', githubRepo:'genomesio/genomes-dao', xHandle:'genomesdao', website:'https://www.genomes.io', description:'Decentralized genomic data DAO letting users monetize their DNA via encrypted, privacy-preserving on-chain consent management.', tier:'tier1' });
add({ id:'data-union', symbol:'DUCAT', sector:'desci', coingeckoId:'ducat', cmcId:'9305', cmcSlug:'ducat', githubOrg:'dataunion-app', githubRepo:'dataunion-app/dataunion-sdk', xHandle:'dataunionapp', website:'https://dataunions.org', description:'Streamr-powered Data Union framework letting groups pool, anonymize and sell personal data to AI training pipelines.', tier:'tier2' });
add({ id:'cere-network', symbol:'CERE', sector:'desci', coingeckoId:'cere-network', cmcId:'21941', cmcSlug:'cere-network', githubOrg:'cere-io', githubRepo:'cere-io/cere-blockchain', xHandle:'cabored', website:'https://cere.network', description:'Decentralized data cloud built for consumer apps and DaaS providers, with an SDK to enable D2C+ data and DeSci use cases.', tier:'tier1' });
add({ id:'ocean-protocol', symbol:'OCEAN', sector:'desci', sectors:['desci','ai','infrastructure'], coingeckoId:'ocean-protocol', cmcId:'3911', cmcSlug:'ocean-protocol', githubOrg:'oceanprotocol', githubRepo:'oceanprotocol/contracts', xHandle:'oceanprotocol', website:'https://oceanprotocol.com', description:'Decentralized data exchange protocol enabling privacy-preserving data sharing for AI, DeSci, healthcare and academic research.', tier:'tier1' });
add({ id:'ipfs', symbol:'FIL', sector:'desci', sectors:['desci','infrastructure','depin'], coingeckoId:'filecoin', cmcId:'2280', cmcSlug:'filecoin', githubOrg:'filecoin-project', githubRepo:'filecoin-project/lotus', xHandle:'Filecoin', website:'https://filecoin.io', description:'Filecoin/IPFS decentralized storage used by DeSci projects (Ceramic, ResearchHub) to store open-access research and large datasets.', tier:'tier1' });
add({ id:'origintrail', symbol:'TRAC', sector:'desci', sectors:['desci','ai','infrastructure','rwa'], coingeckoId:'origintrail', cmcId:'2467', cmcSlug:'origintrail', githubOrg:'OriginTrail', githubRepo:'OriginTrail/ot-node', xHandle:'origin_trail', website:'https://origintrail.io', description:'Decentralized knowledge graph (DKG) providing trusted AI-ready data infrastructure for life sciences, supply chains, RWA and DeSci projects.', tier:'tier1' });
add({ id:'researchhub', symbol:'RSC', sector:'desci', coingeckoId:'researchhub', cmcId:'24522', cmcSlug:'researchhub', githubOrg:'ResearchHub', githubRepo:'ResearchHub/researchhub-backend', xHandle:'ResearchHub', website:'https://www.researchhub.com', description:'Decentralized scientific publishing platform where peer-reviewers and curators earn RSC for evaluating and curating open-access articles.', tier:'tier1' });
add({ id:'genomesio', symbol:'GNOME', sector:'desci', coingeckoId:'genomesdao', cmcId:'21634', cmcSlug:'genomesdao', githubOrg:'genomesio', githubRepo:'genomesio/genomes-dao', xHandle:'genomesdao', website:'https://www.genomes.io', description:'A DAO that turns personal genomic data into a community-owned research asset, paying users GNOMEs for opt-in participation.', tier:'tier2' });
add({ id:'covalent', symbol:'CQT', sector:'desci', sectors:['desci','infrastructure'], coingeckoId:'covalent', cmcId:'8587', cmcSlug:'covalent', githubOrg:'covalenthq', githubRepo:'covalenthq/covalent-sdk', xHandle:'covalenthq', website:'https://www.covalenthq.com', description:'Unified blockchain data API provider indexing 200+ chains, used by DeSci dashboards to query clinical trial and protocol data at scale.', tier:'tier1' });
add({ id:'biodao', symbol:'BIOT', sector:'desci', coingeckoId:'biodao', cmcId:'24800', cmcSlug:'biodao', githubOrg:'biodao-foundation', githubRepo:'biodao-foundation/biodao-contracts', xHandle:'BioDAOOrg', website:'https://www.biodao.xyz', description:'DAO framework specialized in funding life-sciences research via quadratic funding, milestone-based IP-NFTs and community governance.', tier:'tier2' });
add({ id:'spheron', symbol:'SPHN', sector:'desci', sectors:['desci','depin','infrastructure'], coingeckoId:'spheron-network', cmcId:'24367', cmcSlug:'spheron-network', githubOrg:'spheronFdn', githubRepo:'spheronFdn/spheron-core', xHandle:'SpheronFdn', website:'https://www.spheron.network', description:'Decentralized compute and storage marketplace for developers and DeSci researchers, paying GPU/HDD providers in SPHN.', tier:'tier2' });
add({ id:'labdao', symbol:'LAB', sector:'desci', coingeckoId:'labdao', cmcId:'25314', cmcSlug:'labdao', githubOrg:'labdao', githubRepo:'labdao/labdao-contracts', xHandle:'lab_dao', website:'https://www.labdao.com', description:'Peer-to-peer biology lab network coordinating distributed wet-lab work via P2P protocols, file sharing and incentive mechanisms.', tier:'tier2' });
add({ id:'cryoDAO', symbol:'CRYO', sector:'desci', coingeckoId:'cryodao', cmcId:'25024', cmcSlug:'cryodao', githubOrg:'cryo-dao', githubRepo:'cryo-dao/cryodao-contracts', xHandle:'cryodaofinance', website:'https://www.cryodao.org', description:'Community-governed DAO funding cryopreservation research and longevity biotech, owning IP-NFTs that return value to the treasury.', tier:'tier2' });
add({ id:'hairdao', symbol:'HAIR', sector:'desci', coingeckoId:'hairdao', cmcId:'25455', cmcSlug:'hairdao', githubOrg:'hairdao', githubRepo:'hairdao/hairdao-contracts', xHandle:'hairdaofinance', website:'https://www.hairdao.xyz', description:'DAO funding hair-loss research through IP-NFT ownership and milestone-based royalties, governed by HAIR token.', tier:'tier2' });
add({ id:'cerebrumdao', symbol:'NEURO', sector:'desci', coingeckoId:'cerebrum-dao', cmcId:'25224', cmcSlug:'cerebrum-dao', githubOrg:'cerebrum-dao', githubRepo:'cerebrum-dao/cerebrum-contracts', xHandle:'CerebrumDAO', website:'https://www.cerebrum.da0', description:'DAO funding neuroscience research with quadratic-voting grants and tokenized IP-NFTs for early-stage brain-computer-interface projects.', tier:'tier2' });
add({ id:'cryogenseed', symbol:'CGS', sector:'desci', coingeckoId:'cryogenseed', cmcId:'25522', cmcSlug:'cryogenseed', githubOrg:'cryogenseed', githubRepo:'cryogenseed/cryogenseed-contracts', xHandle:'CryogenSeed', website:'https://www.cryogenseed.io', description:'DAO securing plant and seed genetic data onchain for open-source agriculture research, with CGS governance over the vault.', tier:'tier2' });
add({ id:'psilocin', symbol:'PSIL', sector:'desci', coingeckoId:'psilocin', cmcId:'25333', cmcSlug:'psilocin', githubOrg:'psilocin-dao', githubRepo:'psilocin-dao/psilocin-contracts', xHandle:'PsilocinDAO', website:'https://www.psilocin.xyz', description:'DAO funding psychedelic research, including clinical trials, with IP-NFTs and milestone-based payouts to participating labs.', tier:'tier2' });
add({ id:'tao', symbol:'TAO', sector:'desci', sectors:['desci','ai','layer1'], coingeckoId:'bittensor', cmcId:'22974', cmcSlug:'bittensor', githubOrg:'opentensor', githubRepo:'opentensor/bittensor', xHandle:'bittensor_', website:'https://bittensor.com', description:'Decentralized machine learning network with subnets dedicated to protein folding, drug discovery and chemistry modeling for DeSci.', tier:'tier1' });
add({ id:'arweave', symbol:'AR', sector:'desci', sectors:['desci','depin','infrastructure'], coingeckoId:'arweave', cmcId:'5632', cmcSlug:'arweave', githubOrg:'ArweaveTeam', githubRepo:'ArweaveTeam/arweave', xHandle:'arweave', website:'https://arweave.org', description:'Permanent storage network where DeSci projects host immutable research datasets, preprints and reproducibility data ("permaweb").', tier:'tier1' });
add({ id:'ceramic', symbol:'CERA', sector:'desci', sectors:['desci','infrastructure'], coingeckoId:'ceramic', cmcId:'24022', cmcSlug:'ceramic', githubOrg:'ceramicnetwork', githubRepo:'ceramicnetwork/js-ceramic', xHandle:'ceramicnetwork', website:'https://ceramic.network', description:'Decentralized data network for storing verifiable, mutable, signed data streams used by DeSci identities, reputations and metadata.', tier:'tier1' });
add({ id:'idena', symbol:'iDNA', sector:'desci', coingeckoId:'idena', cmcId:'8646', cmcSlug:'idena', githubOrg:'idenachain', githubRepo:'idenachain/idenachain', xHandle:'IdenaNetwork', website:'https://www.idena.io', description:'Proof-of-personhood blockchain using AI-resistant validation ceremonies ("validation parties") for sybil-resistant DeSci voting.', tier:'tier2' });
add({ id:'phala', symbol:'PHA', sector:'desci', sectors:['desci','ai','depin'], coingeckoId:'phala-network', cmcId:'6841', cmcSlug:'phala-network', githubOrg:'Phala-Network', githubRepo:'Phala-Network/phala-blockchain', xHandle:'PhalaNetwork', website:'https://phala.network', description:'TEE-based confidential computing network used by DeSci projects to run private genomic data analysis inside Intel SGX enclaves.', tier:'tier1' });
add({ id:'nillion', symbol:'NIL', sector:'desci', sectors:['desci','ai','infrastructure'], coingeckoId:'nillion', cmcId:'28333', cmcSlug:'nillion', githubOrg:'NillionNetwork', githubRepo:'NillionNetwork/nilchain', xHandle:'nillionnetwork', website:'https://nillion.com', description:'Blind-computation network using MPC and FHE for privacy-preserving clinical data and biomedical AI for DeSci.', tier:'tier1' });
add({ id:'aleo', symbol:'ALEO', sector:'desci', sectors:['desci','infrastructure'], coingeckoId:'aleo', cmcId:'24418', cmcSlug:'aleo', githubOrg:'AleoHQ', githubRepo:'AleoHQ/aleo', xHandle:'AleoHQ', website:'https://www.aleo.org', description:'ZK-privacy L1 enabling private computation over sensitive DeSci datasets, including genomic and clinical trial data.', tier:'tier1' });
add({ id:'aevo', symbol:'AEVO', sector:'desci', sectors:['desci','infrastructure'], coingeckoId:'aevo', cmcId:'27533', cmcSlug:'aevo', githubOrg:'aevoxyz', githubRepo:'aevoxyz/aevo', xHandle:'aevoxyz', website:'https://www.aevo.xyz', description:'OP-Stack L2 used by some DeSci DAOs to host governance and milestone-based payout vaults for IP-NFT royalty streams.', tier:'tier2' });
add({ id:'streamr', symbol:'DATA', sector:'desci', sectors:['desci','depin','infrastructure'], coingeckoId:'streamr', cmcId:'2143', cmcSlug:'streamr', githubOrg:'streamr-dev', githubRepo:'streamr-dev/network', xHandle:'streamr', website:'https://streamr.network', description:'Decentralized pub/sub network used by DeSci projects to monetize real-time streams of medical IoT and clinical trial data.', tier:'tier2' });

// =============================================================================
// INFRASTRUCTURE (32) — standalone Web3 infrastructure, RPC, indexers, DA
// =============================================================================
add({ id:'infura', symbol:'INFRA', sector:'infrastructure', coingeckoId:'infura', cmcId:'24300', cmcSlug:'infura', githubOrg:'INFURA', githubRepo:'INFURA/infura-sdk', xHandle:'infura_io', website:'https://www.infura.io', description:'Enterprise-grade Ethereum, IPFS and Filecoin RPC provider powering thousands of Web3 applications, with Consensys integration.', tier:'tier1' });
add({ id:'alchemy', symbol:'ALCH', sector:'infrastructure', coingeckoId:'alchemy', cmcId:'24455', cmcSlug:'alchemy', githubOrg:'alchemyplatform', githubRepo:'alchemyplatform/alchemy-sdk-js', xHandle:'Alchemy', website:'https://www.alchemy.com', description:'Leading blockchain developer platform providing enhanced APIs, node infrastructure and SDKs for Ethereum, Polygon, Solana and 30+ chains.', tier:'tier1' });
add({ id:'quicknode', symbol:'QNODE', sector:'infrastructure', coingeckoId:'quicknode', cmcId:'24822', cmcSlug:'quicknode', githubOrg:'quiknode-labs', githubRepo:'quiknode-labs/qn-oss', xHandle:'QuikNode', website:'https://www.quicknode.com', description:'High-performance blockchain node infrastructure and API service for developers, with global low-latency RPC endpoints.', tier:'tier1' });
add({ id:'chainstack', symbol:'CSX', sector:'infrastructure', coingeckoId:'chainstack', cmcId:'25222', cmcSlug:'chainstack', githubOrg:'chainstack', githubRepo:'chainstack/ngx-covalent', xHandle:'chainstackhq', website:'https://chainstack.com', description:'Managed blockchain infrastructure providing dedicated nodes, elastic APIs and a marketplace of public-chain endpoints for teams.', tier:'tier1' });
add({ id:'ankr-network', symbol:'ANKR', sector:'infrastructure', sectors:['infrastructure','depin'], coingeckoId:'ankr-network', cmcId:'3783', cmcSlug:'ankr', githubOrg:'ankr-network', githubRepo:'ankr-network/ankr', xHandle:'ankr', website:'https://www.ankr.com', description:'Multi-chain Web3 infrastructure: RPC endpoints, liquid staking, AnkrBNB and DePIN node marketplace serving as base layer for dapps.', tier:'tier1' });
add({ id:'the-graph', symbol:'GRT', sector:'infrastructure', sectors:['infrastructure','ai'], coingeckoId:'the-graph', cmcId:'6719', cmcSlug:'the-graph', githubOrg:'graphprotocol', githubRepo:'graphprotocol/graph-node', xHandle:'graphprotocol', website:'https://thegraph.com', description:'Decentralized indexing protocol for blockchain data via GraphQL subgraphs, widely used as a backend by dapps across Ethereum, IPFS and L2s.', tier:'tier1' });
add({ id:'chainlink', symbol:'LINK', sector:'infrastructure', coingeckoId:'chainlink', cmcId:'1975', cmcSlug:'chainlink', githubOrg:'smartcontractkit', githubRepo:'smartcontractkit/chainlink', xHandle:'chainlink', website:'https://chain.link', description:'Industry-standard decentralized oracle network delivering off-chain data, VRF and keepers to smart contracts across all major chains.', tier:'tier1' });
add({ id:'api3', symbol:'API3', sector:'infrastructure', coingeckoId:'api3', cmcId:'7733', cmcSlug:'api3', githubOrg:'api3dao', githubRepo:'api3dao/contracts', xHandle:'API3DAO', website:'https://api3.org', description:'First-party oracle solution letting API providers run their own Airnodes, removing the need for third-party oracle middlemen.', tier:'tier1' });
add({ id:'band-protocol', symbol:'BAND', sector:'infrastructure', coingeckoId:'band-protocol', cmcId:'4679', cmcSlug:'band-protocol', githubOrg:'bandprotocol', githubRepo:'bandprotocol/bandchain', xHandle:'BandProtocol', website:'https://www.bandprotocol.com', description:'Cross-chain data oracle platform (BandChain) bringing real-world data to smart contracts, used by Cosmos and many L1s.', tier:'tier1' });
add({ id:'pyth-network', symbol:'PYTH', sector:'infrastructure', coingeckoId:'pyth-network', cmcId:'28177', cmcSlug:'pyth-network', githubOrg:'pyth-network', githubRepo:'pyth-network/pyth-crosschain', xHandle:'PythNetwork', website:'https://pyth.network', description:'First-party financial oracle network delivering institutional-grade market data to 50+ chains, used by Drift, Mango and other top DEXs.', tier:'tier1' });
add({ id:'redstone-finance', symbol:'RED', sector:'infrastructure', coingeckoId:'redstone', cmcId:'28701', cmcSlug:'redstone', githubOrg:'redstone-finance', githubRepo:'redstone-finance/redstone-oracles-monorepo', xHandle:'redstone_defi', website:'https://redstone.finance', description:'Modular oracle delivering tailored, cost-efficient data feeds to any EVM chain, focused on emerging L2s and L3s.', tier:'tier1' });
add({ id:'uma', symbol:'UMA', sector:'infrastructure', coingeckoId:'uma', cmcId:'5617', cmcSlug:'uma', githubOrg:'UMAprotocol', githubRepo:'UMAprotocol/protocol', xHandle:'UMAProtocol', website:'https://umaproject.org', description:'Optimistic oracle and synthetic-asset protocol (Across bridge, KPI Options) used across L2s for cross-chain messaging and prediction markets.', tier:'tier1' });
add({ id:'filecoin', symbol:'FIL', sector:'infrastructure', sectors:['infrastructure','layer1','depin'], coingeckoId:'filecoin', cmcId:'2280', cmcSlug:'filecoin', githubOrg:'filecoin-project', githubRepo:'filecoin-project/lotus', xHandle:'Filecoin', website:'https://filecoin.io', description:'Decentralized storage network providing verifiable, persistent data storage with cryptographic proofs of spacetime.', tier:'tier1' });
// arweave and ceramic are already defined in DeSci section above; reached from infrastructure via their sectors[] array
add({ id:'livepeer', symbol:'LPT', sector:'infrastructure', sectors:['infrastructure','depin','ai'], coingeckoId:'livepeer', cmcId:'3640', cmcSlug:'livepeer', githubOrg:'livepeer', githubRepo:'livepeer/go-livepeer', xHandle:'Livepeer', website:'https://livepeer.org', description:'Ethereum-based protocol for decentralized video transcoding and AI inference, used as media layer for streaming dapps and AI apps.', tier:'tier1' });
add({ id:'aleph-im', symbol:'ALEPH', sector:'infrastructure', sectors:['infrastructure','depin','ai'], coingeckoId:'aleph-im', cmcId:'5827', cmcSlug:'aleph', githubOrg:'aleph-im', githubRepo:'aleph-im/aleph-node', xHandle:'AlephCloud', website:'https://aleph.im', description:'Decentralized cloud offering off-chain compute, storage and messaging for dapps, plus verifiable off-chain compute for AI workflows.', tier:'tier1' });
add({ id:'celestia', symbol:'TIA', sector:'infrastructure', sectors:['infrastructure','layer1'], coingeckoId:'celestia', cmcId:'22861', cmcSlug:'celestia', githubOrg:'celestiaorg', githubRepo:'celestiaorg/celestia-core', xHandle:'celestia', website:'https://celestia.org', description:'First modular data-availability and consensus network, enabling sovereign rollups to publish transaction data without execution bottlenecks.', tier:'tier1' });
add({ id:'eigenlayer', symbol:'EIGEN', sector:'infrastructure', sectors:['infrastructure','ai','defi'], coingeckoId:'eigenlayer', cmcId:'24733', cmcSlug:'eigenlayer', githubOrg:'Layr-Labs', githubRepo:'Layr-Labs/eigenlayer-contracts', xHandle:'eigenlayer', website:'https://www.eigenlayer.xyz', description:'Restaking protocol that lets ETH stakers secure new AVSs (data layers, oracle networks, AI coprocessors) via pooled security.', tier:'tier1' });
add({ id:'wormhole', symbol:'W', sector:'infrastructure', sectors:['infrastructure','defi'], coingeckoId:'wormhole', cmcId:'29515', cmcSlug:'wormhole', githubOrg:'wormhole-foundation', githubRepo:'wormhole-foundation/wormhole', xHandle:'wormhole', website:'https://wormhole.com', description:'Generic cross-chain message-passing protocol connecting 30+ chains (Ethereum, Solana, Aptos, Sui) for asset and dapp communication.', tier:'tier1' });
add({ id:'layerzero', symbol:'ZRO', sector:'infrastructure', coingeckoId:'layerzero', cmcId:'31374', cmcSlug:'layerzero', githubOrg:'LayerZero-Labs', githubRepo:'LayerZero-Labs/LayerZero-v2', xHandle:'LayerZero_Labs', website:'https://layerzero.network', description:'Omnichain interoperability protocol enabling cross-chain message passing and OFT (Omnichain Fungible Token) standard for native multichain assets.', tier:'tier1' });
add({ id:'axelar', symbol:'AXL', sector:'infrastructure', coingeckoId:'axelar', cmcId:'17799', cmcSlug:'axelar', githubOrg:'axelarnetwork', githubRepo:'axelarnetwork/axelar-core', xHandle:'axelarcore', website:'https://axelar.network', description:'Universal interoperability platform connecting 50+ blockchains via secure cross-chain gateway, general message passing and wrapped assets.', tier:'tier1' });
add({ id:'icp', symbol:'ICP', sector:'infrastructure', sectors:['infrastructure','layer1'], coingeckoId:'internet-computer', cmcId:'8916', cmcSlug:'internet-computer', githubOrg:'dfinity', githubRepo:'dfinity/ic', xHandle:'dfinity', website:'https://internetcomputer.org', description:'Chain-key cryptography L1 that hosts canisters (smart contracts) running at web-speed, enabling fully on-chain web apps and AI inference.', tier:'tier1' });
add({ id:'chainport', symbol:'PORT', sector:'infrastructure', coingeckoId:'chainport', cmcId:'22633', cmcSlug:'chainport', githubOrg:'chainport-io', githubRepo:'chainport-io/chainport-contracts', xHandle:'chainportio', website:'https://www.chainport.io', description:'Non-custodial multichain bridge locking tokens on the source chain and minting wrapped versions on the destination, supporting 20+ networks.', tier:'tier2' });
add({ id:'connext', symbol:'NEXT', sector:'infrastructure', coingeckoId:'connext', cmcId:'21245', cmcSlug:'connext', githubOrg:'connext', githubRepo:'connext/monorepo', xHandle:'ConnextNetwork', website:'https://www.connext.network', description:'Modular interoperability protocol for passing calldata and value between chains, used by Across and other bridges for cross-chain intents.', tier:'tier1' });
add({ id:'everclear', symbol:'CLEAR', sector:'infrastructure', coingeckoId:'everclear', cmcId:'29876', cmcSlug:'everclear', githubOrg:'everclearorg', githubRepo:'everclearorg/everclear', xHandle:'EverclearOrg', website:'https://www.everclear.org', description:'Settlement layer for cross-chain intents, acting as a clearinghouse that batches and nets rebalancing transactions between networks.', tier:'tier2' });
add({ id:'subsquid', symbol:'SQD', sector:'infrastructure', coingeckoId:'subsquid', cmcId:'24455', cmcSlug:'subsquid', githubOrg:'subsquid', githubRepo:'subsquid/squid-sdk', xHandle:'subsquid', website:'https://subsquid.io', description:'Decentralized data lake and GraphQL API for 100+ chains, providing indexed and historical data to dapps at lower cost than RPC.', tier:'tier1' });
add({ id:'goldsky', symbol:'GOLD', sector:'infrastructure', coingeckoId:'goldsky', cmcId:'25110', cmcSlug:'goldsky', githubOrg:'goldsky', githubRepo:'goldsky/goldsky-monorepo', xHandle:'goldskyhq', website:'https://goldsky.com', description:'Drop-in replacement for The Graph providing managed subgraph hosting, mirror pipelines and real-time data APIs for high-throughput dapps.', tier:'tier2' });
add({ id:'nxyz', symbol:'NXYZ', sector:'infrastructure', coingeckoId:'nxyz', cmcId:'24522', cmcSlug:'nxyz', githubOrg:'nxyz', githubRepo:'nxyz/nxyz-sdk', xHandle:'nxyz', website:'https://nxyz.com', description:'High-performance blockchain search and API provider for 30+ chains, used by wallets and trading dashboards to surface real-time data.', tier:'tier2' });
add({ id:'koinly', symbol:'KOINLY', sector:'infrastructure', coingeckoId:'koinly', cmcId:'25422', cmcSlug:'koinly', githubOrg:'koinly', githubRepo:'koinly/koinly-tools', xHandle:'koinly', website:'https://koinly.io', description:'Crypto tax and portfolio platform providing developer API for transaction history, cost-basis calculation and audit reporting across 750+ chains.', tier:'tier2' });
add({ id:'mina', symbol:'MINA', sector:'infrastructure', sectors:['infrastructure','layer1'], coingeckoId:'mina-protocol', cmcId:'8646', cmcSlug:'mina-protocol', githubOrg:'MinaProtocol', githubRepo:'MinaProtocol/mina', xHandle:'MinaProtocol', website:'https://minaprotocol.com', description:'Succinct blockchain that stays a constant ~22 KB using recursive zero-knowledge proofs, used as ZK verification layer for any chain.', tier:'tier1' });
add({ id:'lagrange', symbol:'LA', sector:'infrastructure', sectors:['infrastructure','ai'], coingeckoId:'lagrange', cmcId:'28843', cmcSlug:'lagrange', githubOrg:'Lagrange-Labs', githubRepo:'Lagrange-Labs/lagrange', xHandle:'lagrangelabs', website:'https://www.lagrange.dev', description:'ZK-proving network generating proofs of cross-chain state, used for cross-chain queries and verifiable AI inference.', tier:'tier1' });

module.exports = { PROJECTS };
