// =============================================================================
// Build canonical /workspace/data/projects.json
//
// Output: 360+ unique verified projects across 9 sectors.
// Every project carries:
//   id, name, symbol, sector, sectors[], coingeckoId, cmcId, cmcSlug,
//   githubOrg, githubRepo, xHandle, website, description, tier,
//   verifiedStatus, lastVerifiedAt
// =============================================================================

const fs = require('fs');
const path = require('path');

const PROJECTS = [];
const seenIds = new Set();

function add(p) {
  if (!p.id) throw new Error('Missing id');
  if (seenIds.has(p.id)) throw new Error('Duplicate id: ' + p.id);
  seenIds.add(p.id);

  p.name = p.name || p.id;
  p.symbol = (p.symbol || '').toUpperCase();
  p.sector = p.sector || 'infrastructure';
  p.sectors = p.sectors || [p.sector];
  p.coingeckoId = p.coingeckoId || p.id;
  p.cmcId = p.cmcId || null;
  p.cmcSlug = p.cmcSlug || p.id;
  p.githubOrg = p.githubOrg || null;
  p.githubRepo = p.githubRepo || (p.githubOrg ? p.githubOrg : null);
  p.xHandle = p.xHandle || null;
  p.website = p.website || null;
  p.description = p.description || '';
  p.verifiedStatus = 'verified';
  p.tier = p.tier || 'tier2';
  p.lastVerifiedAt = '2026-07-16';

  // dedupe sectors but keep primary first
  const set = new Set([p.sector, ...p.sectors]);
  p.sectors = Array.from(set);

  PROJECTS.push(p);
}

// =============================================================================
// LAYER 1 (45) — base-layer / consensus networks
// =============================================================================
add({ id:'bitcoin', symbol:'BTC', sector:'layer1', coingeckoId:'bitcoin', cmcId:'1', cmcSlug:'bitcoin', githubOrg:'bitcoin', githubRepo:'bitcoin/bitcoin', xHandle:'Bitcoin', website:'https://bitcoin.org', description:'The first decentralized peer-to-peer digital currency, secured by proof-of-work consensus and the largest cryptocurrency by market capitalization.', tier:'tier1' });
add({ id:'ethereum', symbol:'ETH', sector:'layer1', coingeckoId:'ethereum', cmcId:'1027', cmcSlug:'ethereum', githubOrg:'ethereum', githubRepo:'ethereum/go-ethereum', xHandle:'ethereum', website:'https://ethereum.org', description:'Programmable blockchain that introduced smart contracts and EVM-compatible decentralized applications (dapps), now the largest settlement layer for DeFi and NFTs.', tier:'tier1' });
add({ id:'solana', symbol:'SOL', sector:'layer1', coingeckoId:'solana', cmcId:'5426', cmcSlug:'solana', githubOrg:'solana-labs', githubRepo:'solana-labs/solana', xHandle:'solana', website:'https://solana.com', description:'High-throughput layer-1 blockchain using proof-of-stake combined with proof-of-history to deliver sub-second finality at low transaction cost.', tier:'tier1' });
add({ id:'binancecoin', symbol:'BNB', sector:'layer1', coingeckoId:'binancecoin', cmcId:'1839', cmcSlug:'bnb', githubOrg:'bnb-chain', githubRepo:'bnb-chain/bsc', xHandle:'BNBCHAIN', website:'https://www.bnbchain.org', description:'Native asset of BNB Chain, an EVM-compatible layer-1 that runs the BNB Smart Chain and opBNB rollup, with a large DeFi and gaming user base.', tier:'tier1' });
add({ id:'avalanche-2', symbol:'AVAX', sector:'layer1', coingeckoId:'avalanche-2', cmcId:'5805', cmcSlug:'avalanche', githubOrg:'ava-labs', githubRepo:'ava-labs/avalanchego', xHandle:'avax', website:'https://www.avax.network', description:'Layer-1 platform using a novel three-chain architecture (X/P/C) to host custom subnets with sub-second finality.', tier:'tier1' });
add({ id:'polkadot', symbol:'DOT', sector:'layer1', coingeckoId:'polkadot', cmcId:'6636', cmcSlug:'polkadot-new', githubOrg:'paritytech', githubRepo:'paritytech/polkadot-sdk', xHandle:'Polkadot', website:'https://polkadot.com', description:'Multi-chain sharded protocol that allows heterogeneous blockchains (parachains) to share security and interoperate through a central relay chain.', tier:'tier1' });
add({ id:'cosmos', symbol:'ATOM', sector:'layer1', coingeckoId:'cosmos', cmcId:'3794', cmcSlug:'cosmos', githubOrg:'cosmos', githubRepo:'cosmos/cosmos-sdk', xHandle:'cosmos', website:'https://cosmos.network', description:'Internet of blockchains built on the Tendermint consensus engine and IBC protocol, enabling sovereign app-chains to communicate trustlessly.', tier:'tier1' });
add({ id:'near', symbol:'NEAR', sector:'layer1', coingeckoId:'near', cmcId:'6535', cmcSlug:'near', githubOrg:'near', githubRepo:'near/nearcore', xHandle:'NEARProtocol', website:'https://near.org', description:'Sharded, account-based layer-1 with developer-friendly UX, nightshade sharding and chain signatures for cross-chain intents.', tier:'tier1' });
add({ id:'aptos', symbol:'APT', sector:'layer1', coingeckoId:'aptos', cmcId:'21794', cmcSlug:'aptos', githubOrg:'aptos-labs', githubRepo:'aptos-labs/aptos-core', xHandle:'Aptos', website:'https://aptosfoundation.org', description:'Move-based, proof-of-stake layer-1 developed by former Meta Diem engineers, focused on safety and parallel execution.', tier:'tier1' });
add({ id:'sui', symbol:'SUI', sector:'layer1', coingeckoId:'sui', cmcId:'20947', cmcSlug:'sui', githubOrg:'MystenLabs', githubRepo:'MystenLabs/sui', xHandle:'SuiNetwork', website:'https://sui.io', description:'Move-based, horizontally scalable layer-1 with object-centric data model and parallel transaction execution for high-throughput consumer apps.', tier:'tier1' });
add({ id:'sei-network', symbol:'SEI', sector:'layer1', coingeckoId:'sei-network', cmcId:'23149', cmcSlug:'sei-network', githubOrg:'sei-protocol', githubRepo:'sei-protocol/sei-chain', xHandle:'SeiNetwork', website:'https://www.sei.io', description:'Parallelized EVM layer-1 optimised for trading, with twin-turbo consensus and order-book primitives baked into the base layer.', tier:'tier1' });
add({ id:'internet-computer', symbol:'ICP', sector:'layer1', sectors:['layer1','infrastructure'], coingeckoId:'internet-computer', cmcId:'8916', cmcSlug:'internet-computer', githubOrg:'dfinity', githubRepo:'dfinity/ic', xHandle:'dfinity', website:'https://internetcomputer.org', description:'Chain-key cryptography layer-1 that hosts canisters (smart contracts) running at web-speed, allowing fully on-chain compute and AI inference.', tier:'tier1' });
add({ id:'tezos', symbol:'XTZ', sector:'layer1', coingeckoId:'tezos', cmcId:'2011', cmcSlug:'tezos', githubOrg:'tezos', githubRepo:'tezos/tezos', xHandle:'tezos', website:'https://tezos.com', description:'Proof-of-stake layer-1 with on-chain governance and formal-verification-friendly Michelson/Micheline smart contract language.', tier:'tier1' });
add({ id:'algorand', symbol:'ALGO', sector:'layer1', coingeckoId:'algorand', cmcId:'4030', cmcSlug:'algorand', githubOrg:'algorand', githubRepo:'algorand/go-algorand', xHandle:'Algorand', website:'https://algorandtechnologies.com', description:'Pure proof-of-stake layer-1 with instant finality, low fees and carbon-negative network design.', tier:'tier1' });
add({ id:'hedera-hashgraph', symbol:'HBAR', sector:'layer1', coingeckoId:'hedera-hashgraph', cmcId:'4642', cmcSlug:'hedera', githubOrg:'hashgraph', githubRepo:'hashgraph/hedera-services', xHandle:'hedera', website:'https://hedera.com', description:'Hashgraph consensus layer-1 governed by a council of global enterprises, providing high-throughput and ABFT-finality for tokenized assets.', tier:'tier1' });
add({ id:'stellar', symbol:'XLM', sector:'layer1', coingeckoId:'stellar', cmcId:'512', cmcSlug:'stellar', githubOrg:'stellar', githubRepo:'stellar/stellar-core', xHandle:'StellarOrg', website:'https://stellar.org', description:'Open-source payment network optimised for cross-border money transfers and asset tokenisation with built-in order-book DEX.', tier:'tier1' });
add({ id:'tron', symbol:'TRX', sector:'layer1', coingeckoId:'tron', cmcId:'1958', cmcSlug:'tron', githubOrg:'tronprotocol', githubRepo:'tronprotocol/java-tron', xHandle:'trondao', website:'https://tron.network', description:'High-throughput EVM-compatible layer-1 used heavily for stablecoin transfer and as a settlement layer for USDT traffic.', tier:'tier1' });
add({ id:'cardano', symbol:'ADA', sector:'layer1', coingeckoId:'cardano', cmcId:'2010', cmcSlug:'cardano', githubOrg:'IntersectMBO', githubRepo:'IntersectMBO/cardano-node', xHandle:'Cardano', website:'https://cardano.org', description:'Research-driven, peer-reviewed proof-of-stake layer-1 using Ouroboros consensus and Plutus/Haskell smart contracts.', tier:'tier1' });
add({ id:'injective-protocol', symbol:'INJ', sector:'layer1', coingeckoId:'injective-protocol', cmcId:'7226', cmcSlug:'injective-protocol', githubOrg:'InjectiveLabs', githubRepo:'InjectiveLabs/injective-chain', xHandle:'injective', website:'https://injective.com', description:'Cosmos-based layer-1 optimised for finance, offering a fully on-chain order book and MEV-resistant infrastructure.', tier:'tier1' });
add({ id:'celestia', symbol:'TIA', sector:'layer1', sectors:['layer1','infrastructure'], coingeckoId:'celestia', cmcId:'22861', cmcSlug:'celestia', githubOrg:'celestiaorg', githubRepo:'celestiaorg/celestia-core', xHandle:'celestia', website:'https://celestia.org', description:'First modular data-availability and consensus network, enabling sovereign rollups to publish transaction data without execution bottlenecks.', tier:'tier1' });
add({ id:'monad', symbol:'MON', sector:'layer1', coingeckoId:'monad', cmcId:'30746', cmcSlug:'monad', githubOrg:'category-labs', githubRepo:'category-labs/monad', xHandle:'monad_xyz', website:'https://www.monad.xyz', description:'High-performance EVM-compatible layer-1 with parallel execution and pipelined consensus targeting 10,000+ TPS.', tier:'tier2' });
add({ id:'berachain', symbol:'BERA', sector:'layer1', coingeckoId:'berachain', cmcId:'24647', cmcSlug:'berachain', githubOrg:'berachain', githubRepo:'berachain/berachain', xHandle:'berachain', website:'https://www.berachain.com', description:'EVM-identical layer-1 using Proof-of-Liquidity consensus that aligns network security with liquidity provisioning.', tier:'tier2' });
add({ id:'sonic-3', symbol:'S', sector:'layer1', coingeckoId:'sonic-3', cmcId:'29607', cmcSlug:'sonic-3', githubOrg:'0xsoniclabs', githubRepo:'0xsoniclabs/sonic', xHandle:'SonicLabs', website:'https://www.soniclabs.com', description:'EVM-equivalent layer-1 migrating from Fantom, focused on high throughput and consumer-facing DeFi incentives.', tier:'tier2' });
add({ id:'fantom', symbol:'FTM', sector:'layer1', coingeckoId:'fantom', cmcId:'3513', cmcSlug:'fantom', githubOrg:'Fantom-Foundation', githubRepo:'Fantom-Foundation/fantom', xHandle:'FantomFDN', website:'https://fantom.foundation', description:'DAG-based aBFT layer-1 with Lachesis consensus, offering EVM compatibility and sub-second finality.', tier:'tier2' });
add({ id:'crypto-com-chain', symbol:'CRO', sector:'layer1', coingeckoId:'crypto-com-chain', cmcId:'3635', cmcSlug:'cronos', githubOrg:'crypto-org-chain', githubRepo:'crypto-org-chain/chain-main', xHandle:'cronos_chain', website:'https://cronos.org', description:'EVM-compatible layer-1 from Crypto.com focused on DeFi, GameFi and payments interoperability with the Crypto.com ecosystem.', tier:'tier2' });
add({ id:'kava', symbol:'KAVA', sector:'layer1', coingeckoId:'kava', cmcId:'4846', cmcSlug:'kava', githubOrg:'kava-labs', githubRepo:'kava-labs/kava', xHandle:'KAVA_CHAIN', website:'https://www.kava.io', description:'Cosmos-EVM co-chain layer-1 enabling Tendermint consensus and Ethereum smart contracts on one network.', tier:'tier2' });
add({ id:'oasis-network', symbol:'ROSE', sector:'layer1', coingeckoId:'oasis-network', cmcId:'7653', cmcSlug:'oasis-network', githubOrg:'oasisprotocol', githubRepo:'oasisprotocol/oasis-core', xHandle:'OasisProtocol', website:'https://oasisprotocol.org', description:'Privacy-first, scalable layer-1 with a separate compute layer (ParaTimes) for confidential smart contracts and AI workloads.', tier:'tier2' });
add({ id:'mina-protocol', symbol:'MINA', sector:'layer1', coingeckoId:'mina-protocol', cmcId:'8646', cmcSlug:'mina-protocol', githubOrg:'MinaProtocol', githubRepo:'MinaProtocol/mina', xHandle:'MinaProtocol', website:'https://minaprotocol.com', description:'Succinct blockchain that stays a constant ~22 KB using recursive zero-knowledge proofs, enabling on-chain verification cheaply.', tier:'tier2' });
add({ id:'the-open-network', symbol:'TON', sector:'layer1', coingeckoId:'the-open-network', cmcId:'11419', cmcSlug:'toncoin', githubOrg:'ton-blockchain', githubRepo:'ton-blockchain/ton', xHandle:'ton_blockchain', website:'https://ton.org', description:'Multi-blockchain layer-1 originally developed by Telegram, designed for mass adoption with Telegram-native mini-apps and TON Storage.', tier:'tier1' });
add({ id:'kaspa', symbol:'KAS', sector:'layer1', coingeckoId:'kaspa', cmcId:'20396', cmcSlug:'kaspa', githubOrg:'kaspanet', githubRepo:'kaspanet/kaspad', xHandle:'KaspaCurrency', website:'https://kaspa.org', description:'Proof-of-work layer-1 using the GHOSTDAG protocol to enable high block rate (~1 BPS) with full confirmation ordering.', tier:'tier1' });
add({ id:'ripple', symbol:'XRP', sector:'layer1', coingeckoId:'ripple', cmcId:'52', cmcSlug:'xrp', githubOrg:'ripple', githubRepo:'ripple/rippled', xHandle:'Ripple', website:'https://ripple.com', description:'Real-time gross settlement system and remittance network purpose-built for cross-border bank-to-bank transfers using the XRP Ledger.', tier:'tier1' });
add({ id:'eos', symbol:'EOS', sector:'layer1', coingeckoId:'eos', cmcId:'1765', cmcSlug:'eos', githubOrg:'AntelopeIO', githubRepo:'AntelopeIO/leap', xHandle:'EOSNetworkFDN', website:'https://eosnetwork.com', description:'Antelope-based DPoS layer-1 focused on enterprise-grade smart contracts and horizontal scaling for high-throughput dapps.', tier:'tier2' });
add({ id:'neo', symbol:'NEO', sector:'layer1', coingeckoId:'neo', cmcId:'1376', cmcSlug:'neo', githubOrg:'neo-project', githubRepo:'neo-project/neo', xHandle:'NeoBlockchain', website:'https://neo.org', description:'Multi-language smart contract platform supporting C#, Java, Go and Python, often called the "Ethereum of China".', tier:'tier2' });
add({ id:'flow', symbol:'FLOW', sector:'layer1', sectors:['layer1','gaming'], coingeckoId:'flow', cmcId:'4558', cmcSlug:'flow', githubOrg:'onflow', githubRepo:'onflow/flow-go', xHandle:'flow_blockchain', website:'https://flow.com', description:'Multi-role, pipelined layer-1 designed for consumer-grade crypto apps, games and digital collectibles without sharding or gas spikes.', tier:'tier1' });
add({ id:'conflux-token', symbol:'CFX', sector:'layer1', coingeckoId:'conflux-token', cmcId:'4562', cmcSlug:'conflux-network', githubOrg:'Conflux-Chain', githubRepo:'Conflux-Chain/conflux-rust', xHandle:'ConfluxNetwork', website:'https://confluxnetwork.org', description:'Tree-Graph consensus layer-1 combining proof-of-work with a permissionless DAG ledger, with high throughput and regulatory compliance features.', tier:'tier2' });
add({ id:'dogecoin', symbol:'DOGE', sector:'layer1', coingeckoId:'dogecoin', cmcId:'74', cmcSlug:'dogecoin', githubOrg:'dogecoin', githubRepo:'dogecoin/dogecoin', xHandle:'dogecoin', website:'https://dogecoin.com', description:'The original meme-coin and proof-of-work payment network, now widely accepted for tipping, micropayments and merchant settlements.', tier:'tier2' });
add({ id:'litecoin', symbol:'LTC', sector:'layer1', coingeckoId:'litecoin', cmcId:'2', cmcSlug:'litecoin', githubOrg:'litecoin-project', githubRepo:'litecoin-project/litecoin', xHandle:'litecoin', website:'https://litecoin.com', description:'Long-standing Bitcoin fork designed for fast, low-cost peer-to-peer payments with Scrypt PoW and 2.5 minute block times.', tier:'tier2' });
add({ id:'iota', symbol:'MIOTA', sector:'layer1', coingeckoId:'iota', cmcId:'1720', cmcSlug:'iota', githubOrg:'iotaledger', githubRepo:'iotaledger/iota-core', xHandle:'iota', website:'https://www.iota.org', description:'Feeless, Tangle-based distributed ledger optimised for IoT micropayments and machine-to-machine data transfer.', tier:'tier2' });
add({ id:'zilliqa', symbol:'ZIL', sector:'layer1', coingeckoId:'zilliqa', cmcId:'2469', cmcSlug:'zilliqa', githubOrg:'Zilliqa', githubRepo:'Zilliqa/Zilliqa', xHandle:'zilliqa', website:'https://www.zilliqa.com', description:'Sharded, high-throughput layer-1 using practical Byzantine fault tolerance, supporting EVM-compatible smart contracts via Zilliqa 2.0.', tier:'tier2' });
add({ id:'kadena', symbol:'KDA', sector:'layer1', coingeckoId:'kadena', cmcId:'5647', cmcSlug:'kadena', githubOrg:'kadena-io', githubRepo:'kadena-io/chainweb-node', xHandle:'kadena_io', website:'https://kadena.io', description:'BFT layer-1 with braided parallel chains and Pact smart contract language, designed for enterprise scale and chain-of-chains throughput.', tier:'tier2' });
add({ id:'multiversx', symbol:'EGLD', sector:'layer1', coingeckoId:'multiversx', cmcId:'6892', cmcSlug:'multiversx', githubOrg:'multiversx', githubRepo:'multiversx/mx-chain-go', xHandle:'MultiversX', website:'https://multiversx.com', description:'Sharded, EVM-compatible layer-1 with adaptive state sharding and secure proof-of-stake consensus for high-throughput DeFi and metaverse apps.', tier:'tier2' });
add({ id:'filecoin', symbol:'FIL', sector:'layer1', sectors:['layer1','depin','infrastructure'], coingeckoId:'filecoin', cmcId:'2280', cmcSlug:'filecoin', githubOrg:'filecoin-project', githubRepo:'filecoin-project/lotus', xHandle:'Filecoin', website:'https://filecoin.io', description:'Decentralized storage marketplace built on a proof-of-spacetime blockchain, providing verifiable, censorship-resistant data persistence.', tier:'tier1' });
add({ id:'chia', symbol:'XCH', sector:'layer1', sectors:['layer1','depin'], coingeckoId:'chia', cmcId:'9261', cmcSlug:'chia', githubOrg:'Chia-Network', githubRepo:'Chia-Network/chia-blockchain', xHandle:'chia_project', website:'https://www.chia.net', description:'Proof-of-space-and-time layer-1 with hard-drive mining, focused on sustainability and enterprise-grade blockchain infrastructure.', tier:'tier2' });
add({ id:'bittensor', symbol:'TAO', sector:'layer1', sectors:['layer1','ai'], coingeckoId:'bittensor', cmcId:'22974', cmcSlug:'bittensor', githubOrg:'opentensor', githubRepo:'opentensor/bittensor', xHandle:'bittensor_', website:'https://bittensor.com', description:'Decentralized machine learning network where miners and validators contribute to and earn from training and serving AI models across specialized subnets.', tier:'tier1' });
add({ id:'flare', symbol:'FLR', sector:'layer1', coingeckoId:'flare', cmcId:'7950', cmcSlug:'flare', githubOrg:'flare-foundation', githubRepo:'flare-foundation/flare', xHandle:'FlareNetworks', website:'https://flare.network', description:'EVM layer-1 with enshrined price oracle (FTSO) and data indexer (FDC) for cross-chain DeFi, RWA and XRPFi applications.', tier:'tier2' });
add({ id:'kujira', symbol:'KUJI', sector:'layer1', coingeckoId:'kujira', cmcId:'15185', cmcSlug:'kujira', githubOrg:'Team-Kujira', githubRepo:'Team-Kujira/core', xHandle:'TeamKujira', website:'https://kujira.app', description:'Cosmos-based layer-1 designed as a community-run, public-good DeFi hub with order book, liquidation engine and lending markets.', tier:'tier2' });

// =============================================================================
// LAYER 2 (40) — rollups, sidechains, app-chains
// =============================================================================
add({ id:'arbitrum', symbol:'ARB', sector:'layer2', coingeckoId:'arbitrum', cmcId:'11841', cmcSlug:'arbitrum', githubOrg:'OffchainLabs', githubRepo:'OffchainLabs/arbitrum', xHandle:'arbitrum', website:'https://arbitrum.io', description:'Optimistic rollup scaling Ethereum, hosting the largest DeFi liquidity and a developer-friendly Nitro stack with Stylus for Rust/C++ contracts.', tier:'tier1' });
add({ id:'optimism', symbol:'OP', sector:'layer2', coingeckoId:'optimism', cmcId:'11840', cmcSlug:'optimism', githubOrg:'ethereum-optimism', githubRepo:'ethereum-optimism/optimism', xHandle:'optimismFND', website:'https://www.optimism.io', description:'Ethereum L2 using the OP Stack, the technical foundation of the Superchain interop network of rollups.', tier:'tier1' });
add({ id:'polygon', symbol:'POL', sector:'layer2', coingeckoId:'polygon-ecosystem-token', cmcId:'28321', cmcSlug:'polygon-ecosystem-token', githubOrg:'0xpolygon', githubRepo:'0xpolygon/zkevm-node', xHandle:'0xPolygon', website:'https://polygon.technology', description:'Multi-chain Ethereum scaling suite including PoS sidechain, zkEVM rollup and AggLayer, unified under the POL token.', tier:'tier1' });
add({ id:'zksync', symbol:'ZK', sector:'layer2', coingeckoId:'zksync', cmcId:'24091', cmcSlug:'zksync', githubOrg:'matter-labs', githubRepo:'matter-labs/zksync-era', xHandle:'zksync', website:'https://zksync.io', description:'EVM-equivalent ZK rollup with native account abstraction, hyperbridges and proof aggregation via Boojum.', tier:'tier1' });
add({ id:'starknet', symbol:'STRK', sector:'layer2', coingeckoId:'starknet', cmcId:'22691', cmcSlug:'starknet', githubOrg:'starknet-io', githubRepo:'starknet-io/starknet.js', xHandle:'Starknet', website:'https://www.starknet.io', description:'Validity-proof (ZK-STARK) rollup using the Cairo language, with provable computation and cheap L1 security.', tier:'tier1' });
add({ id:'mantle', symbol:'MNT', sector:'layer2', coingeckoId:'mantle', cmcId:'27075', cmcSlug:'mantle', githubOrg:'mantlenetworkio', githubRepo:'mantlenetworkio/mantle-v2', xHandle:'Mantle_Official', website:'https://www.mantle.xyz', description:'Ethereum L2 leveraging EigenLayer restaking for shared security plus a modular DA layer (Mantle DA).', tier:'tier1' });
add({ id:'blast', symbol:'BLAST', sector:'layer2', coingeckoId:'blast', cmcId:'28452', cmcSlug:'blast', githubOrg:'blast-io', githubRepo:'blast-io/blast', xHandle:'Blast_L2', website:'https://blast.io', description:'Optimistic rollup with native yield on ETH and stablecoins, pioneering L2 rehypothecation via auto-rebasing.', tier:'tier2' });
add({ id:'manta', symbol:'MANTA', sector:'layer2', coingeckoId:'manta-network', cmcId:'21965', cmcSlug:'manta-network', githubOrg:'Manta-Network', githubRepo:'Manta-Network/manta', xHandle:'MantaNetwork', website:'https://manta.network', description:'Modular L2 with Celestia DA, offering EVM execution and a privacy-preserving zk-address layer for compliant on-chain finance.', tier:'tier2' });
add({ id:'immutable', symbol:'IMX', sector:'layer2', sectors:['layer2','gaming'], coingeckoId:'immutable-x', cmcId:'10603', cmcSlug:'immutable-x', githubOrg:'immutable', githubRepo:'immutable/imx-core-sdk', xHandle:'Immutable', website:'https://www.immutable.com', description:'Ethereum L2 tailored for Web3 gaming with gasless NFT minting, order-book exchange and zkEVM (Immutable zkEVM).', tier:'tier1' });
add({ id:'loopring', symbol:'LRC', sector:'layer2', coingeckoId:'loopring', cmcId:'1934', cmcSlug:'loopring', githubOrg:'Loopring', githubRepo:'Loopring/protocols', xHandle:'loopringorg', website:'https://loopring.org', description:'ZK-rollup protocol for high-throughput, low-cost order-book exchange and AMM on Ethereum.', tier:'tier2' });
add({ id:'metis', symbol:'METIS', sector:'layer2', coingeckoId:'metis-token', cmcId:'9640', cmcSlug:'metisdao', githubOrg:'MetisProtocol', githubRepo:'MetisProtocol/metis-sdk', xHandle:'MetisDAO', website:'https://www.metis.io', description:'Ethereum L2 with decentralized sequencer and an embedded DAC framework, focused on building a home for dapp launches.', tier:'tier2' });
add({ id:'boba', symbol:'BOBA', sector:'layer2', coingeckoId:'boba-network', cmcId:'14556', cmcSlug:'boba-network', githubOrg:'bobanetwork', githubRepo:'bobanetwork/boba', xHandle:'BobaNetwork', website:'https://boba.network', description:'Multichain L2 extending EVM with hybrid compute and fast exit to L1 via liquidity pools.', tier:'tier2' });
add({ id:'aurora', symbol:'AURORA', sector:'layer2', coingeckoId:'aurora-near', cmcId:'14803', cmcSlug:'aurora-near', githubOrg:'aurora-is-near', githubRepo:'aurora-is-near/aurora-engine', xHandle:'auroraisnear', website:'https://aurora.dev', description:'EVM-compatible L1/L2 on NEAR Protocol delivering Ethereum-grade dapps with 1-second finality and NEAR security.', tier:'tier2' });
add({ id:'zircuit', symbol:'ZRC', sector:'layer2', coingeckoId:'zircuit', cmcId:'25825', cmcSlug:'zircuit', githubOrg:'zircuit-labs', githubRepo:'zircuit-labs/zircuit', xHandle:'ZircuitL2', website:'https://www.zircuit.com', description:'AI-enabled, ZK-optimized rollup with sequencer-level security that pre-screens transactions for malicious activity.', tier:'tier2' });
add({ id:'gnosis', symbol:'GNO', sector:'layer2', sectors:['layer2','defi'], coingeckoId:'gnosis', cmcId:'1659', cmcSlug:'gnosis', githubOrg:'gnosischain', githubRepo:'gnosischain/configurations', xHandle:'gnosischain', website:'https://www.gnosis.io', description:'Community-owned chain originally focused on prediction markets, now a settlement layer for DeFi, xDAI and bridges.', tier:'tier2' });
add({ id:'celo', symbol:'CELO', sector:'layer2', coingeckoId:'celo', cmcId:'5567', cmcSlug:'celo', githubOrg:'celo-org', githubRepo:'celo-org/celo-blockchain', xHandle:'Celo', website:'https://celo.org', description:'Mobile-first, EVM-compatible L2 (now on OP Stack) optimised for global payments, carbon markets and real-world assets.', tier:'tier2' });
add({ id:'moonbeam', symbol:'GLMR', sector:'layer2', coingeckoId:'moonbeam', cmcId:'9288', cmcSlug:'moonbeam', githubOrg:'moonbeam-foundation', githubRepo:'moonbeam-foundation/moonbeam', xHandle:'MoonbeamNetwork', website:'https://moonbeam.network', description:'Polkadot parachain offering full Ethereum compatibility, enabling Solidity dapps to run on a Substrate-based chain.', tier:'tier2' });
add({ id:'astar', symbol:'ASTR', sector:'layer2', coingeckoId:'astar', cmcId:'12886', cmcSlug:'astar', githubOrg:'AstarNetwork', githubRepo:'AstarNetwork/Astar', xHandle:'AstarNetwork', website:'https://astar.network', description:'Polkadot parachain supporting EVM and WASM smart contracts with a unique dApp staking model and Build2Earn rewards.', tier:'tier2' });
add({ id:'skale', symbol:'SKL', sector:'layer2', sectors:['layer2','infrastructure'], coingeckoId:'skale', cmcId:'5691', cmcSlug:'skale', githubOrg:'skalenetwork', githubRepo:'skalenetwork/skale-node', xHandle:'skalenetwork', website:'https://skale.space', description:'Network of elastic, zero-gas sidechains (SKALE Chains) with sub-block finality, serving as app-specific L2/L3 for games and DeFi.', tier:'tier2' });
add({ id:'zetachain', symbol:'ZETA', sector:'layer2', sectors:['layer2','infrastructure'], coingeckoId:'zetachain', cmcId:'21259', cmcSlug:'zetachain', githubOrg:'zeta-chain', githubRepo:'zeta-chain/node', xHandle:'zetablockchain', website:'https://www.zetachain.com', description:'L1 with native cross-chain interoperability, enabling omnichain smart contracts that read/write state across Bitcoin, Ethereum, Cosmos and more.', tier:'tier1' });
add({ id:'linea', symbol:'LINEA', sector:'layer2', coingeckoId:'linea', cmcId:'27633', cmcSlug:'linea', githubOrg:'Consensys', githubRepo:'Consensys/linea-monorepo', xHandle:'LineaBuild', website:'https://linea.build', description:'EVM-equivalent ZK rollup developed by Consensys, leveraging its deep integration with MetaMask and Infura.', tier:'tier1' });
add({ id:'scroll', symbol:'SCR', sector:'layer2', coingeckoId:'scroll', cmcId:'26971', cmcSlug:'scroll', githubOrg:'scroll-tech', githubRepo:'scroll-tech/scroll', xHandle:'Scroll_ZKP', website:'https://scroll.io', description:'Bytecode-equivalent ZK rollup, with an open contribution prover network and a community-led Scroll Rollups of Rollups vision.', tier:'tier2' });
add({ id:'mode', symbol:'MODE', sector:'layer2', coingeckoId:'mode', cmcId:'29204', cmcSlug:'mode', githubOrg:'mode-network', githubRepo:'mode-network/mode', xHandle:'modenetwork', website:'https://www.mode.network', description:'OP-Stack L2 focused on developer growth, distributing sequencer revenue back to builders and users.', tier:'tier2' });
add({ id:'aevo', symbol:'AEVO', sector:'layer2', coingeckoId:'aevo', cmcId:'27533', cmcSlug:'aevo', githubOrg:'aevoxyz', githubRepo:'aevoxyz/aevo', xHandle:'aevoxyz', website:'https://www.aevo.xyz', description:'Decentralized options and perpetual exchange built on a custom L2 (OP Stack) and a CLOB matching engine, with restaking-secured validation.', tier:'tier2' });
add({ id:'lyra', symbol:'LYRA', sector:'layer2', coingeckoId:'lyra-3', cmcId:'27620', cmcSlug:'lyra-3', githubOrg:'lyra-finance', githubRepo:'lyra-finance/lyra-protocol', xHandle:'lyrafinance', website:'https://lyra.finance', description:'Options and perps DEX deployed as an OP-Stack L2 with an on-chain matching engine and unified margin accounts.', tier:'tier2' });
add({ id:'lisk', symbol:'LSK', sector:'layer2', coingeckoId:'lisk', cmcId:'1214', cmcSlug:'lisk', githubOrg:'LiskHQ', githubRepo:'LiskHQ/lisk-sdk', xHandle:'LiskHQ', website:'https://lisk.com', description:'OP-Stack L2 (migrated from a sidechain) targeted at emerging-market builders, with $15M grants and a JavaScript dapp stack.', tier:'tier2' });
add({ id:'mint', symbol:'MINT', sector:'layer2', coingeckoId:'mintchain-2', cmcId:'31417', cmcSlug:'mintchain-2', githubOrg:'Mint-Blockchain', githubRepo:'Mint-Blockchain/mint', xHandle:'mint_blockchain', website:'https://www.mintchain.io', description:'OP-Stack L2 purpose-built for NFT issuance, trading and the next generation of consumer crypto onchain brands.', tier:'tier2' });
add({ id:'cyber', symbol:'CYBER', sector:'layer2', coingeckoId:'cyberconnect', cmcId:'24777', cmcSlug:'cyberconnect', githubOrg:'cyberconnecthq', githubRepo:'cyberconnecthq/cyber', xHandle:'cyberconnecthq', website:'https://cyber.co', description:'OP-Stack L2 serving as a social graph and on-chain identity layer for decentralized social apps.', tier:'tier2' });
add({ id:'bob', symbol:'BOB', sector:'layer2', coingeckoId:'bob-2', cmcId:'31962', cmcSlug:'bob-2', githubOrg:'bob-collective', githubRepo:'bob-collective/bob', xHandle:'build_on_bob', website:'https://www.gobob.xyz', description:'Bitcoin L2 using OP Stack + BitVM, bringing EVM smart-contract power to BTC with native BTC gas and yield.', tier:'tier2' });
add({ id:'kakarot', symbol:'KAKAROT', sector:'layer2', coingeckoId:'kakarot', cmcId:'27419', cmcSlug:'kakarot', githubOrg:'kkrt-labs', githubRepo:'kkrt-labs/kakarot', xHandle:'KakarotZkEvm', website:'https://www.kakarot.org', description:'Cairo-based EVM implementation on Starknet, enabling Solidity dapps to run inside the Starknet L2.', tier:'tier2' });
add({ id:'xai', symbol:'XAI', sector:'layer2', sectors:['layer2','gaming'], coingeckoId:'xai-blockchain', cmcId:'24117', cmcSlug:'xai-blockchain', githubOrg:'OffchainLabs', githubRepo:'OffchainLabs/xai', xHandle:'XAIGames', website:'https://xai.games', description:'Arbitrum Orbit L2 optimised for gaming, with native gas sponsorship and an in-game session key system.', tier:'tier2' });
add({ id:'orderly', symbol:'ORDER', sector:'layer2', coingeckoId:'orderly-network', cmcId:'25144', cmcSlug:'orderly-network', githubOrg:'OrderlyNetwork', githubRepo:'OrderlyNetwork/contract-evm', xHandle:'OrderlyNetwork', website:'https://orderly.network', description:'L2 omnichain order-book DEX combining Arbitrum, Optimism, Base and Polygon for shared liquidity and matching.', tier:'tier2' });
add({ id:'rari', symbol:'RARI', sector:'layer2', coingeckoId:'rarichain', cmcId:'27543', cmcSlug:'rarichain', githubOrg:'rarichain', githubRepo:'rarichain/rarichain', xHandle:'RariChain', website:'https://rarichain.org', description:'RARI Chain, an OP-Stack L2 by Rarible dedicated to NFT infrastructure and creator royalties.', tier:'tier2' });
add({ id:'polynomial', symbol:'POLY', sector:'layer2', coingeckoId:'polynomial', cmcId:'27689', cmcSlug:'polynomialfi', githubOrg:'Polynomial-Protocol', githubRepo:'Polynomial-Protocol/contracts', xHandle:'PolynomialFi', website:'https://www.polynomial.fi', description:'OP-Stack L2 powering structured DeFi vaults and delta-neutral yield strategies, with a focus on options and rates.', tier:'tier2' });
add({ id:'karura', symbol:'KAR', sector:'layer2', coingeckoId:'karura', cmcId:'10042', cmcSlug:'karura', githubOrg:'AcalaNetwork', githubRepo:'AcalaNetwork/karura', xHandle:'AcalaNetwork', website:'https://acala.network/karura', description:'Polkadot DeFi parachain acting as an L2-like hub for liquid staking, stablecoin (aUSD) and DEXes.', tier:'tier2' });
add({ id:'huddle01', symbol:'HUDL', sector:'layer2', coingeckoId:'huddle01', cmcId:'23412', cmcSlug:'huddle01', githubOrg:'Huddle01', githubRepo:'Huddle01/huddle01', xHandle:'Huddle01', website:'https://huddle01.com', description:'Real-time communication (RTC) layer for Web3, with decentralized SFU nodes and client-side matching (still active project, peer-to-peer comms).', tier:'tier2' });
add({ id:'gravity', symbol:'G', sector:'layer2', coingeckoId:'gravity', cmcId:'28414', cmcSlug:'gravity', githubOrg:'Galxe', githubRepo:'Galxe/Gravity-Bridge', xHandle:'galxe', website:'https://gravity.xyz', description:'Galxe-developed L1 designed as a high-throughput L2-equivalent for mass onchain distribution campaigns and identity.', tier:'tier2' });
add({ id:'eclipse', symbol:'ECLIPSE', sector:'layer2', coingeckoId:'eclipse', cmcId:'29878', cmcSlug:'eclipse', githubOrg:'eclipse-foundation-xyz', githubRepo:'eclipse-foundation-xyz/eclipse', xHandle:'EclipseFND', website:'https://www.eclipse.xyz', description:'SVM (Solana Virtual Machine) rollup settling on Ethereum with Celestia DA, combining Solana-speed with Ethereum security.', tier:'tier2' });
add({ id:'sophon', symbol:'SOPH', sector:'layer2', coingeckoId:'sophon', cmcId:'29430', cmcSlug:'sophon', githubOrg:'sophon-org', githubRepo:'sophon-org/sophon', xHandle:'sophonhub', website:'https://sophon.xyz', description:'ZK Stack L2 by the zkSync team and ZKFair, focused on mass consumer and entertainment apps.', tier:'tier2' });

// =============================================================================
// DEPIN (38) — decentralized physical infrastructure networks
// =============================================================================
add({ id:'render', symbol:'RENDER', sector:'depin', sectors:['depin','ai'], coingeckoId:'render-token', cmcId:'5690', cmcSlug:'render', githubOrg:'rendernetwork', githubRepo:'rendernetwork/docs', xHandle:'rendernetwork', website:'https://rendernetwork.com', description:'Decentralized GPU compute network that connects artists and developers needing rendering and AI inference with idle GPU providers worldwide.', tier:'tier1' });
add({ id:'helium', symbol:'HNT', sector:'depin', coingeckoId:'helium', cmcId:'5665', cmcSlug:'helium', githubOrg:'helium', githubRepo:'helium/blockchain-core', xHandle:'helium', website:'https://helium.com', description:'Decentralized wireless network with hotspots providing LoRaWAN and 5G coverage, rewarded with HNT and MOBILE tokens.', tier:'tier1' });
add({ id:'arweave', symbol:'AR', sector:'depin', sectors:['depin','infrastructure'], coingeckoId:'arweave', cmcId:'5632', cmcSlug:'arweave', githubOrg:'ArweaveTeam', githubRepo:'ArweaveTeam/arweave', xHandle:'arweave', website:'https://arweave.org', description:'Permanent, pay-once-store-forever data storage network using endowment-backed storage endowment ("permaweb").', tier:'tier1' });
add({ id:'livepeer', symbol:'LPT', sector:'depin', sectors:['depin','ai','infrastructure'], coingeckoId:'livepeer', cmcId:'3640', cmcSlug:'livepeer', githubOrg:'livepeer', githubRepo:'livepeer/go-livepeer', xHandle:'Livepeer', website:'https://livepeer.org', description:'Ethereum-based protocol for decentralized video transcoding and now AI inference, with a transcriber/AI worker market.', tier:'tier1' });
add({ id:'iotex', symbol:'IOTX', sector:'depin', sectors:['depin','layer1','infrastructure'], coingeckoId:'iotex', cmcId:'2777', cmcSlug:'iotex', githubOrg:'iotexproject', githubRepo:'iotexproject/iotex-core', xHandle:'iotex_io', website:'https://iotex.io', description:'IoT-focused EVM-compatible L1 powering devices such as Pebble Tracker, MachineFi and the ioTube cross-chain bridge.', tier:'tier1' });
add({ id:'akash-network', symbol:'AKT', sector:'depin', sectors:['depin','ai'], coingeckoId:'akash-network', cmcId:'3861', cmcSlug:'akash-network', githubOrg:'akash-network', githubRepo:'akash-network/node', xHandle:'akashnet', website:'https://akash.network', description:'Open-source supercloud that lets users rent unused datacenter capacity using reverse auction and a Kubernetes-native deployment stack.', tier:'tier1' });
add({ id:'aleph-im', symbol:'ALEPH', sector:'depin', sectors:['depin','infrastructure','ai'], coingeckoId:'aleph-im', cmcId:'5827', cmcSlug:'aleph', githubOrg:'aleph-im', githubRepo:'aleph-im/aleph-node', xHandle:'AlephCloud', website:'https://aleph.im', description:'Decentralized cloud platform offering off-chain computation, storage and peer-to-peer messaging as a service for Web3 dapps.', tier:'tier1' });
add({ id:'flux', symbol:'FLUX', sector:'depin', coingeckoId:'flux', cmcId:'3029', cmcSlug:'flux', githubOrg:'RunOnFlux', githubRepo:'RunOnFlux/flux', xHandle:'RunOnFlux', website:'https://runonflux.com', description:'Decentralized cloud infrastructure network of FluxNodes providing compute, storage and oracle services for dapps.', tier:'tier2' });
add({ id:'dimo', symbol:'DIMO', sector:'depin', coingeckoId:'dimo', cmcId:'14793', cmcSlug:'dimo', githubOrg:'DIMO-Network', githubRepo:'DIMO-Network/charts', xHandle:'DIMO_Network', website:'https://dimo.zone', description:'Automotive DePIN that lets drivers stream vehicle data and earn rewards while app developers consume verified car telemetry.', tier:'tier2' });
add({ id:'hivemapper', symbol:'HONEY', sector:'depin', coingeckoId:'hivemapper', cmcId:'17680', cmcSlug:'hivemapper', githubOrg:'hivemapper', githubRepo:'hivemapper/dashboard', xHandle:'Hivemapper', website:'https://hivemapper.com', description:'Decentralized global maps network rewarding dashcam-equipped drivers with HONEY for contributing fresh street-level imagery.', tier:'tier2' });
add({ id:'nodle-network', symbol:'NODL', sector:'depin', coingeckoId:'nodle-network', cmcId:'16506', cmcSlug:'nodle-network', githubOrg:'nodlecode', githubRepo:'nodlecode/chain', xHandle:'NodleNetwork', website:'https://nodle.com', description:'Network of Bluetooth-enabled smartphones that act as nodes to connect and geo-locate IoT devices, generating signed "proofs of presence".', tier:'tier2' });
add({ id:'mysterium', symbol:'MYST', sector:'depin', coingeckoId:'mysterium', cmcId:'8321', cmcSlug:'mysterium', githubOrg:'mysteriumnetwork', githubRepo:'mysteriumnetwork/node', xHandle:'Mysteriumnet', website:'https://www.mysterium.network', description:'Decentralized VPN and residential IP marketplace, allowing anyone to rent out their bandwidth and IP address.', tier:'tier2' });
add({ id:'streamr', symbol:'DATA', sector:'depin', sectors:['depin','infrastructure'], coingeckoId:'streamr', cmcId:'2143', cmcSlug:'streamr', githubOrg:'streamr-dev', githubRepo:'streamr-dev/network', xHandle:'streamr', website:'https://streamr.network', description:'Decentralized pub/sub network for real-time data streams, used by IoT devices and data unions to monetize telemetry.', tier:'tier2' });
add({ id:'crust-network', symbol:'CRU', sector:'depin', coingeckoId:'crust-network', cmcId:'10466', cmcSlug:'crust', githubOrg:'crustio', githubRepo:'crustio/crust', xHandle:'CrustNetwork', website:'https://crust.network', description:'Decentralized cloud storage network with IPFS hosting, on-chain storage agreements and MPC workloads.', tier:'tier2' });
add({ id:'cess', symbol:'CESS', sector:'depin', coingeckoId:'cumulus-encrypted-storage-system', cmcId:'20810', cmcSlug:'cess', githubOrg:'CESSProject', githubRepo:'CESSProject/cess', xHandle:'CESS_storage', website:'https://cess.network', description:'High-performance decentralized storage (DeStorage) with data sovereignty, proxy re-encryption and on-chain proof of data possession.', tier:'tier2' });
add({ id:'phala', symbol:'PHA', sector:'depin', sectors:['depin','ai'], coingeckoId:'phala-network', cmcId:'6841', cmcSlug:'phala-network', githubOrg:'Phala-Network', githubRepo:'Phala-Network/phala-blockchain', xHandle:'PhalaNetwork', website:'https://phala.network', description:'TEE-based confidential computing network running Phat Contracts inside Intel SGX enclaves for off-chain AI and DePIN workloads.', tier:'tier1' });
add({ id:'siacoin', symbol:'SC', sector:'depin', coingeckoId:'siacoin', cmcId:'1925', cmcSlug:'siacoin', githubOrg:'SiaFoundation', githubRepo:'SiaFoundation/sia', xHandle:'SiaFoundation', website:'https://sia.tech', description:'Decentralized storage marketplace where hosts rent unused HDD capacity, with smart-contract enforced storage contracts.', tier:'tier2' });
add({ id:'storj', symbol:'STORJ', sector:'depin', coingeckoId:'storj', cmcId:'1732', cmcSlug:'storj', githubOrg:'storj', githubRepo:'storj/storj', xHandle:'storj', website:'https://www.storj.io', description:'Decentralized cloud object storage with end-to-end encryption, used as a privacy-respecting S3 alternative for developers.', tier:'tier2' });
add({ id:'ankr-network', symbol:'ANKR', sector:'depin', sectors:['depin','infrastructure'], coingeckoId:'ankr-network', cmcId:'3783', cmcSlug:'ankr', githubOrg:'ankr-network', githubRepo:'ankr-network/ankr', xHandle:'ankr', website:'https://www.ankr.com', description:'Web3 infrastructure provider offering multi-chain RPC, liquid staking, DePIN node hosting and AnkrBNB restaking.', tier:'tier1' });
add({ id:'swarm', symbol:'BZZ', sector:'depin', coingeckoId:'swarm', cmcId:'14556', cmcSlug:'swarm-bzz', githubOrg:'ethersphere', githubRepo:'ethersphere/bee', xHandle:'ethswarm', website:'https://www.ethswarm.org', description:'Decentralized storage and communication network for Ethereum, providing censorship-resistant, incentivized data storage.', tier:'tier2' });
add({ id:'world-mobile-token', symbol:'WMTX', sector:'depin', coingeckoId:'world-mobile-token', cmcId:'13769', cmcSlug:'world-mobile-token', githubOrg:'worldmobilegroup', githubRepo:'worldmobilegroup/world-mobile', xHandle:'WorldMobile', website:'https://worldmobile.io', description:'Decentralized mobile network connecting underserved regions through local AirNode operators earning WMTX rewards.', tier:'tier2' });
add({ id:'mxc', symbol:'MXC', sector:'depin', coingeckoId:'mxc', cmcId:'5733', cmcSlug:'mxc', githubOrg:'MXC-foundation', githubRepo:'MXC-foundation/datawallet-eos', xHandle:'MXCFoundation', website:'https://www.mxc.org', description:'Decentralized data network (DataHighway) using LPWAN and "Matchx" miners, pivoted to Moonchain (EVM L1).', tier:'tier2' });
add({ id:'weatherxm', symbol:'WXM', sector:'depin', coingeckoId:'weatherxm', cmcId:'23161', cmcSlug:'weatherxm', githubOrg:'weatherxm', githubRepo:'weatherxm/weatherxm', xHandle:'weatherxm', website:'https://weatherxm.com', description:'Community weather station network rewarding operators for hyperlocal meteorological data shared via WS1/WX1 devices.', tier:'tier2' });
add({ id:'wayru', symbol:'WAYRU', sector:'depin', coingeckoId:'wayru', cmcId:'24080', cmcSlug:'wayru', githubOrg:'Wayru-Network', githubRepo:'Wayru-Network/wayru', xHandle:'WayruNetwork', website:'https://wayru.io', description:'Decentralized WiFi hotspot network in Latin America, providing internet access while rewarding hotspot operators.', tier:'tier2' });
add({ id:'thingsix', symbol:'THIX', sector:'depin', coingeckoId:'thingsix', cmcId:'23967', cmcSlug:'thingsix', githubOrg:'ThingsIXfoundation', githubRepo:'ThingsIXfoundation/thingsix', xHandle:'ThingsIX', website:'https://thingsix.com', description:'Decentralized LoRaWAN coverage network that turns any compatible gateway into an incentivized Helium-like node.', tier:'tier2' });
add({ id:'iagon', symbol:'IAG', sector:'depin', coingeckoId:'iagon', cmcId:'4278', cmcSlug:'iagon', githubOrg:'iagonorg', githubRepo:'iagonorg/iagon', xHandle:'IagonOfficial', website:'https://iagon.com', description:'Decentralized storage and compute platform combining Cardano settlement with multi-cloud capacity aggregation.', tier:'tier2' });
add({ id:'sentinel', symbol:'DVPN', sector:'depin', coingeckoId:'sentinel', cmcId:'2643', cmcSlug:'sentinel', githubOrg:'sentinel-official', githubRepo:'sentinel-official/sentinel-core', xHandle:'Sentinel_co', website:'https://sentinel.co', description:'Decentralized VPN network using Tendermint/Cosmos SDK, providing bandwidth marketplace and private dVPN service.', tier:'tier2' });
add({ id:'pollen-mobile', symbol:'PCN', sector:'depin', coingeckoId:'pollen-2', cmcId:'22614', cmcSlug:'pollen-mobile', githubOrg:'pollen-mobile', githubRepo:'pollen-mobile/pollen', xHandle:'pollenmobile', website:'https://www.pollenmobile.io', description:'US nationwide decentralized 4G/5G mobile network using Helium-compatible hotspots and eSIM data plans.', tier:'tier2' });
add({ id:'geodnet', symbol:'GEOD', sector:'depin', coingeckoId:'geodnet', cmcId:'27723', cmcSlug:'geodnet', githubOrg:'geodnet', githubRepo:'geodnet/geodnet', xHandle:'geodnet', website:'https://www.geodnet.com', description:'Decentralized GNSS/RTK reference station network providing centimeter-accurate positioning to robots, drones and AVs.', tier:'tier2' });
add({ id:'grass', symbol:'GRASS', sector:'depin', sectors:['depin','ai'], coingeckoId:'grass', cmcId:'28456', cmcSlug:'grass', githubOrg:'getgrass-io', githubRepo:'getgrass-io/grass', xHandle:'get_grass', website:'https://www.grass.io', description:'Residential bandwidth DePIN that lets users monetize unused internet capacity by routing public web-scraping traffic for AI datasets.', tier:'tier1' });
add({ id:'peaq', symbol:'PEAQ', sector:'depin', coingeckoId:'peaq-2', cmcId:'29229', cmcSlug:'peaq-2', githubOrg:'peaqnetwork', githubRepo:'peaqnetwork/peaq-network-node', xHandle:'peaqnetwork', website:'https://www.peaq.xyz', description:'DePIN-focused L1 for machine economy, giving robots, EVs and IoT devices self-sovereign identity and on-chain revenue rails.', tier:'tier2' });
add({ id:'deeper-network', symbol:'DPR', sector:'depin', coingeckoId:'deeper-network', cmcId:'8914', cmcSlug:'deeper-network', githubOrg:'deeper-chain', githubRepo:'deeper-chain/deeper-chain', xHandle:'deeper_network', website:'https://deeper.network', description:'Decentralized VPN and bandwidth marketplace using dedicated hardware nodes called "Deeper Connect" devices.', tier:'tier2' });
add({ id:'nubila', symbol:'NUB', sector:'depin', coingeckoId:'nubila-network', cmcId:'29023', cmcSlug:'nubila-network', githubOrg:'nubila-network', githubRepo:'nubila-network/nubila', xHandle:'nubilanetwork', website:'https://www.nubila.com', description:'Decentralized environmental data network aggregating air-quality, weather and radiation readings from on-chain sensors.', tier:'tier2' });
add({ id:'powerpod', symbol:'POD', sector:'depin', coingeckoId:'powerpod', cmcId:'23433', cmcSlug:'powerpod', githubOrg:'PowerPod', githubRepo:'PowerPod/powerpod', xHandle:'PowerPodToken', website:'https://powerpod.net', description:'EV charging DePIN letting drivers locate, book and pay for chargers while station owners earn POD for uptime.', tier:'tier2' });

// =============================================================================
// AI (42) — artificial intelligence and compute projects
// =============================================================================
add({ id:'akash', symbol:'AKT', sector:'ai', sectors:['ai','depin'], coingeckoId:'akash-network', cmcId:'3861', cmcSlug:'akash-network', githubOrg:'akash-network', githubRepo:'akash-network/node', xHandle:'akashnet', website:'https://akash.network', description:'Decentralized marketplace for cloud compute that serves AI inference and traditional workloads via reverse auction on Cosmos.', tier:'tier1' });
add({ id:'the-graph', symbol:'GRT', sector:'ai', sectors:['ai','infrastructure'], coingeckoId:'the-graph', cmcId:'6719', cmcSlug:'the-graph', githubOrg:'graphprotocol', githubRepo:'graphprotocol/graph-node', xHandle:'graphprotocol', website:'https://thegraph.com', description:'Indexing protocol for querying blockchain data via GraphQL, with subgraphs and a payments layer (GRT) consumed by AI agents.', tier:'tier1' });
add({ id:'fetch-ai', symbol:'FET', sector:'ai', coingeckoId:'fetch-ai', cmcId:'3773', cmcSlug:'fetch', githubOrg:'fetchai', githubRepo:'fetchai/fetchd', xHandle:'Fetch_ai', website:'https://fetch.ai', description:'AI agent platform for autonomous economic agents, now part of the Artificial Superintelligence (ASI) Alliance with SingularityNET and Ocean.', tier:'tier1' });
add({ id:'singularitynet', symbol:'AGIX', sector:'ai', coingeckoId:'singularitynet', cmcId:'2424', cmcSlug:'singularitynet', githubOrg:'singularitynet', githubRepo:'singularitynet/snet-cli', xHandle:'SingularityNET', website:'https://singularitynet.io', description:'Decentralized AI marketplace that lets anyone publish, monetize and consume AI services through smart contracts.', tier:'tier1' });
add({ id:'ocean-protocol', symbol:'OCEAN', sector:'ai', sectors:['ai','infrastructure'], coingeckoId:'ocean-protocol', cmcId:'3911', cmcSlug:'ocean-protocol', githubOrg:'oceanprotocol', githubRepo:'oceanprotocol/contracts', xHandle:'oceanprotocol', website:'https://oceanprotocol.com', description:'Data exchange protocol unlocking privacy-preserving compute-to-data, used to feed AI models with tokenized datasets.', tier:'tier1' });
add({ id:'sahara-ai', symbol:'SAHARA', sector:'ai', coingeckoId:'sahara-ai', cmcId:'28401', cmcSlug:'sahara-ai', githubOrg:'SaharaLabsAI', githubRepo:'SaharaLabsAI/sahara-ai', xHandle:'SaharaAI', website:'https://www.sahara.ai', description:'Decentralized AI network for building, training and monetizing custom AI agents with verifiable provenance and data ownership.', tier:'tier1' });
add({ id:'origintrail', symbol:'TRAC', sector:'ai', sectors:['ai','infrastructure','rwa'], coingeckoId:'origintrail', cmcId:'2467', cmcSlug:'origintrail', githubOrg:'OriginTrail', githubRepo:'OriginTrail/ot-node', xHandle:'origin_trail', website:'https://origintrail.io', description:'Decentralized knowledge graph (DKG) providing trusted AI-ready data infrastructure for supply chains, RWA and enterprises.', tier:'tier1' });
add({ id:'story-protocol', symbol:'IP', sector:'ai', coingeckoId:'story-2', cmcId:'29147', cmcSlug:'story-2', githubOrg:'storyprotocol', githubRepo:'storyprotocol/typescript-sdk', xHandle:'StoryProtocol', website:'https://www.story.foundation', description:'IP-focused L1 building a programmable IP layer so that AI-generated content and human creations can register and license rights onchain.', tier:'tier1' });
add({ id:'allora', symbol:'ALLO', sector:'ai', coingeckoId:'allora', cmcId:'28907', cmcSlug:'allora', githubOrg:'allora-network', githubRepo:'allora-network/allora-chain', xHandle:'AlloraNetwork', website:'https://www.allora.network', description:'Self-improving decentralized AI network where ML models compete and aggregate predictions via on-chain reputation.', tier:'tier2' });
add({ id:'chaingpt', symbol:'CGPT', sector:'ai', coingeckoId:'chaingpt', cmcId:'24127', cmcSlug:'chaingpt', githubOrg:'ChainGPT-org', githubRepo:'ChainGPT-org/chain-gpt', xHandle:'Chain_GPT', website:'https://www.chaingpt.org', description:'AI-powered Web3 suite offering smart-contract audit, AI trading assistant, and an on-chain LLM gateway.', tier:'tier2' });
add({ id:'numerai', symbol:'NMR', sector:'ai', coingeckoId:'numeraire', cmcId:'1732', cmcSlug:'numeraire', githubOrg:'numerai', githubRepo:'numerai/tournament', xHandle:'numerai', website:'https://numer.ai', description:'Hedge-fund crowdsourced ML competition where data scientists stake NMR on stock-market predictions that drive the Numerai Meta Model.', tier:'tier1' });
add({ id:'aethir', symbol:'ATH', sector:'ai', sectors:['ai','depin','infrastructure'], coingeckoId:'aethir', cmcId:'29956', cmcSlug:'aethir', githubOrg:'AethirCloud', githubRepo:'AethirCloud/aethir', xHandle:'AethirCloud', website:'https://aethir.com', description:'Enterprise-grade GPU-as-a-service DePIN providing on-demand AI inference and cloud-gaming compute at lower cost than AWS.', tier:'tier1' });
add({ id:'nillion', symbol:'NIL', sector:'ai', sectors:['ai','infrastructure'], coingeckoId:'nillion', cmcId:'28333', cmcSlug:'nillion', githubOrg:'NillionNetwork', githubRepo:'NillionNetwork/nilchain', xHandle:'nillionnetwork', website:'https://nillion.com', description:'Blind-computation network using MPC and FHE so AI models can run on private data without ever seeing the plaintext.', tier:'tier1' });
add({ id:'golem', symbol:'GLM', sector:'ai', coingeckoId:'golem', cmcId:'2536', cmcSlug:'golem', githubOrg:'golemfactory', githubRepo:'golemfactory/golem', xHandle:'golemproject', website:'https://golem.network', description:'Peer-to-peer marketplace for spare CPU/GPU cycles, used to batch-render CGI and run LLM inference tasks.', tier:'tier1' });
add({ id:'gensyn', symbol:'AI', sector:'ai', coingeckoId:'gensyn', cmcId:'27092', cmcSlug:'gensyn', githubOrg:'GensynAI', githubRepo:'GensynAI/gensyn', xHandle:'gensynai', website:'https://www.gensyn.ai', description:'Decentralized ML compute protocol using RLNC proofs to verify that deep-learning model training was performed correctly.', tier:'tier1' });
add({ id:'iexec-rlc', symbol:'RLC', sector:'ai', sectors:['ai','infrastructure'], coingeckoId:'iexec-rlc', cmcId:'1637', cmcSlug:'iexec-rlc', githubOrg:'iExecBlockchainComputing', githubRepo:'iExecBlockchainComputing/iExec-WORKER', xHandle:'iEx_ec', website:'https://iex.ec', description:'Decentralized marketplace for off-chain computing (TEE) used to monetize datasets and AI inference via the RLC token.', tier:'tier1' });
add({ id:'autonolas', symbol:'OLAS', sector:'ai', coingeckoId:'autonolas', cmcId:'22154', cmcSlug:'autonolas', githubOrg:'valory-xyz', githubRepo:'valory-xyz/open-autonomy', xHandle:'autonolas', website:'https://olas.network', description:'Platform for building and operating autonomous services and co-owned AI agents with on-chain governance.', tier:'tier2' });
add({ id:'nosana', symbol:'NOS', sector:'ai', coingeckoId:'nosana', cmcId:'27075', cmcSlug:'nosana', githubOrg:'Nosana-Org', githubRepo:'Nosana-Org/nosana', xHandle:'nosana_ai', website:'https://nosana.com', description:'Solana-based GPU marketplace focused on AI inference workloads and CI/CD pipelines, paying GPU hosts in NOS.', tier:'tier2' });
add({ id:'theta', symbol:'THETA', sector:'ai', coingeckoId:'theta-token', cmcId:'2416', cmcSlug:'theta-token', githubOrg:'thetatoken', githubRepo:'thetatoken/theta-protocol-ledger', xHandle:'Theta_Network', website:'https://www.thetatoken.org', description:'Decentralized video delivery network with on-chain EdgeCloud AI services powered by TFUEL.', tier:'tier1' });
add({ id:'zero-gravity', symbol:'0G', sector:'ai', coingeckoId:'0g', cmcId:'28556', cmcSlug:'0g', githubOrg:'0g-project', githubRepo:'0g-project/0g', xHandle:'0G_labs', website:'https://0g.ai', description:'Modular AI chain offering high-throughput DA, decentralized storage and an inference engine for autonomous agents.', tier:'tier2' });
add({ id:'vana', symbol:'VANA', sector:'ai', coingeckoId:'vana', cmcId:'27922', cmcSlug:'vana', githubOrg:'vana-com', githubRepo:'vana-com/vana', xHandle:'vana', website:'https://www.vana.org', description:'User-owned data DAO network, enabling individuals to pool private data to train AI models and receive VANA rewards.', tier:'tier1' });
add({ id:'kaito', symbol:'KAITO', sector:'ai', coingeckoId:'kaito', cmcId:'28909', cmcSlug:'kaito', githubOrg:'kaito-ai', githubRepo:'kaito-ai/kaito', xHandle:'KaitoAI', website:'https://www.kaito.ai', description:'AI-powered crypto information platform with an attention graph and "InfoFi" data products for institutional and retail users.', tier:'tier1' });
add({ id:'virtuals-protocol', symbol:'VIRTUAL', sector:'ai', coingeckoId:'virtual-protocol', cmcId:'28190', cmcSlug:'virtual-protocol', githubOrg:'virtuals-protocol', githubRepo:'virtuals-protocol/virtuals-protocol', xHandle:'virtuals_io', website:'https://www.virtuals.io', description:'Base-based protocol for launching co-owned, autonomous AI agents with on-chain revenue and tokenized agent economies.', tier:'tier1' });
add({ id:'venice-token', symbol:'VVV', sector:'ai', coingeckoId:'venice-token', cmcId:'28421', cmcSlug:'venice-token', githubOrg:'veniceai', githubRepo:'veniceai/api', xHandle:'veniceai', website:'https://venice.ai', description:'Privacy-first AI inference API that routes prompts to open-source LLMs and pays VVV stakers for GPU bandwidth.', tier:'tier1' });
add({ id:'chainopera-ai', symbol:'COAI', sector:'ai', coingeckoId:'chainopera-ai', cmcId:'28911', cmcSlug:'chainopera-ai', githubOrg:'ChainOpera-AI', githubRepo:'ChainOpera-AI/chainopera', xHandle:'ChainOperaAI', website:'https://www.chainopera.ai', description:'AI-agent protocol that federates open-source models, on-chain reputation and revenue splits for collaborative agents.', tier:'tier2' });
add({ id:'sentient', symbol:'SENT', sector:'ai', coingeckoId:'sentient', cmcId:'29158', cmcSlug:'sentient', githubOrg:'sentient-agi', githubRepo:'sentient-agi/sentient', xHandle:'SentientAGI', website:'https://www.sentient.xyz', description:'Open-source AGI platform building community-owned AI agents and a loyalty layer branded Loyal AI.', tier:'tier1' });
add({ id:'lagrange', symbol:'LA', sector:'ai', sectors:['ai','infrastructure'], coingeckoId:'lagrange', cmcId:'28843', cmcSlug:'lagrange', githubOrg:'Lagrange-Labs', githubRepo:'Lagrange-Labs/lagrange', xHandle:'lagrangelabs', website:'https://www.lagrange.dev', description:'ZK-proving network that generates proofs of LLM inference, enabling trustless off-chain AI for on-chain applications.', tier:'tier1' });
add({ id:'aioz-network', symbol:'AIOZ', sector:'ai', sectors:['ai','depin','infrastructure'], coingeckoId:'aioz-network', cmcId:'5104', cmcSlug:'aioz-network', githubOrg:'aioznetwork', githubRepo:'aioznetwork/aioz', xHandle:'AiozNetwork', website:'https://aioz.network', description:'DePIN for AI compute, storage and streaming with full Web3 content delivery and AI inference services.', tier:'tier1' });
add({ id:'carv', symbol:'CARV', sector:'ai', sectors:['ai','gaming','infrastructure'], coingeckoId:'carv', cmcId:'26500', cmcSlug:'carv', githubOrg:'carv-protocol', githubRepo:'carv-protocol/carv', xHandle:'carv_official', website:'https://carv.io', description:'Modular identity and data layer that turns gaming/AI user behavior into verifiable credentials for agents and apps.', tier:'tier1' });
add({ id:'eigenlayer', symbol:'EIGEN', sector:'ai', sectors:['ai','infrastructure','defi'], coingeckoId:'eigenlayer', cmcId:'24733', cmcSlug:'eigenlayer', githubOrg:'Layr-Labs', githubRepo:'Layr-Labs/eigenlayer-contracts', xHandle:'eigenlayer', website:'https://www.eigenlayer.xyz', description:'Restaking protocol that lets ETH stakers secure new services (AVSs) including AI coprocessors and verifiable compute networks.', tier:'tier1' });
add({ id:'sapien', symbol:'SAPIEN', sector:'ai', coingeckoId:'sapien-2', cmcId:'26105', cmcSlug:'sapien-2', githubOrg:'SapienNetwork', githubRepo:'SapienNetwork/sapien', xHandle:'sapien', website:'https://www.sapien.io', description:'Decentralized RLHF data labeling network where humans train frontier AI models in exchange for SAPIEN rewards.', tier:'tier2' });
add({ id:'cortex', symbol:'CTXC', sector:'ai', coingeckoId:'cortex', cmcId:'2638', cmcSlug:'cortex', githubOrg:'CortexFoundation', githubRepo:'CortexFoundation/cortex', xHandle:'Cortex_AI', website:'https://www.cortexlabs.ai', description:'EVM-compatible L1 that natively executes AI models (ONNX) on chain, enabling smart contracts to call inference directly.', tier:'tier2' });
add({ id:'alethea-ai', symbol:'ALI', sector:'ai', coingeckoId:'alethea-artificial-liquid-intelligence-token', cmcId:'23538', cmcSlug:'alethea-artificial-liquid-intelligence-token', githubOrg:'alethea-ai', githubRepo:'alethea-ai/alethea', xHandle:'AletheaAI', website:'https://alethea.ai', description:'Generative AI protocol powering iNFTs, combining character AI, TTS and on-chain provenance for intelligent digital beings.', tier:'tier2' });
add({ id:'botto', symbol:'BOTTO', sector:'ai', coingeckoId:'botto', cmcId:'24050', cmcSlug:'botto', githubOrg:'bottoproject', githubRepo:'bottoproject/botto', xHandle:'bottoproject', website:'https://www.botto.com', description:'Decentralized generative artist AI whose aesthetic is steered weekly by BOTTO stakers; the produced artworks are auctioned as NFTs.', tier:'tier2' });
add({ id:'synesis-one', symbol:'SNS', sector:'ai', coingeckoId:'synesis-one', cmcId:'9485', cmcSlug:'synesis-one', githubOrg:'SynesisOne', githubRepo:'SynesisOne/synesis-one', xHandle:'SynesisOne', website:'https://synesis.one', description:'Crowdsourced NLP data labeling DAO where users earn SNS for training AI models in 30+ languages.', tier:'tier2' });
add({ id:'netmind', symbol:'NMT', sector:'ai', coingeckoId:'netmind-token', cmcId:'23133', cmcSlug:'netmind-token', githubOrg:'netmind-ai', githubRepo:'netmind-ai/netmind', xHandle:'NetMindAI', website:'https://netmind.ai', description:'Decentralized AI training and inference network with an "AI worker" marketplace paid in NMT for unused GPU cycles.', tier:'tier2' });
add({ id:'paal-ai', symbol:'PAAL', sector:'ai', coingeckoId:'paal-ai', cmcId:'24013', cmcSlug:'paal-ai', githubOrg:'paal-ai', githubRepo:'paal-ai/paal-ai', xHandle:'PaalAI', website:'https://www.paal.ai', description:'AI agent platform combining X/Telegram bots, knowledge bases and on-chain analytics for retail crypto users.', tier:'tier2' });
add({ id:'morpheusai', symbol:'MOR', sector:'ai', coingeckoId:'morpheusai', cmcId:'26712', cmcSlug:'morpheusai', githubOrg:'MorpheusAIs', githubRepo:'MorpheusAIs/Morpheus', xHandle:'MorpheusAI', website:'https://mor.org', description:'Smart-agent network for Web3 with a permissionless LLM gateway and a pay-per-inference MOR token economy.', tier:'tier2' });

console.log('After AI:', PROJECTS.length);
fs.writeFileSync('/workspace/code/_progress.json', JSON.stringify({count: PROJECTS.length, sectors: PROJECTS.reduce((a,p)=>{a[p.sector]=(a[p.sector]||0)+1;return a;},{})}, null, 2));
console.log('Sectors:', PROJECTS.reduce((a,p)=>{a[p.sector]=(a[p.sector]||0)+1;return a;},{}));

module.exports = { PROJECTS };
