#!/usr/bin/env node
/** PAYD Intelligence V2: fill only missing market fields via CoinMarketCap keyless API. */
const fs=require('fs'),path=require('path');
const ROOT=process.env.PAYD_ROOT||process.cwd();
const FILE=path.join(ROOT,'public','data','projects_enriched.json');
const TMP=FILE+'.tmp';
const BASE='https://pro-api.coinmarketcap.com/public-api/v3/cryptocurrency/quotes/latest';
const valid=v=>v!==null&&v!==undefined&&!(typeof v==='number'&&Number.isNaN(v));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function rows(data){if(Array.isArray(data?.data))return data.data;if(data?.data&&typeof data.data==='object')return Object.values(data.data).flatMap(v=>Array.isArray(v)?v:[v]);return Array.isArray(data)?data:[]}
function usd(row){const q=row?.quote;if(!q)return null;if(q.USD)return q.USD;if(Array.isArray(q))return q.find(x=>x?.symbol==='USD')||q[0]||null;return null}
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'PAYD-Intelligence/cmc-fallback'},signal:c.signal});const text=await r.text();let d=null;try{d=JSON.parse(text)}catch(_){}if(!r.ok)throw new Error(`HTTP ${r.status}: ${d?.status?.error_message||d?.message||text.slice(0,160)}`);return d}finally{clearTimeout(t)}}
function needs(p){const m=p?.market||{};return !valid(m.price_usd)||!valid(m.market_cap_usd)||!valid(m.fdv_usd)||!valid(m.volume_24h_usd)}
function set(p,key,val,row,now){if(!valid(val)||valid(p.market?.[key]))return false;p.market=p.market&&typeof p.market==='object'?p.market:{};p.market_sources=p.market_sources&&typeof p.market_sources==='object'?p.market_sources:{};p.market[key]=val;p.market_sources[key]={source:'CoinMarketCap',source_id:String(row.id),retrieved_at:now,status:'AVAILABLE'};return true}
function apply(p,row){const q=usd(row);if(!q)return 0;const now=new Date().toISOString();let n=0;for(const [k,v] of Object.entries({price_usd:q.price,market_cap_usd:q.market_cap,fdv_usd:q.fully_diluted_market_cap,volume_24h_usd:q.volume_24h,change_24h_pct:q.percent_change_24h,change_7d_pct:q.percent_change_7d,change_30d_pct:q.percent_change_30d,circulating_supply:row.circulating_supply,total_supply:row.total_supply,max_supply:row.max_supply,market_cap_rank:row.cmc_rank,last_updated:row.last_updated||q.last_updated}))if(set(p,k,v,row,now))n++;if(n){p.market_provenance={...(p.market_provenance||{}),fallback_source:'CoinMarketCap',cmc_id:String(row.id),cmc_retrieved_at:now,fallback_status:'AVAILABLE'}}return n}
async function main(){const doc=JSON.parse(fs.readFileSync(FILE,'utf8'));if(!doc||!Array.isArray(doc.projects))throw new Error('projects_enriched.json must contain { projects: [...] }');const candidates=doc.projects.filter(p=>needs(p)&&p.cmcId);const ids=[...new Set(candidates.map(p=>String(p.cmcId)))];const map=new Map();for(let i=0;i<ids.length;i+=250){const batch=ids.slice(i,i+250);try{for(const r of rows(await get(`${BASE}?id=${encodeURIComponent(batch.join(','))}&convert=USD`)))if(r?.id!=null)map.set(String(r.id),r)}catch(e){console.warn('[PAYD][CMC]',e.message)}if(i+250<ids.length)await sleep(500)}let updated=0,fields=0;for(const p of candidates){const r=map.get(String(p.cmcId));if(!r)continue;const n=apply(p,r);if(n){updated++;fields+=n}}const unresolved=doc.projects.filter(needs).map(p=>({id:p.id,symbol:p.symbol,sector:p.sector,coingeckoId:p.coingeckoId||null,cmcId:p.cmcId||null,reason:p.cmcId?'CMC_NO_DATA':'MISSING_CMC_ID'}));doc.schema_version='payd-intelligence-v2.3';doc.dataset_version=new Date().toISOString();doc.generated_at=new Date().toISOString();doc.market_fallback_provider='CoinMarketCap';doc.market_cmc_candidates=candidates.length;doc.market_cmc_updated=updated;doc.market_cmc_fields_filled=fields;doc.market_unresolved_after_fallback=unresolved;fs.writeFileSync(TMP,JSON.stringify(doc,null,2)+'\n');JSON.parse(fs.readFileSync(TMP,'utf8'));fs.renameSync(TMP,FILE);console.log(JSON.stringify({ok:true,candidates:candidates.length,cmc_rows:map.size,updated,fields_filled:fields,unresolved:unresolved.length,output:FILE},null,2))}
main().catch(e=>{try{if(fs.existsSync(TMP))fs.unlinkSync(TMP)}catch(_){}console.error('[PAYD CMC fallback] FATAL:',e.message);process.exit(1)});
