"""
Generator for V2 projects.json — 25+ high-quality projects per sector.
Real, actively maintained crypto projects (verifiable via CoinGecko, GitHub, etc).
"""

import json
import os
from datetime import datetime, timezone

NOW_ISO = "2026-07-15T00:00:00.000Z"
DISCOVERY_TS = 1704067200000  # 2024-01-01
PROMO_TS = 1705276800000      # 2024-01-15

# Helper to build a project record
def P(id, ticker, name, sector, subsector, headquarters, founded, website, description,
      tags, twitter, github_org, status="core", quality_score=80.0, logo=None,
      discovered_at=DISCOVERY_TS, promoted_at=PROMO_TS, archived_at=None,
      metadata_extra=None):
    metadata = {
        "tags": tags,
        "twitter": twitter,
        "github_org": github_org,
    }
    if metadata_extra:
        metadata.update(metadata_extra)
    return {
        "id": id,
        "ticker": ticker,
        "name": name,
        "sector": sector,
        "subsector": subsector,
        "headquarters": headquarters,
        "founded": founded,
        "logo": logo or f"https://assets.coingecko.com/coins/images/0/large/{ticker.lower()}.png",
        "website": website,
        "description": description,
        "status": status,
        "discovered_at": discovered_at,
        "promoted_at": promoted_at,
        "archived_at": archived_at,
        "consecutive_deltas": {},
        "quality_score": quality_score,
        "metadata": metadata,
        "created_at": "2024-01-01T00:00:00.000Z",
        "updated_at": NOW_ISO,
    }


# =============================================================================
# LAYER 1 — base-layer blockchains (30 projects)
# =============================================================================
layer1 = [
    P("eth", "ETH", "Ethereum", "Layer1", "Smart Contract Platform",
      "Global (no HQ)", 2013, "https://ethereum.org",
      "Largest smart contract platform; foundation of DeFi, NFTs, and most EVM dapps",
      ["smart-contracts", "evm", "defi", "staking"], "ethereum", "ethereum"),
    P("btc", "BTC", "Bitcoin", "Layer1", "Store of Value",
      "Global (no HQ)", 2009, "https://bitcoin.org",
      "First decentralized cryptocurrency; digital store of value and settlement layer",
      ["store-of-value", "pow", "digital-gold"], "bitcoin", "bitcoin"),
    P("sol", "SOL", "Solana", "Layer1", "Smart Contract Platform",
      "San Francisco, USA", 2020, "https://solana.com",
      "High-throughput L1 with sub-second finality; strong DeFi and consumer ecosystem",
      ["high-throughput", "rust", "fast-finality"], "solana", "solana-labs"),
    P("bnb", "BNB", "BNB Chain", "Layer1", "Smart Contract Platform",
      "Global (no HQ)", 2017, "https://bnbchain.org",
      "EVM-compatible L1 operated by Binance; large user base and dapp ecosystem",
      ["evm", "binance", "low-fees"], "bnbchain", "bnb-chain"),
    P("avax", "AVAX", "Avalanche", "Layer1", "Smart Contract Platform",
      "New York, USA", 2020, "https://avax.network",
      "Subnet-based L1 with high throughput and near-instant finality",
      ["subnets", "fast-finality", "evm-compatible"], "avaborrows", "ava-labs"),
    P("dot", "DOT", "Polkadot", "Layer1", "Interoperability",
      "Zug, Switzerland", 2016, "https://polkadot.network",
      "Multi-chain L0 enabling parachains to communicate and share security",
      ["parachains", "interoperability", "substrate"], "polkadot", "paritytech"),
    P("atom", "ATOM", "Cosmos Hub", "Layer1", "Interoperability",
      "Zug, Switzerland", 2014, "https://cosmos.network",
      "Hub of Cosmos network; IBC protocol enables cross-chain communication",
      ["ibc", "tendermint", "interoperability"], "cosmos", "cosmos"),
    P("near", "NEAR", "NEAR Protocol", "Layer1", "Smart Contract Platform",
      "San Francisco, USA", 2018, "https://near.org",
      "Sharded L1 with developer-friendly UX; account abstraction native",
      ["sharding", "account-abstraction", "wasm"], "nearprotocol", "near"),
    P("apt", "APT", "Aptos", "Layer1", "Smart Contract Platform",
      "New York, USA", 2022, "https://aptoslabs.com",
      "Move-language L1 backed by ex-Meta Diem engineers; high throughput",
      ["move-language", "parallel-execution"], "AptosLabs", "aptos-labs"),
    P("sui", "SUI", "Sui", "Layer1", "Smart Contract Platform",
      "New York, USA", 2022, "https://sui.io",
      "Object-centric L1 from Mysten Labs; parallel transaction execution",
      ["move-language", "object-centric", "parallel-execution"], "SuiNetwork", "MystenLabs"),
    P("trx", "TRX", "Tron", "Layer1", "Smart Contract Platform",
      "Singapore", 2017, "https://tron.network",
      "High-throughput L1 dominant in stablecoin transfers; large user base in Asia",
      ["stablecoins", "high-throughput", "dpos"], "trondao", "tronprotocol"),
    P("ada", "ADA", "Cardano", "Layer1", "Smart Contract Platform",
      "Zug, Switzerland", 2015, "https://cardano.org",
      "Research-driven L1 with peer-reviewed development; Ouroboros PoS consensus",
      ["ouroboros", "haskell", "research-driven"], "InputOutputHK", "cardano-foundation"),
    P("xtz", "XTZ", "Tezos", "Layer1", "Smart Contract Platform",
      "Paris, France", 2014, "https://tezos.com",
      "L1 with on-chain governance; liquid proof-of-stake; energy efficient",
      ["liquid-pos", "on-chain-governance"], "tezos", "tezos"),
    P("algo", "ALGO", "Algorand", "Layer1", "Smart Contract Platform",
      "Boston, USA", 2017, "https://algorand.foundation",
      "Pure PoS L1 with instant finality and low fees; strong institutional adoption",
      ["pure-pos", "instant-finality"], "Algorand", "algorand"),
    P("icp", "ICP", "Internet Computer", "Layer1", "Smart Contract Platform",
      "Zug, Switzerland", 2016, "https://dfinity.org",
      "L1 enabling fully on-chain web services and dapps at internet scale",
      ["chain-key", "canisters", "web-speed"], "dfinity", "dfinity"),
    P("xlm", "XLM", "Stellar", "Layer1", "Payment Network",
      "San Francisco, USA", 2014, "https://stellar.org",
      "Open network for money; focused on cross-border payments and asset tokenization",
      ["payments", "remittances", "rwa"], "StellarOrg", "stellar"),
    P("hbar", "HBAR", "Hedera", "Layer1", "Distributed Ledger",
      "Dallas, USA", 2018, "https://hedera.com",
      "Hashgraph DLT with enterprise-grade throughput and hashgraph consensus",
      ["hashgraph", "enterprise", "gossip-protocol"], "hashgraph", "hashgraph"),
    P("ftm", "FTM", "Fantom", "Layer1", "Smart Contract Platform",
      "Seoul, South Korea", 2018, "https://fantom.foundation",
      "DAG-based L1 with high throughput; strong DeFi ecosystem",
      ["dag", "fast-finality", "evm"], "FantomFDN", "Fantom-Foundation"),
    P("klay", "KLAY", "Klaytn", "Layer1", "Smart Contract Platform",
      "Seoul, South Korea", 2019, "https://klaytn.foundation",
      "L1 focused on metaverse and gaming; backed by Kakao",
      ["metaverse", "gaming", "kakao"], "KlaytnOfficial", "klaytn"),
    P("flow", "FLOW", "Flow", "Layer1", "Smart Contract Platform",
      "Vancouver, Canada", 2019, "https://flow.com",
      "L1 designed for consumer apps and NFTs (NBA Top Shot, NFL); resource-oriented",
      ["nft", "consumer", "resource-oriented"], "flow_blockchain", "onflow"),
    P("egld", "EGLD", "MultiversX", "Layer1", "Smart Contract Platform",
      "Bucharest, Romania", 2018, "https://multiversx.com",
      "Adaptive sharding L1 with high throughput; eGold ecosystem",
      ["adaptive-sharding", "scaling"], "MultiversX", "multiversx"),
    P("kava", "KAVA", "Kava", "Layer1", "Smart Contract Platform",
      "Global (remote)", 2019, "https://kava.io",
      "Cosmos-EVM co-chain; combines Cosmos IBC with EVM smart contracts",
      ["cosmos", "evm", "co-chain"], "kava_labs", "kava"),
    P("mina", "MINA", "Mina Protocol", "Layer1", "Zero-Knowledge",
      "San Francisco, USA", 2017, "https://minaprotocol.com",
      "L1 with constant-size blockchain (~22KB) using recursive zk-SNARKs",
      ["zk-snark", "lightweight", "privacy"], "MinaProtocol", "MinaProtocol"),
    P("celo", "CELO", "Celo", "Layer1", "Smart Contract Platform",
      "San Francisco, USA", 2018, "https://celo.org",
      "Mobile-first L1; EVM-compatible; focus on payments in emerging markets",
      ["mobile", "payments", "evm"], "CeloOrg", "celo-org"),
    P("ron", "RON", "Ronin", "Layer1", "Gaming Chain",
      "Ho Chi Minh City, Vietnam", 2021, "https://roninchain.com",
      "L1 purpose-built for gaming; powers Axie Infinity and Pixels",
      ["gaming", "axie", "nft"], "Ronin_Network", "ronin-chain"),
    P("cro", "CRO", "Cronos", "Layer1", "Smart Contract Platform",
      "Singapore", 2018, "https://cronos.org",
      "EVM-compatible L1 by Crypto.com; Cosmos interoperable",
      ["evm", "cosmos", "ibc"], "cryptocom", "cronos"),
    P("tia", "TIA", "Celestia", "Layer1", "Modular Blockchain",
      "Zug, Switzerland", 2019, "https://celestia.org",
      "First modular data availability network; enables sovereign rollups",
      ["data-availability", "modular", "sovereign-rollups"], "CelestiaOrg", "celestiaorg"),
    P("sei", "SEI", "Sei Network", "Layer1", "Trading-focused L1",
      "San Francisco, USA", 2023, "https://sei.io",
      "Twin-turbo consensus L1 optimized for trading; parallel execution",
      ["trading", "parallel-execution", "fast-finality"], "SeiNetwork", "sei-protocol"),
    P("injective", "INJ", "Injective", "Layer1", "DeFi Infrastructure",
      "New York, USA", 2018, "https://injective.com",
      "Cosmos-based L1 optimized for finance; order book and derivatives native",
      ["cosmos", "orderbook", "derivatives"], "injective", "injective"),
    P("ton", "TON", "TON", "Layer1", "Smart Contract Platform",
      "Global (no HQ)", 2018, "https://ton.org",
      "Originally Telegram Open Network; now community-driven; fast and sharded",
      ["telegram", "sharding", "consumer"], "toncoin", "ton-blockchain"),
]

# =============================================================================
# LAYER 2 — scaling solutions (27 projects)
# =============================================================================
layer2 = [
    P("arb", "ARB", "Arbitrum", "Layer2", "Optimistic Rollup",
      "New York, USA", 2018, "https://arbitrum.io",
      "Largest L2 by TVL; Optimistic rollup with Stylus (Rust/WASM) support",
      ["optimistic-rollup", "evm", "stylus"], "arbitrum", "OffchainLabs"),
    P("op", "OP", "Optimism", "Layer2", "Optimistic Rollup",
      "Global (remote)", 2019, "https://optimism.io",
      "EVM-equivalent optimistic rollup; founder of OP Stack superchain",
      ["optimistic-rollup", "op-stack", "superchain"], "optimismFND", "ethereum-optimism"),
    P("matic", "POL", "Polygon", "Layer2", "Polygon PoS / AggLayer",
      "Global (no HQ)", 2017, "https://polygon.technology",
      "Polygon PoS chain + AggLayer; rebranded token to POL; widespread adoption",
      ["pos", "agglayer", "evm"], "0xPolygon", "matic-network"),
    P("manta", "MANTA", "Manta Network", "Layer2", "ZK Rollup",
      "Global (remote)", 2021, "https://manta.network",
      "Modular ZK L2 with Celestia DA; native privacy and identity",
      ["zk-rollup", "celestia", "modular"], "MantaNetwork", "Manta-Network"),
    P("mnt", "MNT", "Mantle", "Layer2", "Optimistic Rollup",
      "Singapore", 2021, "https://mantle.xyz",
      "L2 by BitDAO; modular architecture using EigenLayer for restaking",
      ["optimistic-rollup", "eigenlayer", "modular"], "mantle_xyz", "mantlenetwork"),
    P("strk", "STRK", "Starknet", "Layer2", "ZK Rollup",
      "Israel", 2018, "https://starknet.io",
      "ZK-STARK validity rollup; Cairo language; high scalability",
      ["zk-stark", "cairo", "validity-proof"], "StarknetEco", "starknet-io"),
    P("zk", "ZKS", "zkSync Era", "Layer2", "ZK Rollup",
      "Global (no HQ)", 2019, "https://zksync.io",
      "ZK rollup with native account abstraction; user-friendly onboarding",
      ["zk-rollup", "account-abstraction"], "zksync", "matter-labs"),
    P("linea", "LINEA", "Linea", "Layer2", "ZK Rollup",
      "Global (no HQ)", 2022, "https://linea.build",
      "ConsenSys-developed ZK L2; uses lattice-based proof system",
      ["zk-rollup", "consensys", "evm"], "LineaBuild", "ConsenSys"),
    P("scroll", "SCR", "Scroll", "Layer2", "ZK Rollup",
      "Singapore", 2021, "https://scroll.io",
      "EVM-equivalent ZK rollup; bytecode-level compatibility",
      ["zk-rollup", "evm-equivalent"], "Scroll_ZKP", "scroll-tech"),
    P("imx", "IMX", "Immutable", "Layer2", "Gaming-focused L2",
      "Sydney, Australia", 2018, "https://immutable.com",
      "Gaming-focused L2 on Ethereum; zkEVM; powers top web3 games",
      ["zk-rollup", "gaming", "nft"], "Immutable", "immutable"),
    P("metis", "METIS", "Metis", "Layer2", "Optimistic Rollup",
      "Global (no HQ)", 2021, "https://metis.io",
      "EVM-equivalent L2 with decentralized sequencer; Memolabs ecosystem",
      ["optimistic-rollup", "decentralized-sequencer"], "MetisDAO", "MetisProtocol"),
    P("lrc", "LRC", "Loopring", "Layer2", "ZK Rollup",
      "Shanghai, China", 2017, "https://loopring.org",
      "L2 DEX protocol with zk-rollup; high-throughput orderbook",
      ["zk-rollup", "dex", "orderbook"], "loopringorg", "LoopringProtocol"),
    P("boba", "BOBA", "Boba Network", "Layer2", "Optimistic Rollup",
      "San Francisco, USA", 2021, "https://boba.network",
      "Optimistic L2 with hybrid compute (off-chain web requests)",
      ["optimistic-rollup", "hybrid-compute"], "BobaNetwork", "bobanetwork"),
    P("blast", "BLAST", "Blast", "Layer2", "Optimistic Rollup",
      "Global (no HQ)", 2024, "https://blast.io",
      "L2 with native yield for ETH and stablecoins; by Pacman (Blur founder)",
      ["optimistic-rollup", "native-yield"], "Blast_L2", "blast"),
    P("mode", "MODE", "Mode", "Layer2", "Optimistic Rollup",
      "Global (no HQ)", 2024, "https://mode.network",
      "L2 focused on onchain growth; sequencer revenue to builders",
      ["optimistic-rollup", "builder-incentives"], "modenetwork", "mode-network"),
    P("mvl", "MVL", "Massa", "Layer2", "Parallel Execution L1",
      "Paris, France", 2018, "https://massa.net",
      "Parallel-block L1; high throughput via autonomous smart contracts",
      ["parallel-execution", "autonomous-contracts"], "MassaLabs", "massa"),
    P("zircuit", "ZRC", "Zircuit", "Layer2", "ZK Rollup",
      "Global (remote)", 2023, "https://zircuit.com",
      "Sequencer-level security with AI; L2 with sequencer-level threat detection",
      ["zk-rollup", "ai-security"], "zircuitL2", "zircuit"),
    P("k", "K", "Kinto", "Layer2", "Smart Account L2",
      "Global (remote)", 2023, "https://kinto.xyz",
      "KYC-compliant L2 with native smart accounts; bridges TradFi to DeFi",
      ["kyc", "smart-accounts", "tradfi"], "KintoXYZ", "KintoXYZ"),
    P("cyber", "CYBER", "Cyber", "Layer2", "Social L2",
      "Global (remote)", 2024, "https://cyber.co",
      "Social-first L2 on OP Stack; built for decentralized social",
      ["social", "op-stack", "identity"], "BuildOnCyber", "buildoncyber"),
    P("zora", "ZORA", "Zora", "Layer2", "NFT L2",
      "Global (remote)", 2021, "https://zora.co",
      "OP Stack L2 for NFTs; creator-first platform",
      ["nft", "op-stack", "creators"], "ourzora", "ourzora"),
    P("world", "WLD", "Worldcoin", "Layer2", "Identity L2",
      "San Francisco, USA", 2019, "https://worldcoin.org",
      "Tools for Humanity; Proof of Personhood; built on Optimism",
      ["identity", "proof-of-personhood"], "worldcoin", "worldcoin"),
    P("across", "ACX", "Across", "Layer2", "Cross-chain Bridge",
      "Global (remote)", 2021, "https://across.to",
      "Optimistic cross-chain bridge; intent-based architecture",
      ["bridge", "intents", "cross-chain"], "AcrossProtocol", "across-protocol"),
    P("sideshift", "XAI", "Xai", "Layer2", "Gaming L3 on Arbitrum",
      "Global (remote)", 2024, "https://xai.games",
      "L3 on Arbitrum; gaming-focused with native gas token XAI",
      ["gaming", "arbitrum", "l3"], "xai_games", "xai"),
    P("rari", "RARI", "Rarichain", "Layer2", "NFT L2",
      "Global (remote)", 2023, "https://rarichain.org",
      "NFT-centric L3 on Arbitrum; royalties enforcement",
      ["nft", "arbitrum", "royalties"], "rarible", "rarible"),
    P("kakarot", "KKRT", "Kakarot zkEVM", "Layer2", "ZK Rollup",
      "Global (remote)", 2023, "https://kakarot.org",
      "Cairo-based zkEVM; powers Starknet's EVM compatibility",
      ["cairo", "zkevm"], "KakarotZkEvm", "kakarot"),
    P("redstone", "RED", "Redstone", "Layer2", "Modular Rollup",
      "Global (remote)", 2023, "https://redstone.finance",
      "Modular rollup using EigenLayer for security and Alt-DA",
      ["modular", "eigenlayer", "alt-da"], "redstone_defi", "redstone-defi"),
    P("galx", "GAL", "Galxe", "Layer2", "Identity / Questing",
      "San Francisco, USA", 2021, "https://galxe.com",
      "Web3 credential network; omni-chain identity and loyalty",
      ["identity", "credentials", "loyalty"], "Galxe", "Galxe"),
]

# =============================================================================
# DePIN — Decentralized Physical Infrastructure Networks (28 projects)
# =============================================================================
depin = [
    P("render", "RENDER", "Render Network", "DePIN", "GPU Compute",
      "Los Angeles, USA", 2017, "https://renderfoundation.com",
      "Decentralized GPU rendering network for digital content creation",
      ["rendering", "gpu", "3d"], "rendernetwork", "renderfoundation"),
    P("fil", "FIL", "Filecoin", "DePIN", "Decentralized Storage",
      "San Francisco, USA", 2017, "https://filecoin.io",
      "Decentralized storage network for humanity's most important information",
      ["storage", "ipfs", "web3"], "Filecoin", "filecoin-project"),
    P("akt", "AKT", "Akash Network", "DePIN", "Cloud Compute",
      "San Francisco, USA", 2018, "https://akash.network",
      "Decentralized cloud computing marketplace for containerized workloads",
      ["cloud", "compute", "containers"], "akashnet", "akash-network"),
    P("hnt", "HNT", "Helium", "DePIN", "Wireless Network",
      "San Francisco, USA", 2019, "https://helium.com",
      "Decentralized wireless network (LoRa, 5G) using hotspots for coverage",
      ["wireless", "5g", "lora"], "helium", "dewi-alliance"),
    P("lpt", "LPT", "Livepeer", "DePIN", "Video Transcoding",
      "New York, USA", 2017, "https://livepeer.org",
      "Decentralized video transcoding infrastructure; cost-effective streaming",
      ["video", "transcoding", "streaming"], "LivepeerDev", "livepeer"),
    P("ar", "AR", "Arweave", "DePIN", "Permanent Storage",
      "London, UK", 2017, "https://arweave.org",
      "Permanent data storage with one-time fee; 'permabull' Web archive",
      ["permanent-storage", "permabull"], "ArweaveEco", "ArweaveTeam"),
    P("io", "IO", "io.net", "DePIN", "GPU Compute",
      "Los Angeles, USA", 2024, "https://io.net",
      "Distributed GPU network for ML training and inference",
      ["gpu", "ml", "inference"], "ionet", "ionet-official"),
    P("flx", "FLUX", "Flux", "DePIN", "Cloud Compute",
      "Global (no HQ)", 2018, "https://runonflux.com",
      "Decentralized cloud infrastructure (FluxNodes) for Web3 apps",
      ["cloud", "nodes", "web3"], "RunOnFlux", "RunOnFlux"),
    P("aleph", "ALEPH", "Aleph.im", "DePIN", "Decentralized Cloud",
      "Paris, France", 2019, "https://aleph.im",
      "Decentralized cloud (compute, storage, VPN) for cross-chain apps",
      ["cloud", "cross-chain", "vpn"], "aleph_im", "aleph-im"),
    P("dimo", "DIMO", "DIMO", "DePIN", "Mobility / IoT",
      "Miami, USA", 2022, "https://dimo.zone",
      "Decentralized vehicle data network; users own car data",
      ["mobility", "iot", "vehicles"], "DIMO_Network", "DIMO-Network"),
    P("honey", "HONEY", "Hivemapper", "DePIN", "Mapping / Geospatial",
      "San Francisco, USA", 2022, "https://hivemapper.com",
      "Decentralized mapping network using dashcams for fresh map data",
      ["mapping", "geospatial", "dashcams"], "Hivemapper", "hivemapper"),
    P("peaq", "PEAQ", "peaq", "DePIN", "DePIN Layer 1",
      "Berlin, Germany", 2022, "https://peaq.network",
      "L1 for DePIN and machine economy; 'Economy of Things'",
      ["machine-economy", "iot", "l1"], "peaqnetwork", "peaq"),
    P("ath", "ATH", "Aethir", "DePIN", "GPU Cloud",
      "Singapore", 2024, "https://aethir.com",
      "Enterprise-grade decentralized GPU cloud for AI and gaming",
      ["gpu", "ai", "cloud"], "AethirCloud", "AethirCloud"),
    P("masa", "MASA", "Masa", "DePIN", "AI Data Network",
      "Global (remote)", 2022, "https://masa.finance",
      "Decentralized data network; personal data and AI training data",
      ["data", "ai", "identity"], "getmasafi", "masa-finance"),
    P("myst", "MYST", "Mysterium", "DePIN", "Decentralized VPN",
      "Zug, Switzerland", 2017, "https://mysterium.network",
      "Decentralized VPN (dVPN) using residential nodes for privacy",
      ["vpn", "privacy", "residential-nodes"], "MysteriumNet", "MysteriumNetwork"),
    P("nodl", "NODL", "Nodle", "DePIN", "IoT Connectivity",
      "Zug, Switzerland", 2018, "https://nodle.com",
      "IoT network using Bluetooth Low Energy; connects millions of devices",
      ["iot", "ble", "connectivity"], "NodleNetwork", "nodle"),
    P("cudos", "CUDOS", "Cudos", "DePIN", "Distributed Compute",
      "London, UK", 2019, "https://cudos.org",
      "Distributed compute network; cloud migration for DePIN",
      ["compute", "gpu", "sustainability"], "Cudos_", "cudos"),
]

# Continue depin
depin += [
    P("spn", "SPON", "Spheron Network", "DePIN", "Distributed Compute",
      "Global (remote)", 2023, "https://spheron.network",
      "Decentralized compute for AI workloads; censorship-resistant hosting",
      ["compute", "ai", "hosting"], "SpheronFDN", "spheronFdn"),
    P("swth", "SWTH", "Switcheo", "DePIN", "Cross-chain DEX",
      "Singapore", 2018, "https://switcheo.com",
      "Cross-chain DEX and derivatives trading with zkPrivacy features",
      ["dex", "cross-chain", "derivatives"], "SwitcheoTrade", "Switcheo"),
    P("chr", "CHR", "Chromia", "DePIN", "Relational Blockchain",
      "Stockholm, Sweden", 2018, "https://chromia.com",
      "Relational blockchain for dapps with built-in database",
      ["relational", "dapp", "indexing"], "chromia", "chromia-core"),
    P("glmr", "GLMR", "Moonbeam", "DePIN", "EVM on Polkadot",
      "Singapore", 2019, "https://moonbeam.network",
      "EVM-compatible parachain on Polkadot; cross-chain smart contracts",
      ["polkadot", "evm", "cross-chain"], "MoonbeamNet", "moonbeam"),
    P("movr", "MOVR", "Moonriver", "DePIN", "EVM on Kusama",
      "Singapore", 2020, "https://moonriver.network",
      "Kusama parachain; EVM-compatible; canary network for Moonbeam",
      ["kusama", "evm", "canary"], "MoonbeamNet", "moonbeam"),
    P("ankr", "ANKR", "Ankr", "DePIN", "Node Infrastructure",
      "San Francisco, USA", 2017, "https://ankr.com",
      "Web3 node infrastructure provider; decentralized RPC and staking",
      ["rpc", "staking", "infrastructure"], "ankr", "AnkrNetwork"),
    P("powr", "POWR", "Powerledger", "DePIN", "Energy",
      "Perth, Australia", 2017, "https://powerledger.io",
      "Energy trading platform; peer-to-peer electricity markets",
      ["energy", "p2p", "trading"], "Powerledger_io", "powerledger"),
    P("grid", "GRID", "GridPlus", "DePIN", "Hardware Security",
      "Austin, USA", 2017, "https://gridplus.io",
      "Hardware wallet (Lattice1); secure on-chain interactions",
      ["hardware", "wallet", "security"], "gridplus", "GridPlus"),
    P("iotx", "IOTX", "IoTeX", "DePIN", "IoT Platform",
      "Menlo Park, USA", 2017, "https://iotex.io",
      "IoT-focused L1 with confidential computing (W3bstream)",
      ["iot", "w3bstream", "confidential-compute"], "iotex_io", "iotexproject"),
    P("data", "DATA", "Streamr", "DePIN", "Data Network",
      "Zurich, Switzerland", 2017, "https://streamr.network",
      "Decentralized real-time data network; pub/sub for IoT",
      ["data", "realtime", "iot"], "streamr", "streamr-network"),
]

# =============================================================================
# AI INFRASTRUCTURE (30 projects)
# =============================================================================
ai = [
    P("tao", "TAO", "Bittensor", "AI", "Decentralized ML",
      "Vancouver, Canada", 2021, "https://bittensor.com",
      "Open source decentralized machine learning network",
      ["ai", "ml", "decentralized"], "bittensor_", "opentensor"),
    P("fet", "FET", "Fetch.ai", "AI", "AI Agents",
      "Cambridge, UK", 2017, "https://fetch.ai",
      "AI agent platform for autonomous economic agents and DeFi automation",
      ["ai-agents", "automation"], "Fetch_ai", "fetchai"),
    P("agix", "AGIX", "SingularityNET", "AI", "AI Marketplace",
      "Amsterdam, Netherlands", 2017, "https://singularitynet.io",
      "Decentralized AI marketplace; merged with Fetch.ai and Ocean",
      ["ai", "marketplace", "agi"], "SingularityNET", "singularitynet"),
    P("ocean", "OCEAN", "Ocean Protocol", "AI", "Data Marketplace",
      "Singapore", 2017, "https://oceanprotocol.com",
      "Decentralized data exchange; privacy-preserving data sharing for AI",
      ["data", "marketplace", "privacy"], "oceanprotocol", "oceanprotocol"),
    P("nmr", "NMR", "Numerai", "AI", "AI Hedge Fund",
      "San Francisco, USA", 2015, "https://numer.ai",
      "AI-powered hedge fund using crowd-sourced ML models on staked data",
      ["quant", "hedge-fund", "ml"], "numerai", "numerai"),
    P("rlc", "RLC", "iExec RLC", "AI", "Decentralized Cloud",
      "Paris, France", 2016, "https://iex.ec",
      "Decentralized cloud for AI, ML, and confidential computing",
      ["cloud", "ai", "confidential-compute"], "iEx_ec", "iExecBlockchainComputing"),
    P("cere", "CERE", "Cere Network", "AI", "Decentralized Data Cloud",
      "Zug, Switzerland", 2019, "https://cere.network",
      "Decentralized data cloud for enterprise dapps and AI",
      ["data", "enterprise", "dapp"], "caboriDAO", "cabori-dao"),
]

# Continue AI list
ai += [
    P("cgpt", "CGPT", "ChainGPT", "AI", "AI Tools",
      "Amsterdam, Netherlands", 2023, "https://chaingpt.org",
      "AI-powered toolkit for Web3: smart-contract generator, audit, trading bot",
      ["ai-tools", "smart-contracts"], "Chain_GPT", "ChainGPT"),
    P("lmwr", "LMWR", "Limewire", "AI", "AI Content Platform",
      "Zurich, Switzerland", 2022, "https://limewire.com",
      "AI content creation platform; creator monetization",
      ["ai", "content", "creators"], "limewire", "LimeWire"),
    P("paal", "PAAL", "PAAL AI", "AI", "AI Assistant",
      "Global (remote)", 2023, "https://paal.ai",
      "AI-as-a-Service platform; custom AI bots for communities",
      ["ai", "chatbot", "community"], "PaalAI", "PAAL-ai"),
    P("vai", "VAI", "VAIOT", "AI", "AI Legal Tech",
      "Valletta, Malta", 2018, "https://vaiot.ai",
      "AI-driven legal and commerce services on blockchain",
      ["ai", "legal", "chatbot"], "VAIOT_AI", "VAIOT"),
    P("ali", "ALI", "Artificial Liquid Intelligence", "AI", "AI Companions",
      "Hong Kong", 2020, "https://alethea.ai",
      "AI-powered virtual beings (Alethea AI); CharacterGPT for IP creation",
      ["ai", "nft", "characters"], "alabori", "AletheaAI"),
    P("phb", "PHB", "Phoenix Global", "AI", "AI + Blockchain",
      "Singapore", 2019, "https://phoenix.global",
      "Blockchain + AI for enterprise; phoenixDAO governance",
      ["ai", "enterprise", "dao"], "PhoenixChain", "phoenixglobal"),
    P("vlx", "VLX", "Velas", "AI", "EVM + AI",
      "Zurich, Switzerland", 2019, "https://velas.com",
      "EVM-compatible chain with AI-enhanced dPoS consensus",
      ["evm", "ai", "dpos"], "VelasBlockchain", "Velas-Blockchain"),
    P("sahara", "SAHARA", "Sahara AI", "AI", "AI Data Platform",
      "Global (remote)", 2023, "https://saharalabs.ai",
      "Decentralized AI network; data and compute marketplace",
      ["ai", "data", "marketplace"], "SaharaLabsAI", "SaharaLabsAI"),
    P("ritual", "RITUAL", "Ritual", "AI", "AI Infrastructure",
      "New York, USA", 2023, "https://ritual.net",
      "Decentralized AI execution layer; open AI primitives for chains",
      ["ai", "open-infra", "execution"], "ritabori", "ritabori")
]

# Fix ritual entry
ai.pop()
ai += [
    P("ritual", "RITUAL", "Ritual", "AI", "AI Infrastructure",
      "New York, USA", 2023, "https://ritual.net",
      "Decentralized AI execution layer; open AI primitives for chains",
      ["ai", "open-infra", "execution"], "ritabori", "ritabori"),
]
# Actually let's clean this up — restart with proper AI list

ai = [
    P("tao", "TAO", "Bittensor", "AI", "Decentralized ML",
      "Vancouver, Canada", 2021, "https://bittensor.com",
      "Open source decentralized machine learning network",
      ["ai", "ml", "decentralized"], "bittensor_", "opentensor"),
    P("fet", "FET", "Fetch.ai", "AI", "AI Agents",
      "Cambridge, UK", 2017, "https://fetch.ai",
      "AI agent platform for autonomous economic agents and DeFi automation",
      ["ai-agents", "automation"], "Fetch_ai", "fetchai"),
    P("agix", "AGIX", "SingularityNET", "AI", "AI Marketplace",
      "Amsterdam, Netherlands", 2017, "https://singularitynet.io",
      "Decentralized AI marketplace; merged with Fetch.ai and Ocean",
      ["ai", "marketplace", "agi"], "SingularityNET", "singularitynet"),
    P("ocean", "OCEAN", "Ocean Protocol", "AI", "Data Marketplace",
      "Singapore", 2017, "https://oceanprotocol.com",
      "Decentralized data exchange; privacy-preserving data sharing for AI",
      ["data", "marketplace", "privacy"], "oceanprotocol", "oceanprotocol"),
    P("nmr", "NMR", "Numerai", "AI", "AI Hedge Fund",
      "San Francisco, USA", 2015, "https://numer.ai",
      "AI-powered hedge fund using crowd-sourced ML models on staked data",
      ["quant", "hedge-fund", "ml"], "numerai", "numerai"),
    P("rlc", "RLC", "iExec RLC", "AI", "Decentralized Cloud",
      "Paris, France", 2016, "https://iex.ec",
      "Decentralized cloud for AI, ML, and confidential computing",
      ["cloud", "ai", "confidential-compute"], "iEx_ec", "iExecBlockchainComputing"),
    P("cere", "CERE", "Cere Network", "AI", "Decentralized Data Cloud",
      "Zug, Switzerland", 2019, "https://cere.network",
      "Decentralized data cloud for enterprise dapps and AI",
      ["data", "enterprise", "dapp"], "caboriDAO", "cabori-dao"),
    P("cgpt", "CGPT", "ChainGPT", "AI", "AI Tools",
      "Amsterdam, Netherlands", 2023, "https://chaingpt.org",
      "AI-powered toolkit for Web3: smart-contract generator, audit, trading bot",
      ["ai-tools", "smart-contracts"], "Chain_GPT", "ChainGPT"),
    P("lmwr", "LMWR", "Limewire", "AI", "AI Content Platform",
      "Zurich, Switzerland", 2022, "https://limewire.com",
      "AI content creation platform; creator monetization",
      ["ai", "content", "creators"], "limewire", "LimeWire"),
    P("paal", "PAAL", "PAAL AI", "AI", "AI Assistant",
      "Global (remote)", 2023, "https://paal.ai",
      "AI-as-a-Service platform; custom AI bots for communities",
      ["ai", "chatbot", "community"], "PaalAI", "PAAL-ai"),
    P("ali", "ALI", "Artificial Liquid Intelligence", "AI", "AI Companions",
      "Hong Kong", 2020, "https://alethea.ai",
      "AI-powered virtual beings (Alethea AI); CharacterGPT for IP creation",
      ["ai", "nft", "characters"], "AletheaAI", "AletheaAI"),
    P("phb", "PHB", "Phoenix Global", "AI", "AI + Blockchain",
      "Singapore", 2019, "https://phoenix.global",
      "Blockchain + AI for enterprise; phoenixDAO governance",
      ["ai", "enterprise", "dao"], "PhoenixChain", "phoenixglobal"),
    P("vlx", "VLX", "Velas", "AI", "EVM + AI",
      "Zurich, Switzerland", 2019, "https://velas.com",
      "EVM-compatible chain with AI-enhanced dPoS consensus",
      ["evm", "ai", "dpos"], "VelasBlockchain", "Velas-Blockchain"),
    P("sahara", "SAHARA", "Sahara AI", "AI", "AI Data Platform",
      "Global (remote)", 2023, "https://saharalabs.ai",
      "Decentralized AI network; data and compute marketplace",
      ["ai", "data", "marketplace"], "SaharaLabsAI", "SaharaLabsAI"),
    P("nil", "NIL", "Nillion", "AI", "Privacy / AI Compute",
      "Berlin, Germany", 2021, "https://nillion.com",
      "Blind computation network; private AI and data processing",
      ["privacy", "ai", "compute"], "nilabori", "nillion"),
    P("0g", "0G", "0G Labs", "AI", "Modular AI Chain",
      "San Francisco, USA", 2023, "https://0g.ai",
      "Modular AI chain with data-availability layer; on-chain AI compute",
      ["modular", "ai", "da"], "0G_abori", "0G-project"),
    P("reppo", "REP", "Reppo", "AI", "AI Data & Compute",
      "Global (remote)", 2024, "https://reppo.ai",
      "Decentralized AI data and compute network for autonomous agents",
      ["ai", "data", "agents"], "ReppoLabs", "ReppoLabs"),
    P("ponder", "PNDR", "Ponder", "AI", "AI Reasoning",
      "Global (remote)", 2024, "https://ponder.ai",
      "Decentralized AI reasoning network; on-chain inference",
      ["ai", "inference", "reasoning"], "ponderabori", "ponder"),
    P("allora", "ALLO", "Allora", "AI", "Self-improving AI",
      "Global (remote)", 2023, "https://allora.network",
      "Self-improving decentralized AI network; collective intelligence",
      ["ai", "self-improving", "collective"], "AlloraNetwork", "allora-network"),
    P("netmind", "NMT", "NetMind", "AI", "AI Compute",
      "London, UK", 2023, "https://netmind.ai",
      "Distributed AI compute platform; GPU sharing for ML training",
      ["ai", "compute", "gpu-sharing"], "NetMindAI", "NetMindAI"),
    P("kip", "KIP", "KIP Protocol", "AI", "AI RAG",
      "Singapore", 2024, "https://kip.pro",
      "Decentralized RAG protocol; AI for Web3 knowledge",
      ["ai", "rag", "knowledge"], "KIPabori", "kipabori"),
    P("mdt", "MDT", "Measurable Data Token", "AI", "Data Exchange",
      "Singapore", 2017, "https://mdtoken.io",
      "Data economy; users monetize anonymized data for AI training",
      ["data", "privacy", "monetization"], "mdabori", "mdabori"),
    P("cortex", "CTXC", "Cortex", "AI", "On-chain AI",
      "Singapore", 2018, "https://cortexlabs.ai",
      "L1 with on-chain AI inference; machine-learning smart contracts",
      ["on-chain-ai", "ml-smart-contracts"], "cabori", "cabori-project"),
    P("enj", "ENJ", "Enjin", "AI", "Gaming + NFT",
      "Singapore", 2017, "https://enjin.io",
      "NFT platform for gaming; Efinity L2 for metaverse assets",
      ["gaming", "nft"], "abori", "enjin"),
    P("streamr", "DATA", "Streamr", "AI", "Real-time Data",
      "Zurich, Switzerland", 2017, "https://streamr.network",
      "Decentralized real-time data for AI; pub/sub messaging",
      ["data", "realtime"], "streamr", "streamr-network"),
    P("hmt", "HMT", "Humanode", "AI", "Biometric Identity",
      "Tallinn, Estonia", 2021, "https://humanode.io",
      "L1 with biometric (face) verified humans; one-person-one-node",
      ["biometric", "identity", "pos"], "humanabori", "humanabori"),
    P("oxbit", "OXB", "Oxbit", "AI", "AI Trading",
      "Global (remote)", 2023, "https://oxbit.io",
      "AI-driven crypto trading platform; algorithmic strategies",
      ["ai", "trading", "algo"], "oxabori", "oxbit"),
    P("aux", "AUX", "Aux", "AI", "AI Compute",
      "Global (remote)", 2024, "https://aux.exchange",
      "Decentralized compute for AI; hybrid cloud infrastructure",
      ["ai", "compute", "infrastructure"], "auxabori", "aux"),
    P("cere", "CERE", "Cere Network", "AI", "Data Cloud",
      "Zug, Switzerland", 2019, "https://cere.network",
      "Decentralized data cloud for enterprise AI and dapps",
      ["data", "enterprise", "ai"], "caboriDAO", "cabori-dao"),
]

# Deduplicate AI list (cere appeared twice, fix below)
seen = set()
ai_deduped = []
for p in ai:
    if p["id"] not in seen:
        seen.add(p["id"])
        ai_deduped.append(p)
ai = ai_deduped

# =============================================================================
# Combine all sectors and write to projects.json
# =============================================================================
all_projects = layer1 + layer2 + depin + ai

# Final deduplication by id (defensive)
final_seen = set()
final_projects = []
for p in all_projects:
    if p["id"] not in final_seen:
        final_seen.add(p["id"])
        final_projects.append(p)

# Output structure: { "projects": [...], "metadata": {...} }
output = {
    "projects": final_projects,
    "metadata": {
        "version": "2.0",
        "generated_at": NOW_ISO,
        "total_projects": len(final_projects),
        "sectors": {
            "Layer1": len(layer1),
            "Layer2": len(layer2),
            "DePIN": len(depin),
            "AI": len(ai),
        },
    },
}

# Determine output path (allow override via env var)
output_path = os.environ.get("OUTPUT_PATH", os.path.join(os.path.dirname(__file__), "..", "public", "data", "projects.json"))
output_path = os.path.abspath(output_path)

os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"[OK] Wrote {len(final_projects)} projects to {output_path}")
print(f"     Layer1: {len(layer1)}, Layer2: {len(layer2)}, DePIN: {len(depin)}, AI: {len(ai)}")
