/* =================================================================
   PAYD Intelligence V2 — Provider-Specific Identifier Mappings
   ----------------------------------------------------------------
   Каждый проект имеет РАЗДЕЛЬНЫЕ идентификаторы для каждого провайдера:

   identifiers: {
     coingecko:  "arbitrum"             (CoinGecko API)
     coinmarketcap: "11841"              (CMC API)
     defillama_chain:  "Arbitrum"        (DefiLlama /v2/chains name)
     defillama_protocol: "arbitrum-bridge" (DefiLlama /protocol/ slug, если есть)
     defillama_dex: null                  (DefiLlama /summary/dexs/ slug)
     github: ["OffchainLabs/nitro", ...]  (GitHub repos)
     x: "arbitrum"                        (X/Twitter handle)
     website: "https://arbitrum.io"
   }

   ВАЖНО: разные провайдеры используют разные slug-имена!
   - DefiLlama chain использует "Arbitrum" (заглавная)
   - DefiLlama protocol использует "arbitrum" (lowercase) или вообще другой slug
   - CoinGecko использует "arbitrum" (lowercase)
   ================================================================= */

const PROVIDER_IDS = {
    // ────────── L1 CHAINS ──────────
    'ethereum': {
        coingecko: 'ethereum',
        coinmarketcap: '1027',
        defillama_chain: 'Ethereum',
        defillama_protocol: 'ethereum',
        github: ['ethereum/go-ethereum', 'ethereum/research'],
        website: 'https://ethereum.org',
    },
    'bitcoin': {
        coingecko: 'bitcoin',
        coinmarketcap: '1',
        defillama_chain: 'Bitcoin',
        defillama_protocol: null,
        github: ['bitcoin/bitcoin'],
        website: 'https://bitcoin.org',
    },
    'solana': {
        coingecko: 'solana',
        coinmarketcap: '5426',
        defillama_chain: 'Solana',
        defillama_protocol: 'solana',
        github: ['solana-labs/solana', 'anza-xyz/solana-sdk'],
        website: 'https://solana.com',
    },
    'cardano': {
        coingecko: 'cardano',
        coinmarketcap: '2010',
        defillama_chain: 'Cardano',
        defillama_protocol: 'cardano',
        github: ['input-output-hk/cardano-node'],
        website: 'https://cardano.org',
    },
    'tron': {
        coingecko: 'tron',
        coinmarketcap: '1958',
        defillama_chain: 'Tron',
        defillama_protocol: 'tron',
        github: ['tronprotocol/java-tron'],
        website: 'https://tron.network',
    },
    'polkadot': {
        coingecko: 'polkadot',
        coinmarketcap: '6636',
        defillama_chain: 'Polkadot',
        defillama_protocol: 'polkadot',
        github: ['paritytech/polkadot-sdk'],
        website: 'https://polkadot.network',
    },
    'avalanche-2': {
        coingecko: 'avalanche-2',
        coinmarketcap: '5805',
        defillama_chain: 'Avalanche',
        defillama_protocol: 'avalanche',
        github: ['ava-labs/avalanchego'],
        website: 'https://www.avax.network',
    },
    'cosmos': {
        coingecko: 'cosmos',
        coinmarketcap: '3794',
        defillama_chain: 'Cosmos Hub',
        defillama_protocol: 'cosmos',
        github: ['cosmos/cosmos-sdk'],
        website: 'https://cosmos.network',
    },
    'near': {
        coingecko: 'near',
        coinmarketcap: '6535',
        defillama_chain: 'Near',
        defillama_protocol: 'near',
        github: ['near/nearcore'],
        website: 'https://near.org',
    },
    'sui': {
        coingecko: 'sui',
        coinmarketcap: '20947',
        defillama_chain: 'Sui',
        defillama_protocol: 'sui',
        github: ['MystenLabs/sui'],
        website: 'https://sui.io',
    },
    'aptos': {
        coingecko: 'aptos',
        coinmarketcap: '21794',
        defillama_chain: 'Aptos',
        defillama_protocol: 'aptos',
        github: ['aptos-labs/aptos-core'],
        website: 'https://aptosfoundation.org',
    },
    'tezos': {
        coingecko: 'tezos',
        coinmarketcap: '2011',
        defillama_chain: 'Tezos',
        defillama_protocol: 'tezos',
        github: ['tezos/tezos'],
        website: 'https://tezos.com',
    },
    'monad': {
        coingecko: 'monad',
        coinmarketcap: '22617',
        defillama_chain: 'Monad',
        defillama_protocol: 'monad',
        github: ['category-labs/monad'],
        website: 'https://monad.xyz',
    },
    'celestia': {
        coingecko: 'celestia',
        coinmarketcap: '22861',
        defillama_chain: 'Celestia',
        defillama_protocol: 'celestia',
        github: ['celestiaorg/celestia-core'],
        website: 'https://celestia.org',
    },
    'fantom': {
        coingecko: 'fantom',
        coinmarketcap: '3513',
        defillama_chain: 'Fantom',
        defillama_protocol: 'fantom',
        github: ['Fantom-Foundation/go-opera'],
        website: 'https://fantom.foundation',
    },
    'flow': {
        coingecko: 'flow',
        coinmarketcap: '4558',
        defillama_chain: 'Flow',
        defillama_protocol: 'flow',
        github: ['onflow/flow-go'],
        website: 'https://flow.com',
    },
    'internet-computer': {
        coingecko: 'internet-computer',
        coinmarketcap: '8916',
        defillama_chain: 'Internet Computer',
        defillama_protocol: 'internet-computer',
        github: ['dfinity/ic'],
        website: 'https://internetcomputer.org',
    },
    'hedera-hashgraph': {
        coingecko: 'hedera-hashgraph',
        coinmarketcap: '4642',
        defillama_chain: 'Hedera',
        defillama_protocol: 'hedera',
        github: ['hashgraph/hedera-services'],
        website: 'https://hedera.com',
    },
    'iota': {
        coingecko: 'iota',
        coinmarketcap: '1720',
        defillama_chain: 'IOTA',
        defillama_protocol: 'iota',
        github: ['iotaledger/hornet'],
        website: 'https://www.iota.org',
    },
    'dogecoin': {
        coingecko: 'dogecoin',
        coinmarketcap: '74',
        defillama_chain: 'Dogecoin',
        defillama_protocol: 'dogecoin',
        github: ['dogecoin/dogecoin'],
        website: 'https://dogecoin.com',
    },
    'filecoin': {
        coingecko: 'filecoin',
        coinmarketcap: '2280',
        defillama_chain: 'Filecoin',
        defillama_protocol: 'filecoin',
        github: ['filecoin-project/lotus'],
        website: 'https://filecoin.io',
    },
    'flare': {
        coingecko: 'flare',
        coinmarketcap: '4172',
        defillama_chain: 'Flare',
        defillama_protocol: 'flare',
        github: ['flare-foundation/flare'],
        website: 'https://flare.network',
    },
    'berachain': {
        coingecko: 'berachain',
        coinmarketcap: '24647',
        defillama_chain: 'Berachain',
        defillama_protocol: 'berachain',
        github: ['berachain/berachain'],
        website: 'https://www.berachain.com',
    },
    'sonic-3': {
        coingecko: 'sonic-3',
        coinmarketcap: null,
        defillama_chain: 'Sonic',
        defillama_protocol: 'sonic',
        github: ['SonicSvm/sonic'],
        website: 'https://www.sonic.game',
    },

    // ────────── L2 CHAINS ──────────
    'arbitrum': {
        coingecko: 'arbitrum',
        coinmarketcap: '11841',
        defillama_chain: 'Arbitrum',
        defillama_protocol: 'arbitrum-bridge',  // есть bridge protocol в DefiLlama
        github: ['OffchainLabs/nitro', 'OffchainLabs/arbitrum'],
        website: 'https://arbitrum.io',
    },
    'optimism': {
        coingecko: 'optimism',
        coinmarketcap: '11840',
        defillama_chain: 'Optimism',
        defillama_protocol: 'optimism-bridge',
        github: ['ethereum-optimism/optimism'],
        website: 'https://www.optimism.io',
    },
    'polygon': {
        coingecko: 'matic-network',
        coinmarketcap: '3890',
        defillama_chain: 'Polygon',
        defillama_protocol: 'polygon-bridge',
        github: ['maticnetwork/bor', 'maticnetwork/Polygon-Edge'],
        website: 'https://polygon.technology',
    },
    'base': {
        coingecko: 'base',
        coinmarketcap: '27716',
        defillama_chain: 'Base',
        defillama_protocol: 'base',
        github: ['base-org/contracts', 'base-org/web'],
        website: 'https://base.org',
    },
    'mantle': {
        coingecko: 'mantle',
        coinmarketcap: '27075',
        defillama_chain: 'Mantle',
        defillama_protocol: 'mantle',
        github: ['mantlenetworkio/mantle'],
        website: 'https://www.mantle.xyz',
    },
    'linea': {
        coingecko: 'linea',
        coinmarketcap: null,
        defillama_chain: 'Linea',
        defillama_protocol: 'linea',
        github: ['Consensys/linea-tracer'],
        website: 'https://linea.build',
    },
    'scroll': {
        coingecko: 'scroll',
        coinmarketcap: '26994',
        defillama_chain: 'Scroll',
        defillama_protocol: 'scroll',
        github: ['scroll-tech/scroll'],
        website: 'https://scroll.io',
    },
    'starknet': {
        coingecko: 'starknet',
        coinmarketcap: '22691',
        defillama_chain: 'Starknet',
        defillama_protocol: 'starknet',
        github: ['starkware-libs/starknet-payments'],
        website: 'https://www.starknet.io',
    },
    'zksync': {
        coingecko: 'zksync',
        coinmarketcap: '24091',
        defillama_chain: 'zkSync Era',
        defillama_protocol: 'zksync-era',
        github: ['matter-labs/zksync-era'],
        website: 'https://zksync.io',
    },
    'manta-network': {
        coingecko: 'manta-network',
        coinmarketcap: '21755',
        defillama_chain: 'Manta',
        defillama_protocol: 'manta',
        github: ['Manta-Network/manta'],
        website: 'https://manta.network',
    },
    'metis': {
        coingecko: 'metis-token',
        coinmarketcap: '9640',
        defillama_chain: 'Metis',
        defillama_protocol: 'metis',
        github: ['MetisProtocol/metis-sdk'],
        website: 'https://www.metis.io',
    },
    'celo': {
        coingecko: 'celo',
        coinmarketcap: '5567',
        defillama_chain: 'Celo',
        defillama_protocol: 'celo',
        github: ['celo-org/celo-blockchain'],
        website: 'https://celo.org',
    },
    'gnosis': {
        coingecko: 'gnosis',
        coinmarketcap: '1659',
        defillama_chain: 'Gnosis',
        defillama_protocol: 'gnosis-dao',
        github: ['gnosis/gnosis-chain'],
        website: 'https://www.gnosis.io',
    },
    'moonbeam': {
        coingecko: 'moonbeam',
        coinmarketcap: '6836',
        defillama_chain: 'Moonbeam',
        defillama_protocol: 'moonbeam',
        github: ['moonbeam-foundation/moonbeam'],
        website: 'https://moonbeam.network',
    },
    'astar': {
        coingecko: 'astar',
        coinmarketcap: '16389',
        defillama_chain: 'Astar',
        defillama_protocol: 'astar-dapps-staking',
        github: ['AstarNetwork/Astar'],
        website: 'https://astar.network',
    },
    'cyber': {
        coingecko: 'cyberconnect',
        coinmarketcap: '22914',
        defillama_chain: 'Cyber',
        defillama_protocol: 'cyber',
        github: ['cybercongress/cyber'],
        website: 'https://cyber.co',
    },
    'ord': {
        coingecko: 'ord',
        coinmarketcap: null,
        defillama_chain: null,
        defillama_protocol: null,
        github: [],
        website: 'https://ord.io',
    },
    'oasys': {
        coingecko: 'oasys',
        coinmarketcap: '21846',
        defillama_chain: 'Oasys',
        defillama_protocol: 'oasys',
        github: ['oasys-gmbh/oasys-genesis-contract'],
        website: 'https://www.oasys.games',
    },
    'zetachain': {
        coingecko: 'zeta-chain',
        coinmarketcap: '21259',
        defillama_chain: 'ZetaChain',
        defillama_protocol: 'zetachain',
        github: ['zeta-chain/protocol'],
        website: 'https://www.zetachain.com',
    },
    'zircuit': {
        coingecko: 'zircuit',
        coinmarketcap: null,
        defillama_chain: 'Zircuit',
        defillama_protocol: 'zircuit',
        github: ['zircuit-labs/zircuit'],
        website: 'https://www.zircuit.com',
    },
    'concordium': {
        coingecko: 'concordium',
        coinmarketcap: '22742',
        defillama_chain: 'Concordium',
        defillama_protocol: 'concordium',
        github: ['Concordium/concordium-node'],
        website: 'https://www.concordium.com',
    },

    // ────────── DEFI / DEX PROTOCOLS ──────────
    'uniswap': {
        coingecko: 'uniswap',
        coinmarketcap: '7083',
        defillama_chain: null,
        defillama_protocol: 'uniswap',
        defillama_dex: 'uniswap',
        github: ['Uniswap/v3-core', 'Uniswap/v4-core'],
        website: 'https://uniswap.org',
    },
    'aave': {
        coingecko: 'aave',
        coinmarketcap: '7278',
        defillama_chain: null,
        defillama_protocol: 'aave',
        github: ['aave/aave-v3-core'],
        website: 'https://aave.com',
    },
    'lido-dao': {
        coingecko: 'lido-dao',
        coinmarketcap: '8000',
        defillama_chain: null,
        defillama_protocol: 'lido',
        github: ['lidofinance/lido-dao'],
        website: 'https://lido.fi',
    },
    'pendle': {
        coingecko: 'pendle',
        coinmarketcap: '9481',
        defillama_chain: null,
        defillama_protocol: 'pendle',
        github: ['pendle-finance/pendle-core'],
        website: 'https://www.pendle.finance',
    },
    'balancer': {
        coingecko: 'balancer',
        coinmarketcap: '5728',
        defillama_chain: null,
        defillama_protocol: 'balancer',
        defillama_dex: 'balancer',
        github: ['balancer/balancer-core'],
        website: 'https://balancer.fi',
    },
    '1inch': {
        coingecko: '1inch',
        coinmarketcap: '8104',
        defillama_chain: null,
        defillama_protocol: '1inch',
        defillama_dex: '1inch',
        github: ['1inch/1inch-sdk'],
        website: 'https://1inch.io',
    },
    'convex-finance': {
        coingecko: 'convex-finance',
        coinmarketcap: '9903',
        defillama_chain: null,
        defillama_protocol: 'convex-finance',
        github: ['conic-finance/convex-platform'],
        website: 'https://www.convexfinance.com',
    },
    'beefy': {
        coingecko: 'beefy',
        coinmarketcap: '7311',
        defillama_chain: null,
        defillama_protocol: 'beefy',
        github: ['beefyfinance/beefy-contracts'],
        website: 'https://beefy.com',
    },
    'quickswap': {
        coingecko: 'quickswap',
        coinmarketcap: '10118',
        defillama_chain: null,
        defillama_protocol: 'quickswap',
        defillama_dex: 'quickswap',
        github: ['QuickSwap/quick-perps'],
        website: 'https://quickswap.exchange',
    },
    'thorchain': {
        coingecko: 'thorchain',
        coinmarketcap: '4157',
        defillama_chain: null,
        defillama_protocol: 'thorchain',
        defillama_dex: 'thorchain',
        github: ['thorchain/thornode'],
        website: 'https://thorchain.org',
    },
    'synthetix': {
        coingecko: 'synthetix',
        coinmarketcap: '2586',
        defillama_chain: null,
        defillama_protocol: 'synthetix',
        github: ['Synthetixio/synthetix-v3'],
        website: 'https://synthetix.io',
    },
    'stargate': {
        coingecko: 'stargate',
        coinmarketcap: '18934',
        defillama_chain: null,
        defillama_protocol: 'stargate',
        github: ['stargate-protocol/stargate-v2'],
        website: 'https://stargate.finance',
    },
    'sushi': {
        coingecko: 'sushi',
        coinmarketcap: '6758',
        defillama_chain: null,
        defillama_protocol: 'sushiswap',
        defillama_dex: 'sushiswap',
        github: ['sushiswap/sushiswap'],
        website: 'https://www.sushi.com',
    },
    'synapse': {
        coingecko: 'synapse-2',
        coinmarketcap: '8391',
        defillama_chain: null,
        defillama_protocol: 'synapse',
        github: ['synapse-protocol/synapse-contracts'],
        website: 'https://synapseprotocol.com',
    },
    'curve-dao-token': {
        coingecko: 'curve-dao-token',
        coinmarketcap: '6538',
        defillama_chain: null,
        defillama_protocol: 'curve',
        defillama_dex: 'curve',
        github: ['curvefi/curve-contract'],
        website: 'https://curve.fi',
    },
    'maker': {
        coingecko: 'maker',
        coinmarketcap: '1518',
        defillama_chain: null,
        defillama_protocol: 'sky',
        github: ['sky-ecosystem/makerdao-spellbook'],
        website: 'https://sky.money',
    },
    'loopring': {
        coingecko: 'loopring',
        coinmarketcap: '1934',
        defillama_chain: null,
        defillama_protocol: 'loopring',
        github: ['Loopring/protocols'],
        website: 'https://loopring.org',
    },
    'orderly': {
        coingecko: 'orderly-network',
        coinmarketcap: '22826',
        defillama_chain: null,
        defillama_protocol: 'orderly-network',
        github: ['OrderlyNetwork/js-sdk'],
        website: 'https://orderly.network',
    },
    'dydx': {
        coingecko: 'dydx',
        coinmarketcap: '11156',
        defillama_chain: null,
        defillama_protocol: 'dydx',
        defillama_dex: 'dydx',
        github: ['dydxprotocol/v4-chain'],
        website: 'https://dydx.exchange',
    },

    // ────────── INFRASTRUCTURE ──────────
    'chainlink': {
        coingecko: 'chainlink',
        coinmarketcap: '1975',
        defillama_chain: null,
        defillama_protocol: 'chainlink',
        github: ['smartcontractkit/chainlink'],
        website: 'https://chain.link',
    },
    'the-graph': {
        coingecko: 'the-graph',
        coinmarketcap: '6719',
        defillama_chain: null,
        defillama_protocol: 'the-graph',
        github: ['graphprotocol/graph-node'],
        website: 'https://thegraph.com',
    },
    'arweave': {
        coingecko: 'arweave',
        coinmarketcap: '5632',
        defillama_chain: null,
        defillama_protocol: 'arweave',
        github: ['ArweaveTeam/arweave'],
        website: 'https://arweave.org',
    },
    'livepeer': {
        coingecko: 'livepeer',
        coinmarketcap: '3640',
        defillama_chain: null,
        defillama_protocol: 'livepeer',
        github: ['livepeer/go-livepeer'],
        website: 'https://livepeer.org',
    },
    'helium': {
        coingecko: 'helium',
        coinmarketcap: '5665',
        defillama_chain: null,
        defillama_protocol: 'helium',
        github: ['helium/blockchain-core'],
        website: 'https://helium.com',
    },
    'hivemapper': {
        coingecko: 'hivemapper',
        coinmarketcap: '21478',
        defillama_chain: null,
        defillama_protocol: 'hivemapper',
        github: ['hivemapper/hivemapper'],
        website: 'https://hivemapper.com',
    },
    'iotex': {
        coingecko: 'iotex',
        coinmarketcap: '2777',
        defillama_chain: null,
        defillama_protocol: 'iotex',
        github: ['iotexproject/iotex-core'],
        website: 'https://iotex.io',
    },
    'peaq': {
        coingecko: 'peaq-2',
        coinmarketcap: '21588',
        defillama_chain: null,
        defillama_protocol: 'peaq',
        github: ['peaqnetwork/peaq-network-node'],
        website: 'https://www.peaq.network',
    },
    'geodnet': {
        coingecko: 'geodnet',
        coinmarketcap: '22567',
        defillama_chain: null,
        defillama_protocol: 'geodnet',
        github: ['geodnet/geonode'],
        website: 'https://www.geodnet.com',
    },
    'iagon': {
        coingecko: 'iagon',
        coinmarketcap: '3157',
        defillama_chain: null,
        defillama_protocol: 'iagon',
        github: ['IagonTech/Iagon-Storage'],
        website: 'https://iagon.com',
    },
    'api3': {
        coingecko: 'api3',
        coinmarketcap: '7733',
        defillama_chain: null,
        defillama_protocol: 'api3',
        github: ['api3dao/api3-dao'],
        website: 'https://api3.org',
    },
    'connext': {
        coingecko: 'connext',
        coinmarketcap: '21521',
        defillama_chain: null,
        defillama_protocol: 'connext',
        github: ['connext/monorepo'],
        website: 'https://www.connext.network',
    },
    'everclear': {
        coingecko: 'everclear',
        coinmarketcap: '29413',
        defillama_chain: null,
        defillama_protocol: 'everclear',
        github: ['everclear/contracts'],
        website: 'https://www.everclear.org',
    },
    'safe': {
        coingecko: 'safe',
        coinmarketcap: '20939',
        defillama_chain: null,
        defillama_protocol: 'safe',
        github: ['safe-global/safe-smart-account'],
        website: 'https://safe.global',
    },
    'layerzero': {
        coingecko: 'layerzero',
        coinmarketcap: '22092',
        defillama_chain: null,
        defillama_protocol: 'layerzero',
        github: ['LayerZero-Labs/LayerZero-v2'],
        website: 'https://layerzero.network',
    },

    // ────────── GAMING / NFT / METAVERSE ──────────
    'my-neighbor-alice': {
        coingecko: 'my-neighbor-alice',
        coinmarketcap: '14103',
        defillama_chain: null,
        defillama_protocol: 'my-neighbor-alice',
        github: ['MyNeighborAlice/land-sale'],
        website: 'https://www.myneighboralice.com',
    },
    'apecoin': {
        coingecko: 'apecoin',
        coinmarketcap: '17763',
        defillama_chain: null,
        defillama_protocol: 'apecoin',
        github: ['apecoin/contracts'],
        website: 'https://apecoin.com',
    },
    'axie-infinity': {
        coingecko: 'axie-infinity',
        coinmarketcap: '6783',
        defillama_chain: null,
        defillama_protocol: 'axie-infinity',
        github: ['axieinfinity/axie-contracts'],
        website: 'https://axieinfinity.com',
    },
    'beam': {
        coingecko: 'beam-2',
        coinmarketcap: '19875',
        defillama_chain: null,
        defillama_protocol: 'beam',
        github: ['Merit-Circle/beam-token-contract'],
        website: 'https://www.onbeam.com',
    },
    'big-time': {
        coingecko: 'big-time',
        coinmarketcap: '19233',
        defillama_chain: null,
        defillama_protocol: 'big-time',
        github: ['BigTimeGame/bigtime-contracts'],
        website: 'https://www.bigtime.gg',
    },
    'illuvium': {
        coingecko: 'illuvium',
        coinmarketcap: '8719',
        defillama_chain: null,
        defillama_protocol: 'illuvium',
        github: ['illuvium/contracts'],
        website: 'https://illuvium.io',
    },
    'immutable-x': {
        coingecko: 'immutable-x',
        coinmarketcap: '18346',
        defillama_chain: null,
        defillama_protocol: 'immutablex',
        github: ['immutable/imx-truffle-box'],
        website: 'https://www.immutable.com',
    },
    'defi-kingdoms': {
        coingecko: 'defi-kingdoms',
        coinmarketcap: '17867',
        defillama_chain: null,
        defillama_protocol: 'defi-kingdoms',
        github: ['DefiKingdoms/core'],
        website: 'https://www.defikingdoms.com',
    },
    'mobox': {
        coingecko: 'mobox',
        coinmarketcap: '9178',
        defillama_chain: null,
        defillama_protocol: 'mobox',
        github: ['MOBAMain/moba-core'],
        website: 'https://www.mobox.io',
    },
    'myria': {
        coingecko: 'myria',
        coinmarketcap: '21599',
        defillama_chain: null,
        defillama_protocol: 'myria',
        github: ['Myria-Development/myria-core'],
        website: 'https://myria.com',
    },
    'the-sandbox': {
        coingecko: 'the-sandbox',
        coinmarketcap: '6210',
        defillama_chain: null,
        defillama_protocol: 'the-sandbox',
        github: ['sandbox-game/sandbox-smart-contracts'],
        website: 'https://www.sandbox.game',
    },
    'yield-guild-games': {
        coingecko: 'yield-guild-games',
        coinmarketcap: '10588',
        defillama_chain: null,
        defillama_protocol: 'yield-guild-games',
        github: ['yieldguild/registry-contracts'],
        website: 'https://yieldguild.io',
    },
};

/**
 * Получить маппинг для проекта. Сначала по id, затем по coingeckoId.
 * @returns {Object|null} { coingecko, coinmarketcap, defillama_chain, defillama_protocol, ... }
 */
function getProviderIds(project) {
    if (!project) return null;
    const id = (project.id || '').toLowerCase();
    const cg = (project.coingeckoId || '').toLowerCase();

    if (PROVIDER_IDS[id]) return PROVIDER_IDS[id];
    if (PROVIDER_IDS[cg]) return PROVIDER_IDS[cg];
    return null;
}

/**
 * Создать базовый объект identifiers для проекта, даже если нет маппинга.
 */
function buildEmptyIdentifiers() {
    return {
        coingecko: null,
        coinmarketcap: null,
        defillama_chain: null,
        defillama_protocol: null,
        defillama_dex: null,
        github: [],
        x: null,
        website: null,
    };
}

module.exports = {
    PROVIDER_IDS,
    getProviderIds,
    buildEmptyIdentifiers,
};
